# -*- coding: utf-8 -*-
"""NF 终端面投影（**生成件 · 请勿手改**）。

真源：desktop/src/core/terminal.py 的策展表（ZONES / FAMILIES / FORMS / 写盘闸门三表 /
      BLOCKED_IN_SHELL）+ scripts/nf.py 的 argparse 面（命令存在性）。
生成：python scripts/nf.py shell --surface-write tui/_surface.py
判据：verify check39「投影与真源同步」+ desktop/tests/test_nf_tui.py
——本件被手改、或真源改了没重生成，都会在判据里当场判红（重算后逐字节比对）。
"""

KIND = 'nf-terminal-surface'
SCHEMA = 'nf-terminal-surface/1'
DIGEST = 'sha256:ebb1b2e7acca18c011891490474c9c7b29ff8197ef691bfe23ffd3546a36e047'
SOURCE = {'module': 'desktop/src/core/terminal.py',
 'tables': ['ZONES',
            'FAMILIES',
            'FORMS',
            'CONFIRM_FLAGS',
            'CONFIRM_VERBS',
            'CONFIRM_FLAG_PAIRS',
            'BLOCKED_IN_SHELL'],
 'commands': 'scripts/nf.py 的 argparse 面'}
COMMANDS = ['approve',
 'assemble',
 'assertions',
 'asset',
 'attest',
 'audit',
 'bench',
 'cognition',
 'combine',
 'completion',
 'conformance',
 'daemon',
 'decide',
 'decisions',
 'demo',
 'design',
 'diff',
 'doctor',
 'domain',
 'driver',
 'endpoint',
 'events',
 'explain',
 'handover',
 'help',
 'impact',
 'import',
 'interop',
 'knowledge',
 'layers',
 'library',
 'license',
 'lint',
 'lsp',
 'market',
 'model',
 'module',
 'output',
 'patterns',
 'pipeline',
 'postmortem',
 'preset',
 'receipts',
 'register',
 'related',
 'release',
 'rename',
 'render',
 'review',
 'rfc',
 'run',
 'score',
 'serve',
 'shell',
 'sig',
 'spec',
 'st-validate',
 'state-front',
 'stats',
 'telemetry',
 'terminal',
 'toolface',
 'transparency',
 'who-refers',
 'workloop',
 'worldmodel']
ROOT_FLAGS = ['--help', '--version', '-h']

ZONES = [{'key': '0',
  'id': 'doctor',
  'title': '环境自检',
  'family': 'start',
  'summary': '只读体检：仓库件在场 / 解释器可用 / 基线自描述一致性',
  'examples': ['nf doctor'],
  'forms': False,
  'actions': [{'key': 'doctor', 'title': '只读体检', 'argv': ['doctor'], 'params': [], 'note': ''},
              {'key': 'doctor-json',
               'title': '体检（机器面）',
               'argv': ['doctor', '--json'],
               'params': [],
               'note': ''}]},
 {'key': '1',
  'id': 'demo',
  'title': '一键演示世界',
  'family': 'start',
  'summary': 'P04 轻混全链跑一遍（retrieve→compose→gate→export）并产出 CCV3 卡',
  'examples': ['nf demo'],
  'forms': False,
  'actions': [{'key': 'demo',
               'title': '跑一遍 P04 全链',
               'argv': ['demo'],
               'params': [],
               'note': ''}]},
 {'key': '2',
  'id': 'assemble',
  'title': '需求 → 装配计划',
  'family': 'forge',
  'summary': '一句话需求 → 命中预设包或转用户自定义流；--check 验收成品',
  'examples': ['nf assemble "帮我组装一个西幻生存世界的完整版"', 'nf assemble 西幻生存 --check sample.md'],
  'forms': False,
  'actions': [{'key': 'assemble',
               'title': '一句话→装配计划',
               'argv': ['assemble', '{need}'],
               'params': [{'name': 'need',
                           'label': '需求（一句话）',
                           'kind': 'text',
                           'required': True}],
               'note': '产出装配计划文本，不落盘'},
              {'key': 'assemble-check',
               'title': '校验成品文档',
               'argv': ['assemble', '{file}', '--check'],
               'params': [{'name': 'file',
                           'label': '成品 .md（仓内路径）',
                           'kind': 'path',
                           'required': True}],
               'note': ''}]},
 {'key': '3',
  'id': 'run',
  'title': '全链生产',
  'family': 'forge',
  'summary': '选管线与模块 → 装配 → 质量门 → 导出（--seed 装载官方核心 + 社区包）',
  'examples': ['nf run --pipeline community/校园西幻轻混组合包/pipelines/P04_轻混装配流管线.md --modules '
               '通用类:M00,轻混类:M91,轻混类:M92,通用类:M80 --seed'],
  'forms': False,
  'actions': [{'key': 'run',
               'title': '跑全链管线',
               'argv': ['run', '--pipeline', '{pipeline}', '--modules', '{modules}', '--seed'],
               'params': [{'name': 'pipeline',
                           'label': '管线 .md（仓内路径）',
                           'kind': 'path',
                           'required': True},
                          {'name': 'modules',
                           'label': '模块 full_id（逗号分隔）',
                           'kind': 'text',
                           'required': True}],
               'note': ''},
              {'key': 'run-check',
               'title': '管线 dry-run',
               'argv': ['pipeline', 'dryrun', '{pipeline}'],
               'params': [{'name': 'pipeline',
                           'label': '管线 .md（仓内路径）',
                           'kind': 'path',
                           'required': True}],
               'note': ''}]},
 {'key': '4',
  'id': 'validate',
  'title': '校验与体检',
  'family': 'verify',
  'summary': '正文 lint / 状态前置 / 一致性分级 / 模块引用门禁（端壳时代「校验区」）',
  'examples': ['nf lint sample.md', 'nf conformance', 'nf module verify'],
  'forms': False,
  'actions': [{'key': 'conformance',
               'title': '契约一致性',
               'argv': ['conformance'],
               'params': [],
               'note': ''},
              {'key': 'layers',
               'title': '抽象阶梯核验',
               'argv': ['layers', '--verify'],
               'params': [],
               'note': ''},
              {'key': 'lint',
               'title': '文档语义体检',
               'argv': ['lint', '{file}'],
               'params': [{'name': 'file',
                           'label': '文档 .md（仓内路径）',
                           'kind': 'path',
                           'required': True}],
               'note': ''},
              {'key': 'module-verify',
               'title': '模块门禁',
               'argv': ['module', 'verify'],
               'params': [],
               'note': ''}]},
 {'key': '5',
  'id': 'market',
  'title': '货架与资产',
  'family': 'shelf',
  'summary': '市场浏览（--list）/ 单包详情 / 资产货架 / 供应链台账盘点',
  'examples': ['nf market --list', 'nf asset ls', 'nf asset inventory'],
  'forms': False,
  'actions': [{'key': 'market',
               'title': '市场货架',
               'argv': ['market', '--list'],
               'params': [],
               'note': ''},
              {'key': 'asset-ls',
               'title': '资产清单',
               'argv': ['asset', 'ls'],
               'params': [],
               'note': ''},
              {'key': 'asset-density',
               'title': '资产密度',
               'argv': ['asset', 'density'],
               'params': [],
               'note': ''},
              {'key': 'library-search',
               'title': '馆藏检索',
               'argv': ['library', 'search', '{query}'],
               'params': [{'name': 'query', 'label': '关键词', 'kind': 'text', 'required': True}],
               'note': ''}]},
 {'key': '6',
  'id': 'pipeline',
  'title': '管线与模块',
  'family': 'shelf',
  'summary': '管线派生（new）/ 抽象执行（dryrun）/ 模块状态位与边界签名',
  'examples': ['nf pipeline new --id P07 --name 演示领域管线', 'nf module ls'],
  'forms': False,
  'actions': [{'key': 'module-ls',
               'title': '模块清单',
               'argv': ['module', 'ls'],
               'params': [],
               'note': ''},
              {'key': 'patterns-ls',
               'title': '模式清单',
               'argv': ['patterns', 'ls'],
               'params': [],
               'note': ''},
              {'key': 'stats',
               'title': '自述数字核对',
               'argv': ['stats', '--check'],
               'params': [],
               'note': ''},
              {'key': 'stats-write',
               'title': '自述数字：重写生成区（写盘）',
               'argv': ['stats', '--write'],
               'params': [],
               'note': '会改仓库文件，须键入 yes 确认'}]},
 {'key': '7',
  'id': 'help',
  'title': '帮助与命令面',
  'family': 'meta',
  'summary': '全命令总览与任意子命令帮助（终端内输入 /help 同效）',
  'examples': ['nf --help', 'nf help assemble'],
  'forms': False,
  'actions': [{'key': 'help', 'title': '命令总览', 'argv': ['--help'], 'params': [], 'note': ''},
              {'key': 'help-cmd',
               'title': '看某命令帮助',
               'argv': ['help', '{cmd}'],
               'params': [{'name': 'cmd', 'label': '子命令名', 'kind': 'text', 'required': True}],
               'note': ''}]},
 {'key': '8',
  'id': 'forms',
  'title': '写盘表单',
  'family': 'meta',
  'summary': '会改仓库的动作逐项追问：表单真源 FORMS 的每一张都是一个可执行动作',
  'examples': [],
  'forms': True,
  'actions': [{'key': 'deprecate-module',
               'title': '弃用模块',
               'argv': ['module', 'deprecate', '{file}', '--reason', '{reason}'],
               'params': [{'name': 'file',
                           'label': '模块 md 路径',
                           'kind': 'path',
                           'required': True},
                          {'name': 'reason',
                           'label': '弃用原因（可空）',
                           'kind': 'text',
                           'required': False}],
               'note': '把某个模块文件标记为 deprecated（写文件头状态位）'},
              {'key': 'restore-module',
               'title': '恢复模块',
               'argv': ['module', 'restore', '{file}'],
               'params': [{'name': 'file',
                           'label': '模块 md 路径',
                           'kind': 'path',
                           'required': True}],
               'note': '把 deprecated / retired 的模块恢复为 active'},
              {'key': 'types-write',
               'title': '补 I/O 类型面',
               'argv': ['module', 'types', '--write'],
               'params': [],
               'note': '给有机读契约的模块补 io_types（确定性推导，未命中写 untyped）'},
              {'key': 'stats-write',
               'title': '重写自述数字生成区',
               'argv': ['stats', '--write'],
               'params': [],
               'note': '按实算重写 README / README.en / llms.txt 统计块与 protocol/repo_stats.json'},
              {'key': 'asset-add',
               'title': '资产入库',
               'argv': ['asset',
                        'add',
                        '{file}',
                        '--key',
                        '{key}',
                        '--source',
                        '{source}',
                        '--root',
                        '{root}',
                        '--module',
                        '{module}',
                        '--version',
                        '{version}',
                        '--tier',
                        '{tier}'],
               'params': [{'name': 'file',
                           'label': '资产文件路径（相对 --root）',
                           'kind': 'path',
                           'required': True},
                          {'name': 'key',
                           'label': '溯源键（台账内唯一）',
                           'kind': 'text',
                           'required': True},
                          {'name': 'source',
                           'label': '溯源说明（源文件/区间/登记日期）',
                           'kind': 'text',
                           'required': True},
                          {'name': 'root', 'label': '资产根目录', 'kind': 'path', 'required': True},
                          {'name': 'module',
                           'label': '消费模块 id（可空）',
                           'kind': 'text',
                           'required': False},
                          {'name': 'version',
                           'label': '版本位（可空 = 1.0）',
                           'kind': 'text',
                           'required': False},
                          {'name': 'tier',
                           'label': '货架分级 official/community/experimental（可空）',
                           'kind': 'text',
                           'required': False}],
               'note': '资产文件头写 nf-asset 头 + 台账 append（溯源键表自动生成）'},
              {'key': 'register-apply',
               'title': '本地登记写回',
               'argv': ['register', '{pkg_dir}', '--apply'],
               'params': [{'name': 'pkg_dir',
                           'label': '包目录',
                           'kind': 'path',
                           'required': True}],
               'note': 'protocol.yaml → registry protocols[]（校验全过后只增不删合并写）'},
              {'key': 'rename-apply',
               'title': '模块改名重链',
               'argv': ['rename', '{old_id}', '{new_id}', '--apply'],
               'params': [{'name': 'old_id',
                           'label': '旧模块 id',
                           'kind': 'text',
                           'required': True},
                          {'name': 'new_id',
                           'label': '新模块 id',
                           'kind': 'text',
                           'required': True}],
               'note': '批量更新 references 中对该模块的引用后写回'},
              {'key': 'receipts-write',
               'title': '重签协议层回执',
               'argv': ['receipts', '--scope', 'protocol', '--write'],
               'params': [],
               'note': '内容改动后重新冻结 protocol/RECEIPTS.json（随后通常重跑 conformance / 批准）'},
              {'key': 'preset-save',
               'title': '保存预设',
               'argv': ['preset',
                        'save',
                        '{name}',
                        '--pipeline',
                        '{pipeline}',
                        '--modules',
                        '{modules}',
                        '--assets',
                        '{assets}',
                        '{force}'],
               'params': [{'name': 'name', 'label': '预设名', 'kind': 'text', 'required': True},
                          {'name': 'pipeline',
                           'label': '管线 id（可空）',
                           'kind': 'text',
                           'required': False},
                          {'name': 'modules',
                           'label': '模块 full_id，逗号分隔（可空）',
                           'kind': 'text',
                           'required': False},
                          {'name': 'assets',
                           'label': '资产包名（可空）',
                           'kind': 'text',
                           'required': False},
                          {'name': 'force',
                           'label': '要覆盖同名预设就填 --force，否则留空',
                           'kind': 'text',
                           'required': False}],
               'note': '把一条装配清单存成本机预设（落在 NF_HOME，非仓库）'},
              {'key': 'library-deprecate',
               'title': '馆藏条目弃用',
               'argv': ['library', 'deprecate', '{entry}'],
               'params': [{'name': 'entry', 'label': '馆藏编号', 'kind': 'text', 'required': True}],
               'note': '生命周期流转 → deprecated（不再推荐、仍可读）'},
              {'key': 'library-restore',
               'title': '馆藏条目回退',
               'argv': ['library', 'restore', '{entry}'],
               'params': [{'name': 'entry', 'label': '馆藏编号', 'kind': 'text', 'required': True}],
               'note': '生命周期回退 → active'},
              {'key': 'pipeline-new',
               'title': '派生新管线',
               'argv': ['pipeline',
                        'new',
                        '--id',
                        '{id}',
                        '--name',
                        '{name}',
                        '--from',
                        '{from}',
                        '--domain',
                        '{domain}',
                        '--dest',
                        '{dest}'],
               'params': [{'name': 'id', 'label': '新管线 id', 'kind': 'text', 'required': True},
                          {'name': 'name', 'label': '显示名', 'kind': 'text', 'required': True},
                          {'name': 'from',
                           'label': '模板管线 md（可空 = 03_管线库/P00…）',
                           'kind': 'path',
                           'required': False},
                          {'name': 'domain',
                           'label': '领域标签（可空）',
                           'kind': 'text',
                           'required': False},
                          {'name': 'dest',
                           'label': '输出路径（可空 = 官方管线位）',
                           'kind': 'path',
                           'required': False}],
               'note': '自 P00 骨架派生新管线（改 id/name/领域标签；登记 02 与填层名挂载按 README 三步）'},
              {'key': 'approve-subject',
               'title': '批准内容绑定',
               'argv': ['approve', '{subject}', '--by', '{by}', '--note', '{note}'],
               'params': [{'name': 'subject',
                           'label': '被批准对象路径（仓库相对）',
                           'kind': 'path',
                           'required': True},
                          {'name': 'by',
                           'label': '批准人标识（可空）',
                           'kind': 'text',
                           'required': False},
                          {'name': 'note',
                           'label': '批准说明（可空）',
                           'kind': 'text',
                           'required': False}],
               'note': '给被批准对象落一条批准记录（protocol/approvals/*.json）'}]}]

FAMILIES = [{'id': 'start',
  'name': '上手与自检',
  'summary': '第一次进 NF：体检、一键演示、自述数字、抽象阶梯',
  'commands': ['doctor', 'demo', 'stats', 'layers']},
 {'id': 'forge',
  'name': '装配与生产',
  'summary': '从需求到产物：装配计划、预设（管线+模块+资产包一次组装）、全链管道、渲染、协议件读写、入库登记',
  'commands': ['assemble', 'preset', 'run', 'render', 'spec', 'register', 'import']},
 {'id': 'shelf',
  'name': '资产与货架',
  'summary': '市场、资产台账、模块生命周期、管线派生、组合引擎、域包工厂、产出形态',
  'commands': ['market',
               'asset',
               'module',
               'pipeline',
               'combine',
               'domain',
               'output',
               'rename']},
 {'id': 'verify',
  'name': '质检与验证',
  'summary': '正文 lint、一致性报告、断言表、知识签名、评分、差异、解释、状态前置、发布体检、许可证、遥测',
  'commands': ['lint',
               'conformance',
               'assertions',
               'sig',
               'score',
               'diff',
               'explain',
               'st-validate',
               'release',
               'license',
               'telemetry']},
 {'id': 'library',
  'name': '图书馆与知识',
  'summary': '馆藏存取、双源知识、行话术语、实践包、协议件版本史、引用关系与影响面',
  'commands': ['library',
               'knowledge',
               'cognition',
               'patterns',
               'rfc',
               'related',
               'who-refers',
               'impact']},
 {'id': 'govern',
  'name': '治理与决策',
  'summary': '决策记录（ADR）、审计、背书、回执、交接、复盘、决策层、评审、构建回路、批准、透明日志、设计审计',
  'commands': ['decisions',
               'audit',
               'attest',
               'receipts',
               'handover',
               'postmortem',
               'decide',
               'model',
               'review',
               'workloop',
               'approve',
               'transparency',
               'design']},
 {'id': 'integrate',
  'name': '服务与集成',
  'summary': 'MCP 服务面、编辑器面、跑分台、端点契约、互操作导出、指令档路由、事件背书、状态前置、世界模型、模块工具面',
  'commands': ['serve',
               'lsp',
               'bench',
               'endpoint',
               'interop',
               'driver',
               'events',
               'state-front',
               'worldmodel',
               'toolface']},
 {'id': 'meta',
  'name': '命令面与终端',
  'summary': '帮助、补全脚本、终端自身（本命令即在此族）',
  'commands': ['help', 'completion', 'shell', 'terminal', 'daemon']}]

FORMS = [{'id': 'deprecate-module',
  'title': '弃用模块',
  'summary': '把某个模块文件标记为 deprecated（写文件头状态位）',
  'steps': [{'key': 'file',
             'prompt': '模块 md 路径',
             'required': True,
             'hint': '如 community/<包>/modules/M97_术语管理.md'},
            {'key': 'reason', 'prompt': '弃用原因（可空）', 'required': False, 'hint': ''}],
  'argv': ['module', 'deprecate', '{file}', '--reason', '{reason}']},
 {'id': 'restore-module',
  'title': '恢复模块',
  'summary': '把 deprecated / retired 的模块恢复为 active',
  'steps': [{'key': 'file', 'prompt': '模块 md 路径', 'required': True, 'hint': ''}],
  'argv': ['module', 'restore', '{file}']},
 {'id': 'types-write',
  'title': '补 I/O 类型面',
  'summary': '给有机读契约的模块补 io_types（确定性推导，未命中写 untyped）',
  'steps': [],
  'argv': ['module', 'types', '--write']},
 {'id': 'stats-write',
  'title': '重写自述数字生成区',
  'summary': '按实算重写 README / README.en / llms.txt 统计块与 protocol/repo_stats.json',
  'steps': [],
  'argv': ['stats', '--write']},
 {'id': 'asset-add',
  'title': '资产入库',
  'summary': '资产文件头写 nf-asset 头 + 台账 append（溯源键表自动生成）',
  'steps': [{'key': 'file', 'prompt': '资产文件路径（相对 --root）', 'required': True, 'hint': ''},
            {'key': 'key', 'prompt': '溯源键（台账内唯一）', 'required': True, 'hint': ''},
            {'key': 'source', 'prompt': '溯源说明（源文件/区间/登记日期）', 'required': True, 'hint': ''},
            {'key': 'root', 'prompt': '资产根目录', 'required': True, 'hint': '如 05_资产库'},
            {'key': 'module', 'prompt': '消费模块 id（可空）', 'required': False, 'hint': ''},
            {'key': 'version', 'prompt': '版本位（可空 = 1.0）', 'required': False, 'hint': ''},
            {'key': 'tier',
             'prompt': '货架分级 official/community/experimental（可空）',
             'required': False,
             'hint': ''}],
  'argv': ['asset',
           'add',
           '{file}',
           '--key',
           '{key}',
           '--source',
           '{source}',
           '--root',
           '{root}',
           '--module',
           '{module}',
           '--version',
           '{version}',
           '--tier',
           '{tier}']},
 {'id': 'register-apply',
  'title': '本地登记写回',
  'summary': 'protocol.yaml → registry protocols[]（校验全过后只增不删合并写）',
  'steps': [{'key': 'pkg_dir',
             'prompt': '包目录',
             'required': True,
             'hint': '如 community/校园西幻轻混组合包'}],
  'argv': ['register', '{pkg_dir}', '--apply']},
 {'id': 'rename-apply',
  'title': '模块改名重链',
  'summary': '批量更新 references 中对该模块的引用后写回',
  'steps': [{'key': 'old_id', 'prompt': '旧模块 id', 'required': True, 'hint': ''},
            {'key': 'new_id', 'prompt': '新模块 id', 'required': True, 'hint': ''}],
  'argv': ['rename', '{old_id}', '{new_id}', '--apply']},
 {'id': 'receipts-write',
  'title': '重签协议层回执',
  'summary': '内容改动后重新冻结 protocol/RECEIPTS.json（随后通常重跑 conformance / 批准）',
  'steps': [],
  'argv': ['receipts', '--scope', 'protocol', '--write']},
 {'id': 'preset-save',
  'title': '保存预设',
  'summary': '把一条装配清单存成本机预设（落在 NF_HOME，非仓库）',
  'steps': [{'key': 'name', 'prompt': '预设名', 'required': True, 'hint': '如 西幻生存-最小'},
            {'key': 'pipeline', 'prompt': '管线 id（可空）', 'required': False, 'hint': '如 P04'},
            {'key': 'modules',
             'prompt': '模块 full_id，逗号分隔（可空）',
             'required': False,
             'hint': '如 通用类:M00,轻混类:M91'},
            {'key': 'assets', 'prompt': '资产包名（可空）', 'required': False, 'hint': ''},
            {'key': 'force',
             'prompt': '要覆盖同名预设就填 --force，否则留空',
             'required': False,
             'hint': ''}],
  'argv': ['preset',
           'save',
           '{name}',
           '--pipeline',
           '{pipeline}',
           '--modules',
           '{modules}',
           '--assets',
           '{assets}',
           '{force}']},
 {'id': 'library-deprecate',
  'title': '馆藏条目弃用',
  'summary': '生命周期流转 → deprecated（不再推荐、仍可读）',
  'steps': [{'key': 'entry', 'prompt': '馆藏编号', 'required': True, 'hint': '如 NF-1'}],
  'argv': ['library', 'deprecate', '{entry}']},
 {'id': 'library-restore',
  'title': '馆藏条目回退',
  'summary': '生命周期回退 → active',
  'steps': [{'key': 'entry', 'prompt': '馆藏编号', 'required': True, 'hint': ''}],
  'argv': ['library', 'restore', '{entry}']},
 {'id': 'pipeline-new',
  'title': '派生新管线',
  'summary': '自 P00 骨架派生新管线（改 id/name/领域标签；登记 02 与填层名挂载按 README 三步）',
  'steps': [{'key': 'id', 'prompt': '新管线 id', 'required': True, 'hint': '如 P07'},
            {'key': 'name', 'prompt': '显示名', 'required': True, 'hint': '如 演示领域管线'},
            {'key': 'from',
             'prompt': '模板管线 md（可空 = 03_管线库/P00…）',
             'required': False,
             'hint': ''},
            {'key': 'domain', 'prompt': '领域标签（可空）', 'required': False, 'hint': ''},
            {'key': 'dest', 'prompt': '输出路径（可空 = 官方管线位）', 'required': False, 'hint': ''}],
  'argv': ['pipeline',
           'new',
           '--id',
           '{id}',
           '--name',
           '{name}',
           '--from',
           '{from}',
           '--domain',
           '{domain}',
           '--dest',
           '{dest}']},
 {'id': 'approve-subject',
  'title': '批准内容绑定',
  'summary': '给被批准对象落一条批准记录（protocol/approvals/*.json）',
  'steps': [{'key': 'subject', 'prompt': '被批准对象路径（仓库相对）', 'required': True, 'hint': ''},
            {'key': 'by', 'prompt': '批准人标识（可空）', 'required': False, 'hint': ''},
            {'key': 'note', 'prompt': '批准说明（可空）', 'required': False, 'hint': ''}],
  'argv': ['approve', '{subject}', '--by', '{by}', '--note', '{note}']}]

GATES = {'flags': ['--write',
           '--apply',
           '--register',
           '--force',
           '--out',
           '--dest',
           '--build',
           '--write-baseline',
           '--fix',
           '--harvest',
           '--write-advisory',
           '--certify',
           '--save',
           '--surface-write'],
 'verbs': [['asset', 'add'],
           ['asset', 'rm'],
           ['asset', 'deprecate'],
           ['module', 'deprecate'],
           ['module', 'restore'],
           ['module', 'signature'],
           ['register', ''],
           ['import', ''],
           ['rename', ''],
           ['release', ''],
           ['pipeline', 'new'],
           ['decisions', 'reindex'],
           ['patterns', 'reindex'],
           ['library', 'reindex'],
           ['library', 'deprecate'],
           ['library', 'restore'],
           ['library', 'supersede'],
           ['library', 'attest'],
           ['approve', ''],
           ['asset', 'restore'],
           ['knowledge', 'transform'],
           ['preset', 'save'],
           ['preset', 'rm'],
           ['preset', 'import']],
 'pairs': [['interop', '--all'], ['assemble', '--trace'], ['assemble', '--session']]}

BLOCKED = {'lsp': 'lsp 是常驻 stdio 服务（等编辑器发 Content-Length 帧，会占住当前终端）：请由编辑器/IDE 直接拉起（nf lsp），本终端可继续用只读命令面。',
 'serve': 'serve 是长驻 MCP 服务（会占住当前终端）：请另开终端运行 nf serve <快照.json>，本终端可继续用只读命令面。',
 'shell': '终端内不再开终端（避免递归会话）：请另开一个终端窗口运行 nf shell。',
 'terminal': '终端内不再开终端（避免递归会话）：请另开一个终端窗口运行 nf shell。'}
