//! **由真源转录的常量表 —— 勿手改。**
//!
//! 出处：`desktop/src/core/doc_hygiene.py`（DOC_KINDS / REQUIRED_DOCS /
//! INSTRUCTION_DOCS / KINDS / KIND_RULES）。真源改表后须重生成，否则对账会红。
//!
//! 重生成：`python engine/rust/tools/gen_doc_tables.py <仓库根> <本文件>`

/// 文档四型。
pub const KINDS: [&str; 4] = [r#"tutorial"#, r#"how-to"#, r#"reference"#, r#"explanation"#];

/// 四型**写法**判据：(kind, must_any 正则, label)。
pub const KIND_RULES: [(&str, &[&str], &str); 4] = [
    (r#"how-to"#, &[r#"```"#, r#"python scripts/nf\.py"#, r#">\s*⛔"#], r#"可执行命令块"#),
    (r#"reference"#, &[r#"^\|.+\|"#, r#"词表"#, r#"字段"#], r#"词表或字段表"#),
    (r#"tutorial"#, &[r#"^\s*\d+[.、]\s"#, r#"步骤"#, r#"演练"#], r#"步骤序列"#),
    (r#"explanation"#, &[r#"为什么"#, r#"权衡"#, r#"机制"#, r#"原理"#], r#"为什么或权衡"#),
];

/// 文档 → 四型归属。
pub const DOC_KINDS: [(&str, &str); 48] = [
    (r#"01_核心协议.md"#, r#"reference"#),
    (r#"02_联动注册表.md"#, r#"reference"#),
    (r#"06_Agent执行协议.md"#, r#"how-to"#),
    (r#"07_官方核心出厂与社区预设导航.md"#, r#"reference"#),
    (r#"docs/meta/DEEP_DIVE.md"#, r#"explanation"#),
    (r#"docs/agent/AI_ROUTING.md"#, r#"how-to"#),
    (r#"docs/agent/agent_组装指令包_v0.2.md"#, r#"how-to"#),
    (r#"docs/mcp.md"#, r#"how-to"#),
    (r#"docs/ai-menu.md"#, r#"how-to"#),
    (r#"docs/ai-menu-fieldtest-v1.md"#, r#"how-to"#),
    (r#"docs/迁移指南-基于nf-sig-diff.md"#, r#"how-to"#),
    (r#"docs/attest.md"#, r#"how-to"#),
    (r#"docs/verification-cards.md"#, r#"reference"#),
    (r#"docs/需求收敛模板.md"#, r#"reference"#),
    (r#"docs/42_M1_协议可执行性自测规范.md"#, r#"reference"#),
    (r#"docs/42_M1_P03_演练集.md"#, r#"tutorial"#),
    (r#"docs/42_M2_回合状态头_v1.md"#, r#"reference"#),
    (r#"docs/42_M3_纯度体检.md"#, r#"reference"#),
    (r#"docs/44_M1_执行演练扩展.md"#, r#"tutorial"#),
    (r#"docs/44_M2_AI通道内容规范.md"#, r#"reference"#),
    (r#"docs/45_执行遥测规范.md"#, r#"reference"#),
    (r#"docs/45_M2_回合级drill.md"#, r#"tutorial"#),
    (r#"docs/45_M3_techdoc载荷提案.md"#, r#"explanation"#),
    (r#"docs/library.md"#, r#"how-to"#),
    (r#"docs/receipts.md"#, r#"how-to"#),
    (r#"docs/conformance.md"#, r#"how-to"#),
    (r#"docs/io_types.md"#, r#"reference"#),
    (r#"docs/pipelinerun.md"#, r#"how-to"#),
    (r#"docs/machine_contract.md"#, r#"how-to"#),
    (r#"docs/approval.md"#, r#"how-to"#),
    (r#"docs/module_signature.md"#, r#"how-to"#),
    (r#"docs/lsp.md"#, r#"how-to"#),
    (r#"docs/driver.md"#, r#"how-to"#),
    (r#"docs/patterns.md"#, r#"how-to"#),
    (r#"docs/bench.md"#, r#"how-to"#),
    (r#"docs/endpoint.md"#, r#"how-to"#),
    (r#"docs/rfc.md"#, r#"reference"#),
    (r#"docs/knowledge.md"#, r#"how-to"#),
    (r#"docs/assertions.md"#, r#"how-to"#),
    (r#"docs/modeling.md"#, r#"how-to"#),
    (r#"docs/interop.md"#, r#"how-to"#),
    (r#"docs/text-hygiene.md"#, r#"reference"#),
    (r#"docs/decision-layer.md"#, r#"how-to"#),
    (r#"docs/output-forms.md"#, r#"how-to"#),
    (r#"docs/domain-packs.md"#, r#"how-to"#),
    (r#"docs/combos.md"#, r#"how-to"#),
    (r#"docs/terminal.md"#, r#"how-to"#),
    (r#"docs/layers.md"#, r#"how-to"#),
];

/// 须带「最后更新」位的关键文档。
pub const REQUIRED_DOCS: [&str; 45] = [
    r#"01_核心协议.md"#,
    r#"02_联动注册表.md"#,
    r#"06_Agent执行协议.md"#,
    r#"07_官方核心出厂与社区预设导航.md"#,
    r#"docs/mcp.md"#,
    r#"docs/ai-menu.md"#,
    r#"docs/ai-menu-fieldtest-v1.md"#,
    r#"docs/迁移指南-基于nf-sig-diff.md"#,
    r#"docs/需求收敛模板.md"#,
    r#"docs/42_M1_协议可执行性自测规范.md"#,
    r#"docs/42_M1_P03_演练集.md"#,
    r#"docs/42_M2_回合状态头_v1.md"#,
    r#"docs/42_M3_纯度体检.md"#,
    r#"docs/agent/agent_组装指令包_v0.2.md"#,
    r#"docs/44_M1_执行演练扩展.md"#,
    r#"docs/44_M2_AI通道内容规范.md"#,
    r#"docs/45_执行遥测规范.md"#,
    r#"docs/45_M2_回合级drill.md"#,
    r#"docs/45_M3_techdoc载荷提案.md"#,
    r#"docs/meta/DEEP_DIVE.md"#,
    r#"docs/library.md"#,
    r#"docs/receipts.md"#,
    r#"docs/conformance.md"#,
    r#"docs/io_types.md"#,
    r#"docs/pipelinerun.md"#,
    r#"docs/machine_contract.md"#,
    r#"docs/approval.md"#,
    r#"docs/module_signature.md"#,
    r#"docs/lsp.md"#,
    r#"docs/driver.md"#,
    r#"docs/patterns.md"#,
    r#"docs/bench.md"#,
    r#"docs/endpoint.md"#,
    r#"docs/rfc.md"#,
    r#"docs/knowledge.md"#,
    r#"docs/assertions.md"#,
    r#"docs/modeling.md"#,
    r#"docs/interop.md"#,
    r#"docs/output-forms.md"#,
    r#"docs/domain-packs.md"#,
    r#"docs/combos.md"#,
    r#"docs/text-hygiene.md"#,
    r#"docs/decision-layer.md"#,
    r#"docs/terminal.md"#,
    r#"docs/layers.md"#,
];

/// 须带「⛔ 操作指令」标识头的指令类文档。
pub const INSTRUCTION_DOCS: [&str; 34] = [
    r#"docs/ai-menu.md"#,
    r#"docs/ai-menu-fieldtest-v1.md"#,
    r#"docs/迁移指南-基于nf-sig-diff.md"#,
    r#"docs/42_M1_协议可执行性自测规范.md"#,
    r#"docs/42_M1_P03_演练集.md"#,
    r#"docs/42_M2_回合状态头_v1.md"#,
    r#"docs/42_M3_纯度体检.md"#,
    r#"docs/agent/agent_组装指令包_v0.2.md"#,
    r#"docs/44_M1_执行演练扩展.md"#,
    r#"docs/44_M2_AI通道内容规范.md"#,
    r#"docs/45_执行遥测规范.md"#,
    r#"docs/45_M2_回合级drill.md"#,
    r#"docs/45_M3_techdoc载荷提案.md"#,
    r#"docs/agent/AI_ROUTING.md"#,
    r#"docs/library.md"#,
    r#"docs/receipts.md"#,
    r#"docs/conformance.md"#,
    r#"docs/pipelinerun.md"#,
    r#"docs/machine_contract.md"#,
    r#"docs/approval.md"#,
    r#"docs/module_signature.md"#,
    r#"docs/lsp.md"#,
    r#"docs/driver.md"#,
    r#"docs/patterns.md"#,
    r#"docs/bench.md"#,
    r#"docs/endpoint.md"#,
    r#"docs/rfc.md"#,
    r#"docs/knowledge.md"#,
    r#"docs/assertions.md"#,
    r#"docs/modeling.md"#,
    r#"docs/interop.md"#,
    r#"docs/decision-layer.md"#,
    r#"docs/terminal.md"#,
    r#"docs/layers.md"#,
];
