//! B 线包装声明门禁（`mcp-package`）—— 与真源 `desktop/src/core/mcp_package.py` 的 `scan` 对账。
//!
//! 核心判据是**红线「只读面不变」**：声明的 `tools` / `prompts` 必须与真源
//! `mcp_runtime.TOOL_DEFS` / `PROMPT_DEFS` **逐名一致**（多一个少一个即 FAIL）——
//! 这样"上架材料里写的工具列表"永远不会与真实运行时漂移。
//!
//! **移植面按消费者界定**：真源 `decl` 只被 `scan` 用；`warns`（草案待补提示）契约不看，
//! 故本线结构体未纳入。运行时名字表见 [`crate::mcp_tables`]。

use crate::jsonread;
use crate::pyjson::Json;
use crate::pyval::{get, py_str, str_list};
use std::path::Path;

pub const DECL_REL: &str = "protocol/mcp_package.json";
pub const SCHEMA: &str = "nf-mcp-package/1";
pub const CATEGORIES: [&str; 3] =
    ["content-creation", "developer-tools", "knowledge-management"];

pub struct McpScan {
    pub issues: Vec<String>,
    pub stats: Json,
}

/// 真源 `scan`。
pub fn scan(root: &Path) -> McpScan {
    let mut issues: Vec<String> = Vec::new();
    let Some(d) = jsonread::read_file(root, DECL_REL) else {
        return McpScan {
            issues: vec![format!("缺 B 线包装声明 {}", DECL_REL)],
            stats: Json::Object(Vec::new()),
        };
    };
    if py_str(get(&d, "schema")) != SCHEMA {
        issues.push(format!("包装声明 schema 不匹配（期望 {}）", SCHEMA));
    }
    if str_list(get(&d, "category_vocabulary")) != CATEGORIES.to_vec() {
        issues.push(format!("类目词表与判据不一致（期望 {}）", CATEGORIES.join("/")));
    }
    if crate::pyval::arr_is_empty(get(&d, "red_lines")) {
        issues.push("红线不得为空（上架包的纪律必须成文）".to_string());
    }
    if py_str(get(&d, "status")) == "draft" && crate::pyval::arr_is_empty(get(&d, "pending")) {
        issues.push("status=draft 但 pending 为空——草案必须写明还差什么".to_string());
    }
    let pkg = get(&d, "package")
        .filter(|p| matches!(p, Json::Object(_)))
        .cloned()
        .unwrap_or_else(|| Json::Object(Vec::new()));
    if crate::pyval::arr_is_empty(get(&pkg, "name_candidates")) {
        issues.push("缺命名候选（B-S1 须给候选）".to_string());
    }
    if crate::pyval::arr_is_empty(get(&pkg, "one_liner_candidates")) {
        issues.push("缺一句话候选（B-S1 须给候选）".to_string());
    }
    if !CATEGORIES.contains(&py_str(get(&pkg, "category")).as_str()) {
        issues.push(format!("类目越词表：{}", py_str(get(&pkg, "category"))));
    }

    // 红线「只读面不变」：与运行时逐名一致（名字表见 `mcp_tables`）
    let live_tools: Vec<String> =
        crate::mcp_tables::TOOL_NAMES.iter().map(|s| (*s).to_string()).collect();
    let live_prompts: Vec<String> =
        crate::mcp_tables::PROMPT_NAMES.iter().map(|s| (*s).to_string()).collect();
    let got_tools: Vec<String> = str_list(get(&pkg, "tools"));
    let got_prompts: Vec<String> = str_list(get(&pkg, "prompts"));

    let mut a = got_tools.clone();
    let mut b = live_tools.clone();
    a.sort();
    b.sort();
    if a != b {
        let extra = minus(&got_tools, &live_tools);
        let missing = minus(&live_tools, &got_tools);
        issues.push(format!(
            "工具面与运行时不一致（上架材料会漂移）：声明 {} 个 / 运行时 {} 个（多：{}；少：{}）",
            got_tools.len(),
            live_tools.len(),
            if extra.is_empty() { "无".to_string() } else { py_repr_list(&extra) },
            if missing.is_empty() { "无".to_string() } else { py_repr_list(&missing) }
        ));
    }
    let mut c = got_prompts.clone();
    let mut e = live_prompts.clone();
    c.sort();
    e.sort();
    if c != e {
        issues.push(format!(
            "提示面与运行时不一致：声明 {} / 运行时 {}",
            py_repr_list(&got_prompts),
            py_repr_list(&live_prompts)
        ));
    }

    let stats = Json::Object(vec![
        ("tools".to_string(), Json::Int(got_tools.len() as i64)),
        ("prompts".to_string(), Json::Int(got_prompts.len() as i64)),
        (
            "targets".to_string(),
            Json::Int(
                crate::pyval::arr_items(get(&pkg, "targets")).len() as i64,
            ),
        ),
        ("category".to_string(), Json::Str(py_str(get(&pkg, "category")))),
    ]);
    McpScan { issues, stats }
}

fn minus(a: &[String], b: &[String]) -> Vec<String> {
    a.iter().filter(|x| !b.contains(x)).cloned().collect()
}

/// Python `sorted(set)` 的 `%s` 形态（`['a', 'b']` 或 `无` 由调用方补）。
fn py_repr_list(v: &[String]) -> String {
    let mut s: Vec<String> = v.to_vec();
    s.sort();
    s.dedup();
    format!(
        "[{}]",
        s.iter().map(|x| format!("'{}'", x)).collect::<Vec<_>>().join(", ")
    )
}

/// 供契约层用：`stats.category` 的 `?` 兜底（真源 `stats.get("category", "?")`）。
pub fn category_or_unknown(stats: &Json) -> String {
    match get(stats, "category") {
        Some(Json::Str(s)) => s.clone(),
        _ => "?".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    // >>> GENERATED by tools/gen_mcp_package_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_mcp_package_branches.py` 从真源生成）=====
    ///
    /// 四场景：kitchen（逐分支）/ 全绿 / 草案（pending 非空 ⇒ warn，不判死）/ 缺声明。
    /// 分支：schema / 类目词表 / 红线为空 / draft 但 pending 空 / 缺命名候选 / 缺一句话候选 /
    /// 类目越词表 / **工具面与运行时不一致** / **提示面与运行时不一致** / 缺声明。
    /// 注：真源 `scan` 的 warns（草案待补）契约不看，故本线结构体未纳入；`want_warns` 仅作记录。
    const MCP_KITCHEN: &str = r#"{"schema": "wrong/1", "category_vocabulary": ["nope"], "red_lines": [], "status": "draft", "pending": [], "package": {"name_candidates": [], "one_liner_candidates": [], "category": "bogus", "tools": ["not_a_tool"], "prompts": [], "targets": ["a"]}}"#;
    const MCP_GREEN: &str = r#"{"schema": "nf-mcp-package/1", "category_vocabulary": ["content-creation", "developer-tools", "knowledge-management"], "red_lines": ["只读面不变"], "status": "published", "package": {"name_candidates": ["NF 内容质检"], "one_liner_candidates": ["一句话"], "category": "content-creation", "tools": ["asset_get", "knowledge_order", "library_read", "library_search", "module_read", "pattern_read", "pipeline_ls", "pipeline_read", "registry_query", "spec_ls"], "prompts": ["assemble_guide"], "targets": ["a", "b", "c", "d"]}}"#;
    const MCP_DRAFT: &str = r#"{"schema": "nf-mcp-package/1", "category_vocabulary": ["content-creation", "developer-tools", "knowledge-management"], "red_lines": ["只读面不变"], "status": "draft", "package": {"name_candidates": ["NF 内容质检"], "one_liner_candidates": ["一句话"], "category": "content-creation", "tools": ["asset_get", "knowledge_order", "library_read", "library_search", "module_read", "pattern_read", "pipeline_ls", "pipeline_read", "registry_query", "spec_ls"], "prompts": ["assemble_guide"], "targets": ["a", "b", "c", "d"]}, "pending": ["还差上架材料"]}"#;

    fn build_mcp_fixture(scenario: &str, decl: Option<&str>) -> std::path::PathBuf {
        let root = crate::testutil::fixture(&format!("mcp-package-branches-{}", scenario));
        std::fs::create_dir_all(root.join("protocol")).unwrap();
        if let Some(d) = decl {
            std::fs::write(root.join("protocol/mcp_package.json"), d).unwrap();
        }
        root
    }

    #[test]
    fn scan_matches_truth_source_in_all_four_scenarios() {
        for (scenario, decl, want_issues, want_warns, want_stats) in [
            ("kitchen", Some(MCP_KITCHEN), &["包装声明 schema 不匹配（期望 nf-mcp-package/1）", "类目词表与判据不一致（期望 content-creation/developer-tools/knowledge-management）", "红线不得为空（上架包的纪律必须成文）", "status=draft 但 pending 为空——草案必须写明还差什么", "缺命名候选（B-S1 须给候选）", "缺一句话候选（B-S1 须给候选）", "类目越词表：bogus", "工具面与运行时不一致（上架材料会漂移）：声明 1 个 / 运行时 10 个（多：['not_a_tool']；少：['asset_get', 'knowledge_order', 'library_read', 'library_search', 'module_read', 'pattern_read', 'pipeline_ls', 'pipeline_read', 'registry_query', 'spec_ls']）", "提示面与运行时不一致：声明 [] / 运行时 ['assemble_guide']"] as &[&str], &[] as &[&str], crate::pyjson::Json::Object(vec![("category".to_string(), crate::pyjson::Json::Str("bogus".to_string())), ("prompts".to_string(), crate::pyjson::Json::Int(0)), ("targets".to_string(), crate::pyjson::Json::Int(1)), ("tools".to_string(), crate::pyjson::Json::Int(1))])),
            ("green", Some(MCP_GREEN), &[] as &[&str], &[] as &[&str], crate::pyjson::Json::Object(vec![("category".to_string(), crate::pyjson::Json::Str("content-creation".to_string())), ("prompts".to_string(), crate::pyjson::Json::Int(1)), ("targets".to_string(), crate::pyjson::Json::Int(4)), ("tools".to_string(), crate::pyjson::Json::Int(10))])),
            ("draft", Some(MCP_DRAFT), &[] as &[&str], &["包装声明为草案：1 项待补（还差上架材料）"] as &[&str], crate::pyjson::Json::Object(vec![("category".to_string(), crate::pyjson::Json::Str("content-creation".to_string())), ("prompts".to_string(), crate::pyjson::Json::Int(1)), ("targets".to_string(), crate::pyjson::Json::Int(4)), ("tools".to_string(), crate::pyjson::Json::Int(10))])),
            ("nodecl", None, &["缺 B 线包装声明 protocol/mcp_package.json"] as &[&str], &[] as &[&str], crate::pyjson::Json::Object(Vec::new())),
        ] {
            let root = build_mcp_fixture(scenario, decl);
            let got = scan(&root);
            assert_eq!(got.issues, want_issues, "场景 {} 的 issues", scenario);
            let _ = want_warns;   // 真源 warns 在本面无消费者，未纳入移植面
            assert!(
                crate::jsonread::json_eq(&got.stats, &want_stats),
                "场景 {} 的 stats：实得 {:?}",
                scenario,
                got.stats
            );
        }
    }
    // <<< GENERATED
}
