//! `output_forms` 依赖的两张转录表 —— 由 `tools/gen_output_tables.py` 生成，**勿手改**。
//!
//! - `QUANT_METRICS_NAMES`：真源 `_check_quant_metrics` 用 `hasattr(qm, fn)` 判
//!   「宣称的引擎是否真实存在」（宣称≠实现）；
//! - `DOMAIN_FAMILIES`：真源 `_check_domain_report` 用它判「度量族是否在本仓登记」。
//!
//! ⚠️ 两者都随真源源码变。改了 `quant_metrics.py` / `domain_metrics.py` 后须重跑生成器，
//! 否则对账会红（这正是要的：宁可红，也不要静默用旧表判"实现存在"）。

// >>> GENERATED by tools/gen_output_tables.py（勿手改；重跑生成器覆盖本段）
#[rustfmt::skip]
pub const QUANT_METRICS_NAMES: [&str; 29] = [
    "ANNUAL_FACTORS",
    "DIGITS",
    "GIPS_ALIGNMENT",
    "_block",
    "_geo_link",
    "_mean",
    "_pearson",
    "_r",
    "_rank",
    "_stdev",
    "annualized_return",
    "annualized_volatility",
    "calmar",
    "cumulative_return",
    "drawdown_series",
    "information_coefficient",
    "information_ratio",
    "load_equity_curve",
    "log_returns",
    "max_drawdown",
    "mermaid_declaration_flow",
    "performance_report",
    "returns",
    "sharpe",
    "simple_returns",
    "tracking_error",
    "turnover",
    "vega_drawdown",
    "vega_equity_curve",
];

#[rustfmt::skip]
pub const DOMAIN_FAMILIES: [&str; 12] = [
    "agreement",
    "calibration",
    "classification",
    "contract_compliance",
    "drift",
    "exact_judgement",
    "extraction",
    "generation",
    "latency_cost",
    "preference",
    "regression",
    "retrieval",
];
// <<< GENERATED

// >>> GENERATED by tools/gen_pack_combo_tables.py（勿手改；重跑生成器覆盖本段）
/// 真源 `pack_combo.CERT_REL`。
pub const CERT_REL: &str = "protocol/combo_certificates.json";

/// 真源 `pack_combo.CORE13`（`_core_ids()` 的基）。
#[rustfmt::skip]
pub const CORE13: [&str; 13] = [
    "M00",
    "通用:M10",
    "M08",
    "M23",
    "M24",
    "M50",
    "M80",
    "事件:M22",
    "M06",
    "M12",
    "M13",
    "M20",
    "M90",
];

/// 真源 `pack_combo.CERT_SCHEMA`（**数据**，按规范 JSON 转录；用时解析）。
pub const CERT_SCHEMA_JSON: &str = r#"{"$schema": "https://json-schema.org/draft/2020-12/schema", "additionalProperties": false, "properties": {"assets_borrowed": {"type": "array"}, "assets_unresolved": {"maxItems": 0, "type": "array"}, "dependency_closure": {"additionalProperties": false, "properties": {"core": {"type": "array"}, "dangling": {"maxItems": 0, "type": "array"}, "explicit": {"type": "array"}}, "required": ["core", "explicit", "dangling"], "type": "object"}, "digest": {"pattern": "^[0-9a-f]{32}$", "type": "string"}, "event_closure": {"additionalProperties": false, "properties": {"published": {"type": "array"}, "unbridged": {"maxItems": 0, "type": "array"}}, "required": ["published", "unbridged"], "type": "object"}, "events_unpublished": {"maxItems": 0, "type": "array"}, "extra_modules": {"items": {"type": "string"}, "type": "array"}, "label": {"minLength": 2, "type": "string"}, "layer_stacks": {"items": {"additionalProperties": false, "properties": {"layer": {"minLength": 3, "type": "string"}, "modules": {"items": {"minLength": 2, "type": "string"}, "minItems": 1, "type": "array"}}, "required": ["layer", "modules"], "type": "object"}, "minItems": 1, "type": "array"}, "legal": {"const": true}, "module_count": {"minimum": 1, "type": "integer"}, "module_missing_contract": {"maxItems": 0, "type": "array"}, "modules": {"items": {"type": "string"}, "minItems": 1, "type": "array"}, "modules_borrowed": {"type": "array"}, "note": {"minLength": 4, "type": "string"}, "packs": {"items": {"minLength": 2, "type": "string"}, "type": "array"}, "references_unresolved": {"maxItems": 0, "type": "array"}, "schema": {"const": "nf-combo/1"}, "unknown_packs": {"items": {"type": "string"}, "type": "array"}}, "required": ["schema", "packs", "modules", "module_count", "layer_stacks", "dependency_closure", "event_closure", "legal", "digest"], "title": "nf-combo/1 组合证书", "type": "object"}"#;
// <<< GENERATED
