//! 类型积压台账（`type-backlog`）—— 与真源 `desktop/src/core/payload_harvest.py` 的
//! `backlog` / `verify_backlog` 对账。
//!
//! 判据：台账 **== 实时重算**（`count` 一致），且**无「无 note 的 untyped」**（不许无声增长）。
//!
//! **移植面按消费者界定**：契约 `_c_type_backlog` 只走 `verify_backlog`，而它只调 `backlog`
//! ——真源同模块的 `harvest` / `harvest_doc`（141 行正文收割）**完全不在链上**，
//! `apply` 是写面，`stats` 无消费者，故均不移植。连 `backlog` 返回的完整 doc
//! (`schema`/`note`/`fields`) 也只要 `missing_note` 与 `count` 两样。
//!
//! **已知偏差（fail-closed）**：真源 `backlog` 用 `json.loads(...)` 且**不检查文件在否**，
//! 注册表缺失或坏 JSON 会抛异常 ⇒ 整条判据记 **ERROR**；本线返回一条显式 issue ⇒ 记 **FAIL**。
//! 两边都是红的，只是状态不同（真语料上注册表恒在场，故不触发）。

use crate::jsonread;
use crate::pyjson::Json;
use crate::pyval::{get, py_str};
use std::path::Path;

pub const EVENT_REGISTRY: &str = "protocol/event_registry.json";
pub const BACKLOG_REL: &str = "protocol/type_backlog.json";

pub struct Backlog {
    /// 无 note 的 untyped 字段（按 事件、字段 排序）。
    pub missing_note: Vec<String>,
    /// untyped 字段总数。
    pub count: i64,
    /// 注册表不在场/不可解析（真源在此抛异常）。
    pub unavailable: bool,
}

/// 真源 `backlog`：把**不可从证据推断**的 untyped 字段显式化（可数、不隐身）。
pub fn backlog(root: &Path) -> Backlog {
    let Some(data) = jsonread::read_file(root, EVENT_REGISTRY) else {
        return Backlog { missing_note: Vec::new(), count: 0, unavailable: true };
    };
    let mut missing_note: Vec<String> = Vec::new();
    let mut count = 0i64;
    if let Some(Json::Object(events)) = get(&data, "events") {
        // 真源 `sorted(events.items())` / `sorted(fields.items())`；`jsonread` 保插入序，
        // 故这里显式排序以对齐"排序后遍历"的口径。
        let mut evs: Vec<(&String, &Json)> = events.iter().map(|(k, v)| (k, v)).collect();
        evs.sort_by(|a, b| a.0.cmp(b.0));
        for (ev, body) in evs {
            let Some(Json::Object(fields)) = get(body, "fields") else { continue };
            let mut fs: Vec<(&String, &Json)> = fields.iter().map(|(k, v)| (k, v)).collect();
            fs.sort_by(|a, b| a.0.cmp(b.0));
            for (f, spec) in fs {
                if py_str(get(spec, "type")) != "untyped" {
                    continue;
                }
                count += 1;
                let note = py_str(get(spec, "note")).trim().to_string();
                if note.is_empty() {
                    missing_note.push(format!("{}.{}", ev, f));
                }
            }
        }
    }
    Backlog { missing_note, count, unavailable: false }
}

/// 真源 `verify_backlog` → `(issues, stats)`。
pub fn verify_backlog(root: &Path) -> (Vec<String>, Json) {
    let live = backlog(root);
    let mut issues: Vec<String> = Vec::new();
    if live.unavailable {
        issues.push(format!(
            "缺类型积压台账所需的事件注册表 {}（本线自拟措辞；真源在此抛异常记 ERROR）",
            EVENT_REGISTRY
        ));
        return (
            issues,
            Json::Object(vec![("untyped".to_string(), Json::Int(0))]),
        );
    }
    if !live.missing_note.is_empty() {
        issues.push(format!(
            "存在无 note 的 untyped 字段（无声增长）：{}",
            live.missing_note.iter().take(3).cloned().collect::<Vec<_>>().join("、")
        ));
    }
    let p = root.join(BACKLOG_REL);
    if !p.is_file() {
        issues.push(format!(
            "缺类型积压台账 {}（修复指引：nf module types --backlog --write）",
            BACKLOG_REL
        ));
    } else {
        match jsonread::read_file(root, BACKLOG_REL) {
            Some(c) => {
                // 真源 `committed.get("count")` 后走 `%s` ⇒ 缺键渲染成 `None`
                let recorded = crate::pyval::plain_str_opt(get(&c, "count"));
                if recorded != live.count.to_string() {
                    issues.push(format!(
                        "台账过期：记录 {} ≠ 实测 {}（修复指引：重写台账）",
                        recorded, live.count
                    ));
                }
            }
            None => issues.push("台账 JSON 不可解析".to_string()),
        }
    }
    (
        issues,
        Json::Object(vec![("untyped".to_string(), Json::Int(live.count))]),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    // >>> GENERATED by tools/gen_type_backlog_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_type_backlog_branches.py` 从真源生成）=====
    ///
    /// 四场景：无声增长 + count 不符 / 有 note 但台账缺件 / 台账坏 JSON / 全绿。
    /// 分支：无 note 的 untyped（无声增长）/ 缺台账 / 台账不可解析 / 台账过期（count 不符）/ 全绿。
    const TB_REG_KITCHEN: &str = r#"{"schema": "x", "events": {"e1": {"fields": {"a": {"type": "untyped"}, "b": {"type": "untyped", "note": "有据"}}}, "e2": {"fields": {"c": {"type": "string"}}}}}"#;
    const TB_REG_NOLEDGER: &str = r#"{"schema": "x", "events": {"e1": {"fields": {"a": {"type": "untyped", "note": "n"}}}}}"#;

    fn build_tb_fixture(scenario: &str, reg: &str, ledger: Option<&str>) -> std::path::PathBuf {
        let root = crate::testutil::fixture(&format!("type-backlog-branches-{}", scenario));
        std::fs::create_dir_all(root.join("protocol")).unwrap();
        std::fs::write(root.join("protocol/event_registry.json"), reg).unwrap();
        if let Some(l) = ledger {
            std::fs::write(root.join("protocol/type_backlog.json"), l).unwrap();
        }
        root
    }

    #[test]
    fn verify_backlog_matches_truth_source_in_all_four_scenarios() {
        for (scenario, reg, ledger, want_issues, want_untyped) in [
            ("kitchen", TB_REG_KITCHEN, Some(r#"{"count": 99}"#), &["存在无 note 的 untyped 字段（无声增长）：e1.a", "台账过期：记录 99 ≠ 实测 2（修复指引：重写台账）"] as &[&str], 2),
            ("noledger", TB_REG_NOLEDGER, None, &["缺类型积压台账 protocol/type_backlog.json（修复指引：nf module types --backlog --write）"] as &[&str], 1),
            ("badjson", TB_REG_NOLEDGER, Some("{ 这不是 JSON"), &["台账 JSON 不可解析"] as &[&str], 1),
            ("green", TB_REG_NOLEDGER, Some(r#"{"count": 1}"#), &[] as &[&str], 1),
        ] {
            let root = build_tb_fixture(scenario, reg, ledger);
            let (issues, stats) = verify_backlog(&root);
            assert_eq!(issues, want_issues, "场景 {} 的 issues", scenario);
            assert!(crate::jsonread::json_eq(
                &stats,
                &crate::jsonread::convert(&serde_json::json!({"untyped": want_untyped})).unwrap()
            ));
        }
    }
    // <<< GENERATED
}
