//! 公开导出面泄漏审计（`public-surface`）—— 真源把这条**直接写在 `conformance_report.py` 里**
//!（没有独立的 core 模块），本线照此落地。
//!
//! 判据：对外产物（外部验证资产面）里**不得出现绝对路径**——作者机路径泄漏进公开仓是
//! 不可回滚的暴露（提交历史里擦不掉）。
//!
//! 只读；`_c_public_surface` 原本就在契约包装层，故本模块无对应 core 模块可指。

use std::path::Path;

/// 真源 `EXPORT_GLOBS`。
pub const EXPORT_GLOBS: [&str; 2] = [
    "desktop/tests/fixtures/external/**/*",
    "docs/external-validation-assets/*",
];

/// ⚠️ 该模式含**后顾断言** `(?<![A-Za-z0-9])`——Rust 的 `regex` crate **不支持 look-around**，
/// 用它会在启动时 panic（实测踩过）。本线走已依赖的 `fancy-regex`（基于 regex 但走回溯，
/// `contracts.rs` 的断言算子也在用它）。
fn abs_path_re() -> &'static fancy_regex::Regex {
    static RE: std::sync::OnceLock<fancy_regex::Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| {
        fancy_regex::Regex::new(r"(?<![A-Za-z0-9])[A-Za-z]:[\\/]|/Users/|/home/[a-z]|\\Users\\")
            .expect("绝对路径正则固定合法")
    })
}

/// 真源 `_c_public_surface` → `(issues, 说明)`。
pub fn scan(root: &Path) -> (Vec<String>, String) {
    let mut bad: Vec<String> = Vec::new();
    let mut seen: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for pat in EXPORT_GLOBS {
        for rel in crate::glob::expand(root, pat) {
            if !seen.insert(rel.clone()) {
                continue;
            }
            if !rel.ends_with(".md")
                && !rel.ends_with(".json")
                && !rel.ends_with(".yaml")
                && !rel.ends_with(".yml")
                && !rel.ends_with(".txt")
            {
                continue;
            }
            // 尽力而为：跳过不可读/非 UTF-8 项（该类缺口由对应门禁另行报出，见真源 AUD-0016）
            let Ok(text) = std::fs::read_to_string(root.join(&rel)) else { continue };
            if abs_path_re().is_match(&text).unwrap_or(false) {
                bad.push(format!("{} 含绝对路径", rel));
            }
        }
    }
    let ok = bad.is_empty();
    let detail = if ok {
        "公开导出面零泄漏".to_string()
    } else {
        bad.iter().take(2).cloned().collect::<Vec<_>>().join("; ")
    };
    (bad, detail)
}

/// 供契约表复用的 `(ok, detail)`。
pub fn contract(root: &Path) -> (bool, String) {
    let (bad, detail) = scan(root);
    (bad.is_empty(), detail)
}

#[cfg(test)]
mod tests {
    use super::*;
    // >>> GENERATED by tools/gen_public_surface_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_public_surface_branches.py` 从真源生成）=====
    ///
    /// 契约在真语料上**全绿** ⇒ 对账核不到错误分支。而它的判据依赖一个**含后顾断言**的正则
    /// （`(?<![A-Za-z0-9])`——Rust `regex` 不支持、本线走 `fancy-regex`），故四个变体都该被钉住：
    /// 驱动器号 + `\Users\` / `/Users/` / `/home/x`；另加「后缀不在白名单 ⇒ 跳过」与
    /// 「前一个字符是字母数字 ⇒ 后顾断言不命中」两个边界。
    const PS_FILES: [(&str, &str); 7] = [
        ("desktop/tests/fixtures/external/sub/adjacent.md", r#"abcC:/x
"#),
        ("desktop/tests/fixtures/external/sub/deep.md", r#"D:/x
"#),
        ("docs/external-validation-assets/clean.txt", r#"没有绝对路径
"#),
        ("docs/external-validation-assets/drive.md", r#"# x
见 C:\Users\bob\nf
"#),
        ("docs/external-validation-assets/lin.yaml", r#"p: /home/bob/nf
"#),
        ("docs/external-validation-assets/mac.json", r#"{"p": "/Users/bob/nf"}
"#),
        ("docs/external-validation-assets/skip.png", r#"C:\Users\bob
"#),
    ];

    fn build_ps_fixture() -> std::path::PathBuf {
        let root = crate::testutil::fixture("public-surface-branches");
        for (rel, body) in PS_FILES {
            let p = root.join(rel);
            std::fs::create_dir_all(p.parent().unwrap()).unwrap();
            std::fs::write(p, body).unwrap();
        }
        root
    }

    #[test]
    fn contract_matches_truth_source_branch_by_branch() {
        let root = build_ps_fixture();
        let (ok, detail) = contract(&root);
        assert_eq!(ok, false, "ok 须与真源一致");
        assert_eq!(detail, "desktop/tests/fixtures/external/sub/deep.md 含绝对路径; docs/external-validation-assets/drive.md 含绝对路径", "detail 字面须与真源一致");
        // 真源 `_c_public_surface` **只暴露 `(ok, detail)`**，而 detail 是 `"; ".join(bad[:2])`
        // ——**它把清单截断到前两条**，总条数根本不在外露面上。
        // 故这里只断言真源确实暴露的东西：ok、detail 字面、以及本线 issues 的**前两条**与之相同。
        // **不发明期望值**（这是本线对"期望值只能来自真源"的具体执行）。
        let (issues, _d) = scan(&root);
        assert!(issues.len() >= 2, "至少应命中 detail 里那两条");
        for (i, want) in ["desktop/tests/fixtures/external/sub/deep.md 含绝对路径", "docs/external-validation-assets/drive.md 含绝对路径"].iter().enumerate() {
            assert_eq!(&issues[i], want, "第 {} 条", i + 1);
        }
    }
    // <<< GENERATED
}
