"""为 `asset_contract` 的**代码面 / 脚本面 / 聚合**生成验证判据。

数据面已有独立判据（`gen_asset_data_cases.py`）。这里补：

1. **真实声明的代码面逐条**：`_check_code`（`deny_calls` + 可证空指针 + 测试件在场）；
2. **真实声明的脚本面逐条**：`_check_script`（`nf-io` 双源 + 未声明字面路径）；
3. **链**：`_check_chain`；
4. **聚合**：`scan(root)` 的三元组。

用法：python engine/rust/tools/gen_asset_code_cases.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import asset_contract as ac  # noqa: E402

doc = json.loads((ROOT / 'protocol' / 'asset_contracts.json').read_text(encoding='utf-8'))

code_rows = []
for spec in doc.get('code') or []:
    issues, stats = ac._check_code(str(ROOT), spec)
    code_rows.append((spec, issues, stats))
    print('# 代码 %-22s issues=%d stats=%s' % (spec.get('id'), len(issues),
                                           json.dumps(stats, ensure_ascii=False, sort_keys=True)))

script_rows = []
for spec in doc.get('script') or []:
    issues, stats = ac._check_script(str(ROOT), spec)
    script_rows.append((spec, issues, stats))
    print('# 脚本 %-22s issues=%d stats=%s' % (spec.get('id'), len(issues),
                                           json.dumps(stats, ensure_ascii=False, sort_keys=True)))

specs = {str(s.get('id')): s for s in doc.get('script') or []}
chain_rows = []
for chain in doc.get('chains') or []:
    issues, stats = ac._check_chain(specs, chain)
    chain_rows.append((chain, issues, stats))
    print('# 链   %s→%s issues=%d stats=%s' % (chain.get('from'), chain.get('to'), len(issues),
                                            json.dumps(stats, ensure_ascii=False, sort_keys=True)))

issues, warns, stats = ac.scan(str(ROOT))
print('# 聚合 issues=%d warns=%d stats=%s' % (len(issues), len(warns),
                                          json.dumps(stats, ensure_ascii=False, sort_keys=True)))


def arr(v):
    return "&[%s]" % ", ".join(rr(x) for x in v)


def rows(items):
    out = []
    for spec, issues, stats in items:
        out.append('        (\n            %s,\n            %s,\n            %s\n        ),'
                   % (rr(json.dumps(spec, ensure_ascii=False, sort_keys=True)),
                      arr(issues),
                      rr(json.dumps(stats, ensure_ascii=False, sort_keys=True))))
    return "\n".join(out)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_asset_code_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== 代码面 / 脚本面 / 链 / 聚合（真实声明，期望值由生成器从真源取）=====
    ///
    /// 语法坏那一支的**文本不可比**（真源给 CPython `SyntaxError`，本线给本线解析器的），
    /// 故那类消息在两侧都归一到 `<TEXT>`（同 `code_metrics` 的处理）。
    #[test]
    fn asset_code_real_declarations_match_truth_source() {
        let root = ac_repo_root();
        let cases: &[(&str, &[&str], &str)] = &[
@@CODE@@
        ];
        for (spec_s, want_issues, want_stats) in cases {
            let spec: Json = crate::jsonread::convert(
                &serde_json::from_str::<serde_json::Value>(spec_s).unwrap(),
            )
            .unwrap();
            let (issues, stats) = check_code(&root, &spec);
            assert_eq!(ac_norm(&issues),
                       ac_norm(&want_issues.iter().map(|s| s.to_string()).collect::<Vec<_>>()),
                       "代码面 issues 不一致");
            let want: Json = crate::jsonread::convert(
                &serde_json::from_str::<serde_json::Value>(want_stats).unwrap(),
            )
            .unwrap();
            assert!(crate::jsonread::json_eq(&stats, &want), "代码面 stats 不一致");
        }
    }

    #[test]
    fn asset_script_real_declarations_match_truth_source() {
        let root = ac_repo_root();
        let cases: &[(&str, &[&str], &str)] = &[
@@SCRIPT@@
        ];
        for (spec_s, want_issues, want_stats) in cases {
            let spec: Json = crate::jsonread::convert(
                &serde_json::from_str::<serde_json::Value>(spec_s).unwrap(),
            )
            .unwrap();
            let (issues, stats) = check_script(&root, &spec);
            assert_eq!(issues, want_issues.to_vec(), "脚本面 issues 不一致");
            let want: Json = crate::jsonread::convert(
                &serde_json::from_str::<serde_json::Value>(want_stats).unwrap(),
            )
            .unwrap();
            assert!(crate::jsonread::json_eq(&stats, &want), "脚本面 stats 不一致");
        }
    }

    #[test]
    fn asset_chains_match_truth_source() {
        let root = ac_repo_root();
        let specs: Vec<(String, Json)> = {
            let (doc, _) = load(&root);
            match obj_get(&doc, "script") {
                Some(Json::Array(a)) => a.iter().map(|s| (sg_str(s, "id"), s.clone())).collect(),
                _ => Vec::new(),
            }
        };
        let cases: &[(&str, &[&str], &str)] = &[
@@CHAIN@@
        ];
        for (chain_s, want_issues, want_stats) in cases {
            let chain: Json = crate::jsonread::convert(
                &serde_json::from_str::<serde_json::Value>(chain_s).unwrap(),
            )
            .unwrap();
            let (issues, stats) = check_chain(&specs, &chain);
            assert_eq!(issues, want_issues.to_vec(), "链 issues 不一致");
            let want: Json = crate::jsonread::convert(
                &serde_json::from_str::<serde_json::Value>(want_stats).unwrap(),
            )
            .unwrap();
            assert!(crate::jsonread::json_eq(&stats, &want), "链 stats 不一致");
        }
    }

    #[test]
    fn asset_contract_scan_matches_truth_source() {
        let root = ac_repo_root();
        let (issues, warns, stats) = scan(&root);
        assert_eq!(ac_norm(&issues), @@SCANISSUES@@ as &[&str], "聚合 issues 不一致");
        assert_eq!(warns, @@SCANWARNS@@ as &[&str], "聚合 warns 不一致");
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@SCANSTATS@@).unwrap(),
        )
        .unwrap();
        assert!(crate::jsonread::json_eq(&stats, &want),
                "聚合 stats 不一致\n  实得 {}\n  期望 {}", stats.dumps(), want.dumps());
    }
    // <<< GENERATED
'''

text = (TEMPLATE.replace('@@CODE@@', rows(code_rows))
        .replace('@@SCRIPT@@', rows(script_rows))
        .replace('@@CHAIN@@', rows(chain_rows))
        .replace('@@SCANISSUES@@', arr(issues))
        .replace('@@SCANWARNS@@', arr(warns))
        .replace('@@SCANSTATS@@', rr(json.dumps(stats, ensure_ascii=False, sort_keys=True))))

BEGIN = '    // >>> GENERATED by tools/gen_asset_code_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'asset_contract.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
# 归一函数 + obj_get 的公开别名（供判据用）
if 'fn ac_norm' not in t:
    t = t.replace('#[cfg(test)]\nmod tests {\n    use super::*;\n',
                  '''#[cfg(test)]
mod tests {
    use super::*;

    /// 归一：解析/读件失败的文本两侧不可比，只留稳定前缀。
    fn ac_norm(issues: &[String]) -> Vec<String> {
        issues
            .iter()
            .map(|x| {
                for pat in ["不是合法 JSON：", "schema 本身不是合法 JSON：", "读不到 ",
                            " 不是 UTF-8：", "语法坏："] {
                    if let Some(i) = x.find(pat) {
                        return format!("{}<TEXT>", &x[..i + pat.len()]);
                    }
                }
                x.clone()
            })
            .collect()
    }
''', 1)
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入 asset_contract 的代码/脚本/链/聚合判据')
