"""为 `purity_scan`（R1–R7）生成**分支级**判据。

真语料上该判据是 **0 issue** ⇒ 所有错误分支都没被踩到；"逐字节一致"只在全绿路径上被证过。
本夹具逐支踩：R1 端壳（且只在前两份文档判）/ R2 私货 / R3 重复标题 / R4 raise 缺指引（含反例）
/ R5 未登记第三方（含软导入未守卫、软导入已守卫、硬白名单、标准库、本仓局部五个反例）
/ R6 三类 sink（整串命中 / 末段命中 / shell=True）+ SINK_ALLOW 放行命中 / R7 缺阶梯件。

**踩不到的分支（如实记）**：R6 自洽面（`DANGEROUS_CALLS` 缺 CWE 对齐、`SINK_ALLOW` 指向未登记
sink）由**常量表自身**驱动——夹具改不了编译期常量，故本线这两支不可达。它们在真源里同样只在
有人改表时才触发，属"表的不变量"，已由代码保留但无判据覆盖。

用法：python engine/rust/tools/gen_purity_branches.py
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import purity_scan as p  # noqa: E402

FIX = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'purity-branches'
if FIX.exists():
    shutil.rmtree(FIX)

# ① 协议文档：R1 端壳（只在前两份判）+ R2 私货 + R3 重复标题
DOC1 = """# 总纲
本节提到 android 端的旧方案（应为端壳残留）。
路径 D:\\private\\x 与 /home/someone/y 属私货；TODO 也该清。
## 同名小节
正文一
## 同名小节
正文二
"""
DOC2 = """# 联动
## 也重复
甲
## 也重复
乙
"""
# 第三份（06）**不该被端壳判据扫**——用来验"只在前两份判"这一支
DOC3 = """# 执行协议
这里出现 android 字样，但本档不在端壳判据面内。
"""

# ② core/*.py：R4（raise 缺指引 / 带指引反例）+ R5（本仓局部 import 反例）
CORE = '''import os
import yaml
from core import other_local


def f():
    if True:
        raise ValueError("坏了")            # R4：无修复指引
    if True:
        raise ValueError("请改用安全写法")   # R4 反例：带指引
    raise RuntimeError(f"应检查 {os.sep}")  # R4：JoinedStr 常量段带指引
'''

# ③ scripts/*.py：R5 六种 + R6 四类
SCRIPTS = '''import json
import sys
import jsonschema           # R5：软导入登记了但**无守卫**
try:
    import PySide6          # R5 反例：软导入 + 守卫 → 不报
except ImportError:
    PySide6 = None
import requests             # R5：未登记第三方
import nosuchlocal          # R5：未登记（也不是本仓局部）
import shutil
import subprocess


def g(p):
    os.system("ls")                      # R6：整串命中 DANGEROUS_CALLS
    p.unlink()                           # R6：末段命中 METHOD_SINKS
    subprocess.run("x", shell=True)      # R6：shell=True
    shutil.rmtree(p)                     # R6：整串命中
'''

# R6 的 SINK_ALLOW 放行支：文件名必须是放行键里的基名（storage.py:unlink）
STORAGE = '''import pathlib


def clean(p):
    p.unlink()
'''

# 让 `nosuchlocal` 不是本仓局部；`other_local` 要成为本仓局部
LOCAL = 'X = 1\n'

FILES = {
    '01_核心协议.md': DOC1,
    '02_联动注册表.md': DOC2,
    '06_Agent执行协议.md': DOC3,
    'desktop/src/core/zz_fixture.py': CORE,
    'desktop/src/core/other_local.py': LOCAL,
    'scripts/zz_fixture.py': SCRIPTS,
    'scripts/storage.py': STORAGE,
}
for rel, body in FILES.items():
    fp = FIX / rel
    fp.parent.mkdir(parents=True, exist_ok=True)
    fp.write_text(body, encoding='utf-8', newline='')

issues, stats = p.scan(str(FIX))
print('# 真源：issues=%d' % len(issues))
for x in issues:
    print('#   ! %s' % x)
print('# stats = %s' % json.dumps(stats, ensure_ascii=False, sort_keys=True))


def arr(v):
    return "&[%s]" % ", ".join(rr(x) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_purity_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_purity_branches.py` 从真源生成）=====
    ///
    /// 真语料上该判据 **0 issue** ⇒ 错误分支全未踩到。本夹具逐支踩：R1 端壳（**且只在前两份
    /// 文档判**——第三份带 android 字样但不报）/ R2 私货 / R3 重复标题 / R4 raise 缺指引（含
    /// "带指引"与"f-string 常量段"两个反例）/ R5 未登记第三方（含软导入未守卫、软导入已守卫、
    /// 硬白名单 `yaml`、标准库、本仓局部 `core.other_local` 五个反例）/ R6 三类 sink（整串命中 /
    /// 末段命中 / `shell=True`）+ `SINK_ALLOW` 放行命中（`storage.py:unlink`）/ R7 缺阶梯件。
    ///
    /// **踩不到的分支**：R6 自洽面（表缺 CWE 对齐、放行键指向未登记 sink）由**常量表本身**驱动
    /// ——夹具改不了编译期常量，故本线那两支不可达；属"表的不变量"，代码保留但无判据覆盖。
    const PURITY_DOC1: &str = @@DOC1@@;
    const PURITY_DOC2: &str = @@DOC2@@;
    const PURITY_DOC3: &str = @@DOC3@@;
    const PURITY_CORE: &str = @@CORE@@;
    const PURITY_SCRIPTS: &str = @@SCRIPTS@@;
    const PURITY_STORAGE: &str = @@STORAGE@@;

    fn build_purity_fixture() -> std::path::PathBuf {
        let root = crate::testutil::fixture("purity-branches");
        let write = |rel: &str, body: &str| {
            let p = root.join(rel);
            std::fs::create_dir_all(p.parent().unwrap()).unwrap();
            std::fs::write(p, body).unwrap();
        };
        write("01_核心协议.md", PURITY_DOC1);
        write("02_联动注册表.md", PURITY_DOC2);
        write("06_Agent执行协议.md", PURITY_DOC3);
        write("desktop/src/core/zz_fixture.py", PURITY_CORE);
        write("desktop/src/core/other_local.py", "X = 1\n");
        write("scripts/zz_fixture.py", PURITY_SCRIPTS);
        write("scripts/storage.py", PURITY_STORAGE);
        root
    }

    #[test]
    fn purity_matches_truth_source_branch_by_branch() {
        let root = build_purity_fixture();
        let (issues, stats) = scan(&root);
        assert_eq!(issues, @@ISSUES@@ as &[&str], "issues 须逐字且同序");
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@WANT@@).unwrap(),
        )
        .unwrap();
        assert!(
            crate::jsonread::json_eq(&stats, &want),
            "stats 不一致\n  实得 {}\n  期望 {}",
            stats.dumps(),
            want.dumps()
        );
    }
    // <<< GENERATED
'''

text = (TEMPLATE
        .replace('@@DOC1@@', rr(DOC1)).replace('@@DOC2@@', rr(DOC2)).replace('@@DOC3@@', rr(DOC3))
        .replace('@@CORE@@', rr(CORE)).replace('@@SCRIPTS@@', rr(SCRIPTS))
        .replace('@@STORAGE@@', rr(STORAGE))
        .replace('@@ISSUES@@', arr(issues))
        .replace('@@WANT@@', rr(json.dumps(stats, ensure_ascii=False, sort_keys=True))))

BEGIN = '    // >>> GENERATED by tools/gen_purity_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'purity.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    if '#[cfg(test)]' not in t:
        t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n}\n'
    path.write_text(t.rstrip()[:-1].rstrip() + '\n' + block + '}\n', encoding='utf-8', newline='')
    print('# 已插入标记区间')
