"""为 `concept_graph.scan` 生成差分判据（真实语料，期望值从真源取）。

用法：python engine/rust/tools/gen_concept_graph_cases.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import concept_graph as cg  # noqa: E402

issues, stats = cg.scan(str(ROOT))
print('# concept_graph: issues=%d stats=%s' % (len(issues),
                                            json.dumps(stats, ensure_ascii=False, sort_keys=True)))
for x in issues[:6]:
    print('#   ! %s' % x[:120])

# 顺带记录图资产清单（判据里另行核对枚举面）
assets = cg.graph_assets(str(ROOT))
print('# 图资产 %d 份' % len(assets))


def arr(v):
    return "&[%s]" % ", ".join(rr(x) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_concept_graph_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== 真实语料差分（期望值由生成器从真源取）=====
    ///
    /// 真语料上 **%d 份图资产全部健康**（issues=0），故判据面里那些错误分支要另做合成夹具
    /// （下一轮）；这一条钉的是**枚举面 + 通过路径 + stats 三项计数**。
    #[test]
    fn concept_graph_matches_truth_source() {
        let root = crate::testutil::repo_root();
        let (issues, stats) = scan(&root);
        assert_eq!(issues, @@ISSUES@@ as &[&str], "issues 须逐字且同序");
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@WANT@@).unwrap(),
        )
        .unwrap();
        assert!(
            crate::jsonread::json_eq(&stats, &want),
            "stats 不一致\n  实得 {}\n  期望 {}",
            stats.dumps(),
            want.dumps()
        );
    }

    /// 枚举面单独钉一条：`graph_assets` 的相对路径清单须与真源逐条同序。
    #[test]
    fn concept_graph_asset_enumeration_matches_truth_source() {
        let root = crate::testutil::repo_root();
        assert_eq!(graph_assets(&root), @@ASSETS@@ as &[&str]);
    }
    // <<< GENERATED
'''
text = (TEMPLATE % len(issues))
text = (text.replace('@@ISSUES@@', arr(issues))
        .replace('@@WANT@@', rr(json.dumps(stats, ensure_ascii=False, sort_keys=True)))
        .replace('@@ASSETS@@', arr(assets)))
BEGIN = '    // >>> GENERATED by tools/gen_concept_graph_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'concept_graph.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入 concept_graph 判据（issues %d 条 / 资产 %d 份）' % (len(issues), len(assets)))
