"""为 `doc-kinds`（`doc_hygiene.kind_coverage` + `kind_rules`）生成分支级判据。

契约 `_c_doc_kinds` **只调这两个函数**（不碰 `check_markers` / `stale`，故不涉日期）。

两件事各有价值：

1. **`kind_coverage` 忽略 `root`**——它遍历真源里**固定的** `REQUIRED_DOCS ∪ INSTRUCTION_DOCS`
   常量表。合成夹具**触发不了**它的两个分支，但它能**校验本线转录的常量表是否与真源一致**：
   我这侧若漏了任何一条（或 kind 写错），就会报出真源没有的 issue。
2. **`kind_rules` 可夹具**：给一条真实 `DOC_KINDS` 路径放"不符合该型写法"的内容 ⇒ WARN；
   另一条放合规内容 ⇒ 不 WARN；其余路径不在场 ⇒ 走"跳过"分支。

用法：python engine/rust/tools/gen_doc_kinds_branches.py
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
from core import doc_hygiene as dh  # noqa: E402
from core import conformance_report as cr  # noqa: E402

FIX = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'doc-kinds-branches'
if FIX.exists():
    shutil.rmtree(FIX)
FIX.mkdir(parents=True)

# 从真源常量表里挑两条真实路径，一条踩"写法未定型"、一条合规
HOWTO = next(rel for rel, k in sorted(dh.DOC_KINDS.items()) if k == 'how-to')
EXPL = next(rel for rel, k in sorted(dh.DOC_KINDS.items()) if k == 'explanation')
REFS = [rel for rel, k in sorted(dh.DOC_KINDS.items()) if k == 'reference'][:1]
REFS = REFS[0] if REFS else HOWTO

FILES = {
    # how-to 的要求是「可执行命令块」之一（``` / python scripts/nf.py / ⛔）——这里**都不给**
    HOWTO: "# 章节\n只有说明文字，没有命令块。\n",
    # explanation 要求出现「为什么 / 权衡 / 机制」之一——这里给足
    EXPL: "# 说明\n这里解释**机制**与取舍。\n",
}
for rel, body in FILES.items():
    p = FIX / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body, encoding='utf-8', newline='')

issues = dh.kind_coverage(str(FIX))
warns = dh.kind_rules(str(FIX))
ok, detail = cr._c_doc_kinds(str(FIX))
print('# 真源：issues=%d warns=%d ok=%s' % (len(issues), len(warns), ok))
for x in issues:
    print('#   ! %s' % x)
for x in warns:
    print('#   ~ %s' % x)
print('# detail = %r' % detail)
print('# 夹具路径：%s(how-to) / %s(explanation)' % (HOWTO, EXPL))


from _rustlit import raw as rr, rs  # noqa: E402  —— 键走 rs()（Rust 普通字面量）、内容走 raw()（原始字符串）


def arr(v):
    return "&[%s]" % ", ".join(json.dumps(x, ensure_ascii=False) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_doc_kinds_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_doc_kinds_branches.py` 从真源生成）=====
    ///
    /// `_c_doc_kinds` 只调 `kind_coverage` + `kind_rules`（不涉日期）。
    /// 本判据钉两件事：
    /// ① **常量表一致性**：`kind_coverage` 忽略 `root`、只用真源里固定的 `REQUIRED_DOCS ∪
    ///    INSTRUCTION_DOCS` ——本线若漏转录某条，就会报出真源没有的 issue（合成夹具**触发不了**
    ///    它的分支，故只能这样核）；
    /// ② **`kind_rules` 的两个分支**：路径在场但写法不符该型 ⇒ WARN；在场且合规 ⇒ 不 WARN；
    ///    其余路径不在场 ⇒ 走「跳过」分支。
    const DK_FILES: [(&str, &str); @@NF@@] = [
@@FILES@@
    ];

    fn build_doc_kinds_fixture() -> std::path::PathBuf {
        let root = crate::testutil::fixture("doc-kinds-branches");
        for (rel, body) in DK_FILES {
            let p = root.join(rel);
            std::fs::create_dir_all(p.parent().unwrap()).unwrap();
            std::fs::write(p, body).unwrap();
        }
        root
    }

    #[test]
    fn doc_kinds_matches_truth_source() {
        let root = build_doc_kinds_fixture();
        // ① 常量表一致性（真源这两个函数里，只有 kind_coverage 与 root 无关）
        assert_eq!(crate::doc_hygiene::kind_coverage(), @@ISSUES@@ as &[&str], "四型覆盖（常量表一致性）");
        // ② kind_rules 的两个分支
        assert_eq!(crate::doc_hygiene::kind_rules(&root), @@WARNS@@ as &[&str], "写法 WARN 须逐字且同序");
        // ③ 契约层 detail
        let (ok, detail) = doc_kinds(&root);
        assert_eq!(ok, @@OK@@);
        assert_eq!(detail, @@DETAIL@@);
    }
    // <<< GENERATED
'''

text = (TEMPLATE
        .replace('@@NF@@', str(len(FILES)))
        .replace('@@FILES@@', "\n".join('        (%s, %s),' % (rs(k), rr(v))
                                       for k, v in sorted(FILES.items())))
        .replace('@@ISSUES@@', arr(issues))
        .replace('@@WARNS@@', arr(warns))
        .replace('@@OK@@', 'true' if ok else 'false')
        .replace('@@DETAIL@@', json.dumps(detail, ensure_ascii=False)))

BEGIN = '    // >>> GENERATED by tools/gen_doc_kinds_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'contracts.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    idx = t.rstrip().rfind('\n}')
    path.write_text(t[:idx] + '\n' + block + t[idx:], encoding='utf-8', newline='')
    print('# 已插入标记区间')
