"""为 `domain_metrics` 生成差分判据：真语料 **100 个 T4 域报告条目**的真实输入。

口径：对每条 `tier == T4` 且生成器为 `domain-report` 的条目，按真源 `_gen_domain_report` 的路径
取样例 CSV → `load_rows` → `evaluate(family, rows, **params)`，把整份报告与真源比对。

用法：python engine/rust/tools/gen_domain_metrics_cases.py
"""
import glob
import json
import pathlib
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import domain_metrics as dm  # noqa: E402
from core import output_forms as of  # noqa: E402

rows = []
for f in sorted(glob.glob('community/*/outputs/INDEX.json')):
    pkg = pathlib.Path(f).parts[1]
    try:
        idx = json.load(open(f, encoding='utf-8'))
    except Exception:
        continue
    for e in idx.get('outputs') or []:
        if e.get('tier') != 'T4':
            continue
        if of._gen_id(e) != 'domain-report':
            continue
        spec = e.get('recompute') or e.get('render') or {}
        inputs = spec.get('inputs') or []
        params = dict(spec.get('params') or {})
        family = str(params.get('family') or '')
        if not inputs or not family:
            rows.append((pkg, e.get('path'), family, params, None, '域报告缺 inputs 或 family'))
            continue
        src = of._pkg_rel({**e, '_pkg': pkg}, inputs[0])
        loaded, err = dm.load_rows(ROOT / src)
        if err:
            rows.append((pkg, e.get('path'), family, params, None, '输入 %s %s' % (src, err)))
            continue
        kw = {k: v for k, v in params.items() if k not in ('family',)}
        got = dm.evaluate(family, loaded, **kw)
        rows.append((pkg, e.get('path'), family, params, got, ''))

print('# domain-report 条目 %d 条（成功 %d / 报错 %d）'
      % (len(rows), sum(1 for r in rows if r[5] == ''), sum(1 for r in rows if r[5])))
fams = {}
for r in rows:
    fams[r[2]] = fams.get(r[2], 0) + 1
print('# 族分布:', fams)

def src_of(pkg, path):
    """重算该条目所需样例件的仓库相对路径（与 `_gen_domain_report` 的 `_pkg_rel` 同源）。"""
    for f in glob.glob('community/*/outputs/INDEX.json'):
        if pathlib.Path(f).parts[1] != pkg:
            continue
        try:
            idx = json.load(open(f, encoding='utf-8'))
        except Exception:
            return ''
        for e in idx.get('outputs') or []:
            if e.get('path') != path:
                continue
            spec = e.get('recompute') or e.get('render') or {}
            inputs = spec.get('inputs') or []
            if inputs:
                return 'community/%s/%s' % (pkg, str(inputs[0]).lstrip('/'))
    return ''


entries = []
for pkg, path, family, params, got, err in rows:
    entries.append(
        '        (\n            %s,\n            %s,\n            %s,\n            %s,\n            %s\n        ),'
        % (rr(pkg), rr(family), rr(src_of(pkg, path)),
           rr(json.dumps(params, ensure_ascii=False, sort_keys=True)),
           rr(json.dumps(got, ensure_ascii=False, sort_keys=True) if got is not None else '')))

TEMPLATE = r'''
    // >>> GENERATED by tools/gen_domain_metrics_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== 真语料 T4 域报告条目：`load_rows` + `evaluate` **全字段比对** =====
    ///
    /// 每条按真源 `_gen_domain_report` 的路径取样例 CSV（`community/<pkg>/<inputs[0]>`）→
    /// `load_rows` → `evaluate(family, rows, **params)`，与真源算出的整份报告逐字段比对。
    /// 这是 T4 复算的**真路径**（覆盖真语料实际用到的度量族）。
    #[test]
    fn domain_metrics_matches_truth_source_over_corpus() {
        let root = crate::testutil::repo_root();
        let cases: &[(&str, &str, &str, &str, &str)] = &[
@@CASES@@
        ];
        let mut ok = 0usize;
        let mut skipped = 0usize;
        for (pkg, family, src, params_s, want_s) in cases {
            if src.is_empty() || want_s.is_empty() {
                skipped += 1;
                continue;
            }
            let spec: Json = crate::jsonread::convert(
                &serde_json::from_str::<serde_json::Value>(params_s).unwrap(),
            )
            .unwrap();
            let params: Vec<(String, Json)> = match spec {
                Json::Object(o) => o,
                _ => Vec::new(),
            };
            let loaded = load_rows(&root.join(src))
                .unwrap_or_else(|e| panic!("{} 读样例 {} 失败：{}", pkg, src, e));
            let got = evaluate(family, &loaded, &params)
                .unwrap_or_else(|e| panic!("{} ({}) evaluate 失败：{}", pkg, family, e));
            let want: Json = crate::jsonread::convert(
                &serde_json::from_str::<serde_json::Value>(want_s).unwrap(),
            )
            .unwrap();
            assert!(
                crate::jsonread::json_eq(&got, &want),
                "{} ({}) 报告不一致\n  实得 {}\n  期望 {}",
                pkg,
                family,
                got.dumps_default(),
                want.dumps_default()
            );
            ok += 1;
        }
        assert!(ok > 0, "至少要真跑若干条，否则判据是空转");
        eprintln!("domain_metrics 对账：{} 条通过 / {} 条跳过（缺 inputs）", ok, skipped);
    }
    // <<< GENERATED
'''
text = TEMPLATE.replace('@@CASES@@', "\n".join(entries))
BEGIN = '    // >>> GENERATED by tools/gen_domain_metrics_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'domain_metrics.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入 domain_metrics 判据（%d 条）' % len(rows))
