"""为 `output_forms.scan` 生成差分判据（形态清单 + 包级产出面 + 机验率基线三合一）。

用法：python engine/rust/tools/gen_output_forms_scan_cases.py
"""
import json
import pathlib
import sys
import time

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import output_forms as of  # noqa: E402

t0 = time.time()
issues, stats = of.scan(str(ROOT))
print('# output_forms.scan: issues=%d 用时 %.1fs' % (len(issues), time.time() - t0))
print('# registry=%s' % json.dumps(stats.get('registry'), ensure_ascii=False, sort_keys=True)[:150])
print('# index=%s' % json.dumps(stats.get('index'), ensure_ascii=False, sort_keys=True)[:220])
print('# meter 包数=%d totals=%s'
      % (len(stats.get('meter') or {}), json.dumps(
          {k: v for k, v in (stats.get('meter') or {}).items() if k == ''} or
          {'(逐包见下)': len(stats.get('meter') or {})}, ensure_ascii=False)))
for x in issues[:6]:
    print('#   ! %s' % x[:118])

# 逐包 meter 也单独出一条（比整份 stats 更易定位）
meter_issues, meter_stats = of.meter(str(ROOT))
print('# meter: issues=%d totals=%s' % (len(meter_issues),
                                        json.dumps(meter_stats['totals'], ensure_ascii=False)))
base_issues, base_stats = of.baseline_verify(str(ROOT))
print('# baseline_verify: issues=%d baseline=%s' % (len(base_issues), base_stats.get('baseline')))


def arr(v):
    return "&[%s]" % ", ".join(rr(str(x)) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_output_forms_scan_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== 真语料 `scan`：形态清单 + **包级产出面 1156 件逐条校验** + 机验率基线 =====
    #[test]
    fn output_forms_scan_matches_truth_source() {
        let root = crate::testutil::repo_root();
        let (issues, stats) = scan(&root);
        assert_eq!(issues, @@ISSUES@@ as &[&str], "issues 须逐字且同序");
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@WANT@@).unwrap(),
        )
        .unwrap();
        assert!(crate::jsonread::json_eq(&stats, &want),
                "stats 不一致\n  实得 {}\n  期望 {}", stats.dumps_default(), want.dumps_default());
    }

    /// 机验率计量逐包比对（`scan` 的 stats 里也含它，这里单独钉一条便于定位）。
    #[test]
    fn meter_matches_truth_source_over_corpus() {
        let root = crate::testutil::repo_root();
        let (issues, stats) = meter(&root);
        assert_eq!(issues, @@MISSUES@@ as &[&str]);
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@MWANT@@).unwrap(),
        )
        .unwrap();
        assert!(crate::jsonread::json_eq(&stats, &want), "meter stats 不一致");
    }

    /// 基线比对（可重签工件）：低于基线即 FAIL。
    #[test]
    fn baseline_verify_matches_truth_source() {
        let root = crate::testutil::repo_root();
        let (issues, stats) = baseline_verify(&root);
        assert_eq!(issues, @@BISSUES@@ as &[&str]);
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@BWANT@@).unwrap(),
        )
        .unwrap();
        assert!(crate::jsonread::json_eq(&stats, &want), "baseline stats 不一致");
    }
    // <<< GENERATED
'''
text = (TEMPLATE.replace('@@ISSUES@@', arr(issues))
        .replace('@@WANT@@', rr(json.dumps(stats, ensure_ascii=False, sort_keys=True)))
        .replace('@@MISSUES@@', arr(meter_issues))
        .replace('@@MWANT@@', rr(json.dumps(meter_stats, ensure_ascii=False, sort_keys=True)))
        .replace('@@BISSUES@@', arr(base_issues))
        .replace('@@BWANT@@', rr(json.dumps(base_stats, ensure_ascii=False, sort_keys=True))))
BEGIN = '    // >>> GENERATED by tools/gen_output_forms_scan_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'output_forms_verify.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入 output_forms.scan 判据（issues %d 条）' % len(issues))
