"""把 `pack_combo` 的两个**数据常量**转录进 `src/output_tables.rs`。

- `CERT_SCHEMA`：组合证书的 JSON Schema（1,868 字符，**数据**，手抄必错 ⇒ 转录）；
- `CORE13`：官方核心 13 件模块号（`_core_ids()` 的基）。

用法：python engine/rust/tools/gen_pack_combo_tables.py
"""
import json
import pathlib
import sys

sys.path.insert(0, 'engine/rust/tools')
sys.path.insert(0, 'desktop/src')
from _rustlit import raw as rr, rs  # noqa: E402
from core import pack_combo as pc  # noqa: E402

ROOT = pathlib.Path('.').resolve()
P = ROOT / 'engine/rust/src/output_tables.rs'
t = P.read_text(encoding='utf-8')

schema_json = json.dumps(pc.CERT_SCHEMA, ensure_ascii=False, sort_keys=True)
block = '\n'.join([
    '',
    '// >>> GENERATED by tools/gen_pack_combo_tables.py（勿手改；重跑生成器覆盖本段）',
    '/// 真源 `pack_combo.CERT_REL`。',
    'pub const CERT_REL: &str = %s;' % rs(pc.CERT_REL),
    '',
    '/// 真源 `pack_combo.CORE13`（`_core_ids()` 的基）。',
    '#[rustfmt::skip]',
    'pub const CORE13: [&str; %d] = [' % len(pc.CORE13),
    *['    %s,' % rs(x) for x in pc.CORE13],
    '];',
    '',
    '/// 真源 `pack_combo.CERT_SCHEMA`（**数据**，按规范 JSON 转录；用时解析）。',
    'pub const CERT_SCHEMA_JSON: &str = %s;' % rr(schema_json),
    '// <<< GENERATED',
    '',
])

BEGIN = '// >>> GENERATED by tools/gen_pack_combo_tables.py'
END = '// <<< GENERATED'
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    out = t[:a] + block.lstrip('\n') + t[b:].lstrip('\n')
else:
    out = t.rstrip() + '\n' + block
P.write_text(out, encoding='utf-8', newline='')
print('已转录 CERT_REL / CORE13(%d) / CERT_SCHEMA(%d 字符)'
      % (len(pc.CORE13), len(schema_json)))
