"""为 `xmlmini` 生成差分判据：真语料 GraphML/SVG 上比对真源 `ElementTree` 的四个查询。

`output_forms._check_graphml` / `_check_xml` 只需要四件事（见 `xmlmini.rs` 文档）：根元素局部名、
后代 `graph` 数、`node` 的 id 集、`edge` 端点是否悬空。本生成器把这四件事从真源算出来落成判据
——**先钉住解析器的用到那一层**，再往上写校验器。

用法：python engine/rust/tools/gen_xmlmini_cases.py
"""
import glob
import json
import pathlib
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402

files = sorted(
    p.relative_to(ROOT).as_posix()
    for pat in ('community/*/outputs/**/*.graphml', 'community/*/outputs/**/*.svg')
    for p in ROOT.glob(pat)
)
rows = []
for rel in files:
    text = (ROOT / rel).read_text(encoding='utf-8')
    try:
        r = ET.fromstring(text)
    except ET.ParseError as exc:
        rows.append((rel, None, str(exc), 0, [], 0))
        continue
    tag = r.tag.split('}')[-1]
    graphs = r.findall('.//{*}graph')
    nodes = sorted({n.get('id') for g in graphs for n in g.findall('{*}node')})
    dangling = 0
    for g in graphs:
        for e in g.findall('{*}edge'):
            for end in ('source', 'target'):
                if e.get(end) not in set(nodes):
                    dangling += 1
    rows.append((rel, tag, '', len(graphs), nodes, dangling))

print('# 文件 %d 份（解析成功 %d）' % (len(files), sum(1 for r in rows if r[1] is not None)))
print('# 例：%s → 根=%s 图=%d 节点=%d 悬空=%d'
      % (rows[0][0], rows[0][1], rows[0][3], len(rows[0][4]), rows[0][5]))


def arr(v):
    return "&[%s]" % ", ".join(rr(str(x)) for x in v)


entries = []
for rel, tag, err, ngraphs, nodes, dangling in rows:
    entries.append(
        '        (%s, %s, %d, %s, %d),'
        % (rr(rel), rr(tag or ''), ngraphs, arr(nodes), dangling))

TEMPLATE = r'''
    // >>> GENERATED by tools/gen_xmlmini_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== 真语料 GraphML/SVG 上的四查询差分（期望值从真源 `ElementTree` 取）=====
    ///
    /// 钉住 `xmlmini` 的**用到那一层**：根元素局部名 / 后代 `graph` 数 / `node` id 集 / `edge`
    /// 端点悬空数。**解析失败的文本不可比**（CPython 的 ParseError vs 本线），故只比"是否解析成功"。
    #[test]
    fn xmlmini_matches_elementtree_query_layer() {
        let root = crate::testutil::repo_root();
        let cases: &[(&str, &str, usize, &[&str], usize)] = &[
@@CASES@@
        ];
        let mut parsed_ok = 0;
        for (rel, want_tag, want_graphs, want_nodes, want_dangling) in cases {
            let text = std::fs::read_to_string(root.join(rel)).unwrap();
            match parse(&text) {
                Err(_) => {
                    // 真源那条也只记"解析失败"（文本不可比）
                    assert!(want_graphs == &0 && want_nodes.is_empty() && want_tag.is_empty(),
                            "{} 本线解析失败但真源成功", rel);
                }
                Ok(node) => {
                    parsed_ok += 1;
                    assert_eq!(node.local(), *want_tag, "{} 根元素局部名", rel);
                    let graphs = node.descendants("graph");
                    assert_eq!(graphs.len(), *want_graphs, "{} 后代 graph 数", rel);
                    let mut ids: Vec<String> = Vec::new();
                    for g in &graphs {
                        for n in g.children_named("node") {
                            if let Some(id) = n.attr("id") {
                                ids.push(id.to_string());
                            }
                        }
                    }
                    ids.sort();
                    ids.dedup();
                    assert_eq!(ids, want_nodes.iter().map(|s| s.to_string()).collect::<Vec<_>>(),
                               "{} node id 集", rel);
                    let idset: std::collections::BTreeSet<String> = ids.clone().into_iter().collect();
                    let mut dangling = 0usize;
                    for g in &graphs {
                        for e in g.children_named("edge") {
                            for end in ["source", "target"] {
                                if !e.attr(end).map(|v| idset.contains(v)).unwrap_or(false) {
                                    dangling += 1;
                                }
                            }
                        }
                    }
                    assert_eq!(dangling, *want_dangling, "{} edge 悬空数", rel);
                }
            }
        }
        assert!(parsed_ok > 0, "至少要成功解析若干件，否则判据是空转");
    }
    // <<< GENERATED
'''
text = TEMPLATE.replace('@@CASES@@', "\n".join(entries))
BEGIN = '    // >>> GENERATED by tools/gen_xmlmini_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'xmlmini.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入 xmlmini 判据（%d 份文件）' % len(rows))
