"""为 `public_surface.scan` 生成分支级判据。

契约在真语料上**全绿**（公开导出面零泄漏）⇒ 对账核不到任何错误分支；
而它的判据依赖一个**含后顾断言**的正则（`(?<![A-Za-z0-9])`，Rust `regex` 不支持，
本线走 `fancy-regex`）——四个分支变体都该被钉住。

用法：python engine/rust/tools/gen_public_surface_branches.py
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
from _rustlit import rs  # noqa: E402  —— Rust 普通字符串字面量（键等）
from core import conformance_report as cr  # noqa: E402
# ⚠️ `public-surface` 在真源里**没有独立模块**：`_c_public_surface` 内联在 `conformance_report.py`
# （我移植时已记过这点）。故这里直接调契约包装，比对的是 `(ok, detail)`。

FIX = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'public-surface-branches'
if FIX.exists():
    shutil.rmtree(FIX)

# 覆盖面：EXPORT_GLOBS = desktop/tests/fixtures/external/**/* + docs/external-validation-assets/*
FILES = {
    # 驱动器号 + 反斜杠 Users
    'docs/external-validation-assets/drive.md': "# x\n见 C:\\Users\\bob\\nf\n",
    # /Users/
    'docs/external-validation-assets/mac.json': '{"p": "/Users/bob/nf"}\n',
    # /home/x
    'docs/external-validation-assets/lin.yaml': "p: /home/bob/nf\n",
    # 干净的（不该被报）
    'docs/external-validation-assets/clean.txt': "没有绝对路径\n",
    # 后缀不在白名单 → 跳过（哪怕含绝对路径）
    'docs/external-validation-assets/skip.png': "C:\\Users\\bob\n",
    # 第二条 glob（`**`）也要踩
    'desktop/tests/fixtures/external/sub/deep.md': "D:/x\n",
    # 前一个字符是字母数字 ⇒ **不该**命中 `(?<![A-Za-z0-9])`（后顾断言的分界）
    'desktop/tests/fixtures/external/sub/adjacent.md': "abcC:/x\n",
}

for rel, body in FILES.items():
    p = FIX / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body, encoding='utf-8', newline='')

ok, detail = cr._c_public_surface(str(FIX))
print('# 真源：ok=%s' % ok)
print('# detail = %r' % detail)


def rj(s):
    assert '"#' not in s
    return 'r#"%s"#' % s


def arr(v):
    return "&[%s]" % ", ".join(json.dumps(x, ensure_ascii=False) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_public_surface_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_public_surface_branches.py` 从真源生成）=====
    ///
    /// 契约在真语料上**全绿** ⇒ 对账核不到错误分支。而它的判据依赖一个**含后顾断言**的正则
    /// （`(?<![A-Za-z0-9])`——Rust `regex` 不支持、本线走 `fancy-regex`），故四个变体都该被钉住：
    /// 驱动器号 + `\Users\` / `/Users/` / `/home/x`；另加「后缀不在白名单 ⇒ 跳过」与
    /// 「前一个字符是字母数字 ⇒ 后顾断言不命中」两个边界。
    const PS_FILES: [(&str, &str); @@NF@@] = [
@@FILES@@
    ];

    fn build_ps_fixture() -> std::path::PathBuf {
        let root = crate::testutil::fixture("public-surface-branches");
        for (rel, body) in PS_FILES {
            let p = root.join(rel);
            std::fs::create_dir_all(p.parent().unwrap()).unwrap();
            std::fs::write(p, body).unwrap();
        }
        root
    }

    #[test]
    fn contract_matches_truth_source_branch_by_branch() {
        let root = build_ps_fixture();
        let (ok, detail) = contract(&root);
        assert_eq!(ok, @@OK@@, "ok 须与真源一致");
        assert_eq!(detail, @@DETAIL@@, "detail 字面须与真源一致");
        // 真源 `_c_public_surface` **只暴露 `(ok, detail)`**，而 detail 是 `"; ".join(bad[:2])`
        // ——**它把清单截断到前两条**，总条数根本不在外露面上。
        // 故这里只断言真源确实暴露的东西：ok、detail 字面、以及本线 issues 的**前两条**与之相同。
        // **不发明期望值**（这是本线对"期望值只能来自真源"的具体执行）。
        let (issues, _d) = scan(&root);
        assert!(issues.len() >= @@N@@, "至少应命中 detail 里那两条");
        for (i, want) in @@HEAD@@.iter().enumerate() {
            assert_eq!(&issues[i], want, "第 {} 条", i + 1);
        }
    }
    // <<< GENERATED
'''

text = (TEMPLATE
        .replace('@@NF@@', str(len(FILES)))
        .replace('@@FILES@@', "\n".join('        (%s, %s),' % (rs(k), rj(v))
                                       for k, v in sorted(FILES.items())))
        .replace('@@OK@@', 'true' if ok else 'false')
        .replace('@@N@@', str(detail.count('; ') + 1 if not ok else 0))
        .replace('@@HEAD@@', '[%s]' % ', '.join(json.dumps(x, ensure_ascii=False) for x in (detail.split('; ') if not ok else [])))
        .replace('@@DETAIL@@', json.dumps(detail, ensure_ascii=False)))

BEGIN = '    // >>> GENERATED by tools/gen_public_surface_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]
path = ROOT / 'engine' / 'rust' / 'src' / 'public_surface.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    path.write_text(t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n'
                    + block + '}\n', encoding='utf-8', newline='')
    print('# 已追加标记区间')
