"""为 `state_front.scan` 生成分支级判据（真源 8 个 issue 分支 + 空声明 warn）。

用法：python engine/rust/tools/gen_state_front_branches.py
"""
import json
from _rustlit import rs  # noqa: E402
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
from core import state_front as sf  # noqa: E402

BASE = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'state-front-branches'
if BASE.exists():
    shutil.rmtree(BASE)

# `check_order` 期望「条件先行」：条件段在前、正文段在后。这里用两种版式各踩一支。
GOOD_DOC = "# 标题\n\n> 适用条件：X 成立时。\n\n## 正文\n内容\n"
BAD_DOC = "## 正文\n内容\n"          # 无适用条件 → check_order 报红

DOCS = {
    'docs/fam/a.md': GOOD_DOC,
    'docs/fam/b.md': BAD_DOC,
    'docs/one.md': BAD_DOC,
    'docs/two.md': GOOD_DOC,
}
DECL = {
    "schema": "wrong/1",                       # schema 不匹配
    "declared": [
        {"path": ""},                          # 缺 path
        {"path": "docs/nope.md"},              # 登记件不存在
        {"path": "docs/one.md"},               # 存在但未过 check_order
        {"path": "docs/two.md"},               # 全绿
    ],
    "family_rules": [
        {"glob": ""},                          # 缺 glob
        {"glob": "docs/fam/*.md", "min_members": 5},   # 成员不足
        {"glob": "docs/fam/*.md"},                     # 成员达标（族内件逐个 check_order）
        {"glob": "docs/none/*.md", "min_members": 1},  # 零成员 → 不足
    ],
}

SCENARIOS = {}
for name, decl, docs in (
    ('kitchen', DECL, DOCS),
    ('nodecl', None, DOCS),
    ('empty', {"schema": "nf-state-front/1", "declared": [], "family_rules": []}, {}),
):
    fix = BASE / name
    (fix / 'protocol').mkdir(parents=True)
    if decl is not None:
        (fix / 'protocol' / 'state_front.json').write_text(
            json.dumps(decl, ensure_ascii=False), encoding='utf-8', newline='')
    for rel, body in docs.items():
        (fix / rel).parent.mkdir(parents=True, exist_ok=True)
        (fix / rel).write_text(body, encoding='utf-8', newline='')
    issues, warns, stats = sf.scan(str(fix))
    SCENARIOS[name] = (issues, warns, stats)
    print('# 场景 %s：issues=%d warns=%d' % (name, len(issues), len(warns)))
    for x in issues:
        print('#   ! %s' % x)
    for x in warns:
        print('#   ~ %s' % x)
    print('# stats = %s' % json.dumps(stats, ensure_ascii=False, sort_keys=True))


def rj(s):
    assert '"#' not in s
    return 'r#"%s"#' % s


def arr(v):
    return "&[%s]" % ", ".join(json.dumps(x, ensure_ascii=False) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_state_front_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_state_front_branches.py` 从真源生成）=====
    ///
    /// 三场景：kitchen（逐分支踩）/ 缺声明 / 空声明（门禁空转 warn）。
    /// 分支：schema / 族规则缺 glob / 族成员不足 / 族内件未过 condition-first /
    /// 声明条目缺 path / 登记件不存在 / 登记件未过 condition-first / 全绿。
    /// 注：真源 `scan` 的 warns 在本面无消费者（契约只看 issues），故本线未纳入移植面。
    const SF_GOOD: &str = @@GOOD@@;
    const SF_BAD: &str = @@BAD@@;

    fn build_sf_fixture(scenario: &str, decl: Option<&str>) -> std::path::PathBuf {
        let root = crate::testutil::fixture(&format!("state-front-branches-{}", scenario));
        std::fs::create_dir_all(root.join("protocol")).unwrap();
        if let Some(d) = decl {
            std::fs::write(root.join("protocol/state_front.json"), d).unwrap();
        }
        if scenario != "empty" {
            for (rel, body) in [
                ("docs/fam/a.md", SF_GOOD),
                ("docs/fam/b.md", SF_BAD),
                ("docs/one.md", SF_BAD),
                ("docs/two.md", SF_GOOD),
            ] {
                let p = root.join(rel);
                std::fs::create_dir_all(p.parent().unwrap()).unwrap();
                std::fs::write(p, body).unwrap();
            }
        }
        root
    }

    #[test]
    fn the_contract_matches_the_truth_source_branch_by_branch() {
        for (scenario, decl, want) in [
            ("kitchen", Some(@@D1@@), @@I1@@ as &[&str]),
            ("nodecl", None, @@I2@@ as &[&str]),
            ("empty", Some(@@D3@@), @@I3@@ as &[&str]),
        ] {
            let root = build_sf_fixture(scenario, decl);
            let (issues, _stats) = state_front_scan(&root);
            assert_eq!(issues, want, "场景 {} 的 issues", scenario);
        }
    }
    // <<< GENERATED
'''

sc = SCENARIOS
text = (TEMPLATE
        .replace('@@GOOD@@', rj(GOOD_DOC)).replace('@@BAD@@', rj(BAD_DOC))
        .replace('@@D1@@', rj(json.dumps(DECL, ensure_ascii=False)))
        .replace('@@D3@@', rj(json.dumps({"schema": "nf-state-front/1", "declared": [],
                                          "family_rules": []}, ensure_ascii=False)))
        .replace('@@I1@@', arr(sc['kitchen'][0]))
        .replace('@@I2@@', arr(sc['nodecl'][0]))
        .replace('@@I3@@', arr(sc['empty'][0])))

BEGIN = '    // >>> GENERATED by tools/gen_state_front_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]
path = ROOT / 'engine' / 'rust' / 'src' / 'contracts.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    # contracts.rs 有 tests 模块：插到它收尾之前
    idx = t.rstrip().rfind('\n}')
    path.write_text(t[:idx] + '\n#[cfg(test)]\nmod state_front_tests {\n    use super::*;\n'
                    + block + '}\n' + t[idx:], encoding='utf-8', newline='')
    print('# 已插入标记区间（新 tests 模块）')
