"""为 `mcp_package.scan` 生成分支级判据（真源 10 个分支）。

用法：python engine/rust/tools/gen_mcp_package_branches.py
"""
import json
from _rustlit import rs  # noqa: E402
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
from core import mcp_package as mp  # noqa: E402
from core.mcp_runtime import PROMPT_DEFS, TOOL_DEFS  # noqa: E402

BASE = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'mcp-package-branches'
if BASE.exists():
    shutil.rmtree(BASE)

TOOLS = sorted(t['name'] for t in TOOL_DEFS)
PROMPTS = sorted(p['name'] for p in PROMPT_DEFS)

KITCHEN = {
    "schema": "wrong/1",                                   # schema 不匹配
    "category_vocabulary": ["nope"],                       # 类目词表不一致
    "red_lines": [],                                       # 红线为空
    "status": "draft",
    "pending": [],                                         # draft 但 pending 空
    "package": {
        "name_candidates": [],                             # 缺命名候选
        "one_liner_candidates": [],                        # 缺一句话候选
        "category": "bogus",                               # 类目越词表
        "tools": ["not_a_tool"],                           # 工具面不一致
        "prompts": [],                                     # 提示面不一致（少）
        "targets": ["a"],
    },
}
GREEN = {
    "schema": "nf-mcp-package/1",
    "category_vocabulary": ["content-creation", "developer-tools", "knowledge-management"],
    "red_lines": ["只读面不变"],
    "status": "published",
    "package": {
        "name_candidates": ["NF 内容质检"],
        "one_liner_candidates": ["一句话"],
        "category": "content-creation",
        "tools": TOOLS,
        "prompts": PROMPTS,
        "targets": ["a", "b", "c", "d"],
    },
}
DRAFT = dict(GREEN, status="draft", pending=["还差上架材料"])

SCENARIOS = {}
for name, decl in (('kitchen', KITCHEN), ('green', GREEN), ('draft', DRAFT), ('nodecl', None)):
    fix = BASE / name
    (fix / 'protocol').mkdir(parents=True)
    if decl is not None:
        (fix / 'protocol' / 'mcp_package.json').write_text(
            json.dumps(decl, ensure_ascii=False), encoding='utf-8', newline='')
    issues, warns, stats = mp.scan(str(fix))
    SCENARIOS[name] = (issues, warns, stats)
    print('# 场景 %s：issues=%d warns=%d' % (name, len(issues), len(warns)))
    for x in issues:
        print('#   ! %s' % x)
    for x in warns:
        print('#   ~ %s' % x)
    print('# stats = %s' % json.dumps(stats, ensure_ascii=False, sort_keys=True))


def rj(s):
    assert '"#' not in s
    return 'r#"%s"#' % s


def arr(v):
    return "&[%s]" % ", ".join(json.dumps(x, ensure_ascii=False) for x in v)


def stats_rust(s):
    parts = []
    for k in sorted(s):
        v = s[k]
        if isinstance(v, str):
            parts.append('("{}".to_string(), crate::pyjson::Json::Str({}.to_string()))'
                         .format(k, json.dumps(v, ensure_ascii=False)))
        else:
            parts.append('("{}".to_string(), crate::pyjson::Json::Int({}))'.format(k, v))
    if not parts:
        return 'crate::pyjson::Json::Object(Vec::new())'
    return 'crate::pyjson::Json::Object(vec![%s])' % ', '.join(parts)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_mcp_package_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_mcp_package_branches.py` 从真源生成）=====
    ///
    /// 四场景：kitchen（逐分支）/ 全绿 / 草案（pending 非空 ⇒ warn，不判死）/ 缺声明。
    /// 分支：schema / 类目词表 / 红线为空 / draft 但 pending 空 / 缺命名候选 / 缺一句话候选 /
    /// 类目越词表 / **工具面与运行时不一致** / **提示面与运行时不一致** / 缺声明。
    /// 注：真源 `scan` 的 warns（草案待补）契约不看，故本线结构体未纳入；`want_warns` 仅作记录。
    const MCP_KITCHEN: &str = @@KITCHEN@@;
    const MCP_GREEN: &str = @@GREEN@@;
    const MCP_DRAFT: &str = @@DRAFT@@;

    fn build_mcp_fixture(scenario: &str, decl: Option<&str>) -> std::path::PathBuf {
        let root = crate::testutil::fixture(&format!("mcp-package-branches-{}", scenario));
        std::fs::create_dir_all(root.join("protocol")).unwrap();
        if let Some(d) = decl {
            std::fs::write(root.join("protocol/mcp_package.json"), d).unwrap();
        }
        root
    }

    #[test]
    fn scan_matches_truth_source_in_all_four_scenarios() {
        for (scenario, decl, want_issues, want_warns, want_stats) in [
            ("kitchen", Some(MCP_KITCHEN), @@I1@@ as &[&str], @@W1@@ as &[&str], @@S1@@),
            ("green", Some(MCP_GREEN), @@I2@@ as &[&str], @@W2@@ as &[&str], @@S2@@),
            ("draft", Some(MCP_DRAFT), @@I3@@ as &[&str], @@W3@@ as &[&str], @@S3@@),
            ("nodecl", None, @@I4@@ as &[&str], @@W4@@ as &[&str], @@S4@@),
        ] {
            let root = build_mcp_fixture(scenario, decl);
            let got = scan(&root);
            assert_eq!(got.issues, want_issues, "场景 {} 的 issues", scenario);
            let _ = want_warns;   // 真源 warns 在本面无消费者，未纳入移植面
            assert!(
                crate::jsonread::json_eq(&got.stats, &want_stats),
                "场景 {} 的 stats：实得 {:?}",
                scenario,
                got.stats
            );
        }
    }
    // <<< GENERATED
'''

sc = SCENARIOS
text = (TEMPLATE
        .replace('@@KITCHEN@@', rj(json.dumps(KITCHEN, ensure_ascii=False)))
        .replace('@@GREEN@@', rj(json.dumps(GREEN, ensure_ascii=False)))
        .replace('@@DRAFT@@', rj(json.dumps(DRAFT, ensure_ascii=False)))
        .replace('@@I1@@', arr(sc['kitchen'][0])).replace('@@W1@@', arr(sc['kitchen'][1]))
        .replace('@@I2@@', arr(sc['green'][0])).replace('@@W2@@', arr(sc['green'][1]))
        .replace('@@I3@@', arr(sc['draft'][0])).replace('@@W3@@', arr(sc['draft'][1]))
        .replace('@@I4@@', arr(sc['nodecl'][0])).replace('@@W4@@', arr(sc['nodecl'][1]))
        .replace('@@S1@@', stats_rust(sc['kitchen'][2]))
        .replace('@@S2@@', stats_rust(sc['green'][2]))
        .replace('@@S3@@', stats_rust(sc['draft'][2]))
        .replace('@@S4@@', stats_rust(sc['nodecl'][2])))

BEGIN = '    // >>> GENERATED by tools/gen_mcp_package_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]
path = ROOT / 'engine' / 'rust' / 'src' / 'mcp_package.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    path.write_text(t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n'
                    + block + '}\n', encoding='utf-8', newline='')
    print('# 已追加标记区间')
