"""为 `output_forms` 块 A 生成差分判据：`registry_verify` / `detect` / `_check_xml` / `_check_graphml`。

用法：python engine/rust/tools/gen_output_forms_cases.py
"""
import glob
import json
import pathlib
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import output_forms as of  # noqa: E402

reg_issues, reg_stats = of.registry_verify(str(ROOT))
print('# registry_verify: issues=%d stats=%s'
      % (len(reg_issues), json.dumps(reg_stats, ensure_ascii=False, sort_keys=True)[:140]))

# 枚举面：community 各包的 outputs 下**所有文件**
files = sorted(p.relative_to(ROOT).as_posix()
               for p in ROOT.glob('community/*/outputs/**/*') if p.is_file())
print('# outputs 下文件 %d 份' % len(files))

detect_rows = []
for rel in files:
    form, tier = of.detect(str(ROOT), rel)
    detect_rows.append((rel, form, tier))

xml_rows = []
for rel in files:
    if rel.endswith('.graphml'):
        xml_rows.append((rel, 'graphml', of._check_graphml(str(ROOT), rel)))
    elif rel.endswith('.svg') or rel.endswith('.xml'):
        xml_rows.append((rel, 'xml', of._check_xml(str(ROOT), rel)))
print('# XML 面 %d 份（其中报 issue 的 %d 份）'
      % (len(xml_rows), sum(1 for r in xml_rows if r[2])))


def arr(v):
    return "&[%s]" % ", ".join(rr(str(x)) for x in v)


detect_entries = "\n".join('        (%s, %s, %s),' % (rr(r), rr(f), rr(t))
                           for r, f, t in detect_rows)
xml_entries = "\n".join('        (%s, %s, %s),' % (rr(r), rr(k), arr(i))
                        for r, k, i in xml_rows)

TEMPLATE = r'''
    // >>> GENERATED by tools/gen_output_forms_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== 块 A 差分（期望值由生成器从真源取）=====
    ///
    /// 覆盖：形态清单自检（`registry_verify`）/ 形态识别 + 档位（`detect`，逐件）/ XML 面
    /// （`_check_xml` / `_check_graphml`，逐件）。XML 良构失败的**文本不可比**（CPython 的
    /// ParseError vs 本线），真语料上全部良构，故本条不涉该偏差。
    #[test]
    fn output_forms_registry_matches_truth_source() {
        let root = crate::testutil::repo_root();
        let (issues, stats) = registry_verify(&root);
        assert_eq!(issues, @@REGI@@ as &[&str]);
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@REGS@@).unwrap(),
        )
        .unwrap();
        assert!(crate::jsonread::json_eq(&stats, &want),
                "registry stats 不一致\n  实得 {}\n  期望 {}", stats.dumps(), want.dumps());
    }

    #[test]
    fn output_forms_detect_matches_truth_source() {
        let root = crate::testutil::repo_root();
        let cases: &[(&str, &str, &str)] = &[
@@DETECT@@
        ];
        for (rel, want_form, want_tier) in cases {
            let (form, tier) = detect(&root, rel);
            assert_eq!(&form, want_form, "{} 的形态", rel);
            assert_eq!(&tier, want_tier, "{} 的档位", rel);
        }
    }

    #[test]
    fn output_forms_xml_faces_match_truth_source() {
        let root = crate::testutil::repo_root();
        let cases: &[(&str, &str, &[&str])] = &[
@@XML@@
        ];
        for (rel, kind, want) in cases {
            let got = if *kind == "graphml" {
                check_graphml(&root, rel)
            } else {
                check_xml(&root, rel)
            };
            assert_eq!(got, want.to_vec(), "{} 的 XML 面 issue", rel);
        }
    }
    // <<< GENERATED
'''
text = (TEMPLATE
        .replace('@@REGI@@', arr(reg_issues))
        .replace('@@REGS@@', rr(json.dumps(reg_stats, ensure_ascii=False, sort_keys=True)))
        .replace('@@DETECT@@', detect_entries)
        .replace('@@XML@@', xml_entries))
BEGIN = '    // >>> GENERATED by tools/gen_output_forms_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'output_forms.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入块 A 判据（detect %d 件 / XML %d 件）' % (len(detect_rows), len(xml_rows)))
