"""为 `code_metrics.scan` 生成**分支级**判据。

真语料上它 **0 issue**（棘轮全绿）⇒ 三支全未踩到。本夹具逐支踩：
冻结值超标（`lines` / `max_fn_lines` / `max_fn_cc` 三键各一支）/ 新文件超限（同样三键）/
语法坏 / 基线里 cap=0 的短路支 / 基线内未超标 / **缺基线**的 WARN 支（单独一个用例）。

**语法坏那一支的文本不可比**：真源给 CPython 的 `SyntaxError` 文本，本线给本线解析器的文本。
故两侧都做**归一**（`<rel> <SYNTAX>`）后比较，另单独断言"确实报了且前缀对"——不假装文本相同。

用法：python engine/rust/tools/gen_code_metrics_branches.py
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import code_metrics as cm  # noqa: E402

FIX = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'code-metrics-branches'
if FIX.exists():
    shutil.rmtree(FIX)

# 大函数：31 个 if ⇒ cc=32；行数也长
BIGFUNC = 'def big():\n' + ''.join('    if x == %d:\n        pass\n' % i for i in range(31))
LONG = 'x = 1\n' * 801
SYNTAX = 'def f(:\n    pass\n'
ZERO = 'y = 1\n'
OK = 'z = 1\n'

BASELINE = {
    "schema": "nf-code-metrics/1",
    "limits": {"lines": 800, "max_fn_lines": 120, "max_fn_cc": 25},
    "files": {
        "desktop/src/core/zz_big.py": {"lines": 1, "max_fn_lines": 2, "max_fn_cc": 3},
        "scripts/zz_zero_cap.py": {"lines": 0, "max_fn_lines": 9999, "max_fn_cc": 9999},
        "scripts/zz_ok.py": {"lines": 9999, "max_fn_lines": 9999, "max_fn_cc": 9999},
    },
}

FILES = {
    'desktop/src/core/zz_big.py': BIGFUNC,
    'scripts/zz_new_long.py': LONG,
    'scripts/zz_new_bigfunc.py': BIGFUNC,
    'scripts/zz_syntax.py': SYNTAX,
    'scripts/zz_zero_cap.py': ZERO,
    'scripts/zz_ok.py': OK,
    'protocol/code_metrics_baseline.json':
        json.dumps(BASELINE, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
}
for rel, body in FILES.items():
    fp = FIX / rel
    fp.parent.mkdir(parents=True, exist_ok=True)
    fp.write_text(body, encoding='utf-8', newline='')

SYN_REL = 'scripts/zz_syntax.py'


def norm(issues):
    return [('%s <SYNTAX>' % SYN_REL) if x.startswith(SYN_REL + ' ') else x for x in issues]


issues, warns, stats = cm.scan(str(FIX))
print('# 真源：issues=%d warns=%d' % (len(issues), len(warns)))
for x in issues:
    print('#   ! %s' % x[:120])
print('# stats = %s' % json.dumps(stats, ensure_ascii=False, sort_keys=True))

# 缺基线那一支：换个根，不放 baseline
FIX2 = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'code-metrics-nobase'
if FIX2.exists():
    shutil.rmtree(FIX2)
(FIX2 / 'scripts').mkdir(parents=True)
(FIX2 / 'scripts' / 'zz_ok.py').write_text(OK, encoding='utf-8', newline='')
issues2, warns2, stats2 = cm.scan(str(FIX2))
print('# 缺基线：issues=%d warns=%d' % (len(issues2), len(warns2)))
for x in warns2:
    print('#   ~ %s' % x[:120])


def arr(v):
    return "&[%s]" % ", ".join(rr(x) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_code_metrics_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_code_metrics_branches.py` 从真源生成）=====
    ///
    /// 真语料上该判据 **0 issue** ⇒ 三支全未踩到。本夹具逐支踩：冻结值超标（三键各一支）/
    /// 新文件超限（同样三键）/ 语法坏 / 基线里 `cap=0` 的短路支 / 基线内未超标 /
    /// 缺基线的 WARN 支（单独用例）。
    ///
    /// **语法坏那一支的文本不可比**（真源给 CPython `SyntaxError` 文本，本线给本线解析器的），
    /// 故两侧都归一到 `<rel> <SYNTAX>` 后比较——**不假装文本相同**。
    const CM_BASELINE: &str = @@BASELINE@@;
    const CM_BIGFUNC_PREFIX: &str = "def big():\n";
    const CM_BIGFUNC_BODY: &str = @@BIGBODY@@;
    const CM_OK: &str = "z = 1\n";
    const CM_SYNTAX: &str = @@SYNTAX@@;
    const CM_SYN_REL: &str = "scripts/zz_syntax.py";

    fn cm_bigfunc() -> String {
        let mut s = String::from(CM_BIGFUNC_PREFIX);
        for i in 0..31 {
            s.push_str(&format!("    if x == {}:\n        pass\n", i));
        }
        s
    }

    fn build_code_metrics_fixture(with_baseline: bool) -> std::path::PathBuf {
        let name = if with_baseline { "code-metrics-branches" } else { "code-metrics-nobase" };
        let root = crate::testutil::fixture(name);
        let write = |rel: &str, body: &str| {
            let p = root.join(rel);
            std::fs::create_dir_all(p.parent().unwrap()).unwrap();
            std::fs::write(p, body).unwrap();
        };
        if with_baseline {
            write("desktop/src/core/zz_big.py", &cm_bigfunc());
            write("scripts/zz_new_long.py", &"x = 1\n".repeat(801));
            write("scripts/zz_new_bigfunc.py", &cm_bigfunc());
        }
        if with_baseline {
            write("scripts/zz_syntax.py", CM_SYNTAX);
            write("scripts/zz_zero_cap.py", "y = 1\n");
        }
        write("scripts/zz_ok.py", CM_OK);
        if with_baseline {
            write("protocol/code_metrics_baseline.json", CM_BASELINE);
        }
        root
    }

    fn cm_norm(issues: &[String]) -> Vec<String> {
        issues
            .iter()
            .map(|x| {
                if x.starts_with(&format!("{} ", CM_SYN_REL)) {
                    format!("{} <SYNTAX>", CM_SYN_REL)
                } else {
                    x.clone()
                }
            })
            .collect()
    }

    #[test]
    fn code_metrics_matches_truth_source_branch_by_branch() {
        let root = build_code_metrics_fixture(true);
        let (issues, warns, stats) = scan(&root);
        assert_eq!(cm_norm(&issues), @@ISSUES@@ as &[&str], "issues 须逐字且同序（语法支已归一）");
        assert_eq!(warns, @@WARNS@@ as &[&str], "warns 须逐字且同序");
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@WANT@@).unwrap(),
        )
        .unwrap();
        assert!(
            crate::jsonread::json_eq(&stats, &want),
            "stats 不一致\n  实得 {}\n  期望 {}",
            stats.dumps(),
            want.dumps()
        );
    }

    #[test]
    fn code_metrics_without_baseline_warns() {
        let root = build_code_metrics_fixture(false);
        let (issues, warns, _stats) = scan(&root);
        assert!(issues.is_empty(), "缺基线不该产生 issue：{:?}", issues);
        assert_eq!(warns, @@WARNS2@@ as &[&str]);
    }
    // <<< GENERATED
'''

text = (TEMPLATE
        .replace('@@BASELINE@@', rr(FILES['protocol/code_metrics_baseline.json']))
        .replace('@@BIGBODY@@', rr('    if x == 0:\n        pass\n'))
        .replace('@@SYNTAX@@', rr(SYNTAX))
        .replace('@@ISSUES@@', arr(norm(issues)))
        .replace('@@WARNS@@', arr(warns))
        .replace('@@WANT@@', rr(json.dumps(stats, ensure_ascii=False, sort_keys=True)))
        .replace('@@WARNS2@@', arr(warns2)))

BEGIN = '    // >>> GENERATED by tools/gen_code_metrics_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'code_metrics.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    if '#[cfg(test)]' not in t:
        t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    path.write_text(t.rstrip()[:-1].rstrip() + '\n' + block + '}\n', encoding='utf-8', newline='')
    print('# 已插入标记区间')
