"""生成真源 `conformance_report.CONTRACTS` 的**顺序**表（Merkle 叶序由它决定）。

真源调用顺序 = `CONTRACTS` 的定义顺序；本线此前只有按字母序的 `PORTED`（用于分派）。
顺序错了 → 封缄根错 → `conformance_report` 判据必红。故此表**从真源转录**，不手写。

用法：python engine/rust/tools/gen_contract_order.py
"""
import pathlib
import sys

sys.path.insert(0, 'engine/rust/tools')
sys.path.insert(0, 'desktop/src')
from _rustlit import rs  # noqa: E402
from core import conformance_report as cr  # noqa: E402

ids = [c[0] for c in cr.CONTRACTS]
descs = {c[0]: c[2] for c in cr.CONTRACTS}

body = ['// >>> GENERATED by tools/gen_contract_order.py（勿手改；重跑生成器覆盖本段）',
        '/// 真源 `CONTRACTS` 的**定义顺序**——Merkle 叶序由它决定，顺序错了封缄根就错。',
        '#[rustfmt::skip]',
        'pub const CONTRACT_ORDER: [&str; %d] = [' % len(ids)]
body += ['    %s,' % rs(i) for i in ids]
body += ['];', '// <<< GENERATED']

p = pathlib.Path('engine/rust/src/conformance.rs')
t = p.read_text(encoding='utf-8')
BEGIN = '// >>> GENERATED by tools/gen_contract_order.py'
END = '// <<< GENERATED'
block = '\n'.join(body)
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n' + block + '\n'
p.write_text(t, encoding='utf-8', newline='')
print('已写入 CONTRACT_ORDER（%d 条）' % len(ids))

# 顺带核对：每条的 description 必须与真源逐字一致（转义后比较）
bad = []
for i in ids:
    d = descs[i]
    if rs(d) not in t and ('"%s"' % d) not in t and d not in t:
        bad.append(i)
if bad:
    print('  ⚠️ 以下契约的 description 未在 conformance.rs/contracts.rs 中逐字找到：', bad[:5])
