"""为 `pyrandom`（CPython MT19937 + sample）生成差分判据。

`pack_combo.breadth` 用 `random.Random(20260923).sample(names, k)` 抽 3/4/5/6 元样，样本**进判据与 stats**。
故本判据按真源**同样的循环**抽一遍，逐序列比对——抽样器差一位，广度证明的结论就不同。

用法：python engine/rust/tools/gen_pyrandom_cases.py
"""
import json
import pathlib
import random
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402

SEED = 20260923
# 参与面 = 真源 `profiles(root)` 的键（sorted）
names = sorted(p.name for p in (ROOT / 'community').iterdir()
               if p.is_dir() and (p / 'protocol.yaml').is_file())
print('# names = %d 个' % len(names))

rnd = random.Random(SEED)
# ① getrandbits 序列（k = 1..8）
bits = [rnd.getrandbits(k) for k in range(1, 9)]
print('# getrandbits(1..8) =', bits)

# ② 与 breadth 完全同款的抽样循环
rnd = random.Random(SEED)


def draw(size, want):
    picks = set()
    if len(names) >= size:
        while len(picks) < min(want, 5000):
            picks.add(tuple(sorted(rnd.sample(names, size))))
    return sorted(picks)


triples = draw(3, 400)
quads = draw(4, 200)
quints = draw(5, 120)
sexts = draw(6, 60)
print('# 抽样：三元 %d / 四元 %d / 五元 %d / 六元 %d'
      % (len(triples), len(quads), len(quints), len(sexts)))


def arr(v):
    return "&[%s]" % ", ".join(rr(str(x)) for x in v)


def combos(v):
    # ⚠️ 每个内层数组前必须显式 `&`：`&[[a, b], …]` 是 `&[[&str; k]; N]`，
    # 无法逐元素退化成 `&[&str]`（Rust 不做"数组的数组"到"切片的切片"的隐式转换）。
    return "&[%s]" % ", ".join('&[%s]' % ", ".join(rr(str(y)) for y in t) for t in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_pyrandom_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== 与真源 `random.Random(20260923)` 逐序列比对 =====
    ///
    /// ① `getrandbits(1..8)` 的**前 8 个**取值；② 与 `breadth` **同款循环**抽出的
    /// 三/四/五/六元样集合（真语料 111 个包名）。
    const PY_NAMES: [&str; @@NN@@] = [
@@NAMES@@
    ];

    #[test]
    fn pyrandom_getrandbits_matches_cpython() {
        let mut r = PyRandom::new(20260923);
        let want: [u32; 8] = @@BITS@@;
        for (i, w) in want.iter().enumerate() {
            assert_eq!(r.getrandbits(i as u32 + 1), *w, "getrandbits({})", i + 1);
        }
    }

    #[test]
    fn pyrandom_sample_matches_cpython_over_breadth_loop() {
        let names: Vec<String> = PY_NAMES.iter().map(|s| s.to_string()).collect();
        let mut r = PyRandom::new(20260923);
        let draw = |r: &mut PyRandom, size: usize, want: usize| -> Vec<Vec<String>> {
            let mut picks: std::collections::BTreeSet<Vec<String>> =
                std::collections::BTreeSet::new();
            if names.len() >= size {
                while picks.len() < std::cmp::min(want, 5000) {
                    let mut s = r.sample(&names, size);
                    s.sort();
                    picks.insert(s);
                }
            }
            picks.into_iter().collect()
        };
        // 期望值以 `&[&[&str]]` 常量给出（内层是定长数组，直接传参对不上签名）
        const TRIPLES: &[&[&str]] = @@TRIPLES@@;
        const QUADS: &[&[&str]] = @@QUADS@@;
        const QUINTS: &[&[&str]] = @@QUINTS@@;
        const SEXTS: &[&[&str]] = @@SEXTS@@;
        fn to_owned_vec(v: &[&[&str]]) -> Vec<Vec<String>> {
            v.iter().map(|t| t.iter().map(|s| s.to_string()).collect()).collect()
        }
        let triples = draw(&mut r, 3, 400);
        assert_eq!(triples, to_owned_vec(TRIPLES), "三元样");
        let quads = draw(&mut r, 4, 200);
        assert_eq!(quads, to_owned_vec(@@QUADS@@), "四元样");
        let quints = draw(&mut r, 5, 120);
        assert_eq!(quints, to_owned_vec(@@QUINTS@@), "五元样");
        let sexts = draw(&mut r, 6, 60);
        assert_eq!(sexts, to_owned_vec(SEXTS), "六元样");
    }
    // <<< GENERATED
'''
text = (TEMPLATE
        .replace('@@NN@@', str(len(names)))
        .replace('@@NAMES@@', "\n".join('        %s,' % rr(n) for n in names))
        .replace('@@BITS@@', '[%s]' % ", ".join(str(b) for b in bits))
        .replace('@@TRIPLES@@', combos(triples))
        .replace('@@QUADS@@', combos(quads))
        .replace('@@QUINTS@@', combos(quints))
        .replace('@@SEXTS@@', combos(sexts)))
BEGIN = '    // >>> GENERATED by tools/gen_pyrandom_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'pyrandom.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入 pyrandom 判据')
