"""为 `output_forms` 的格式校验器生成差分判据。

① **真语料逐件**：`community/*/outputs/**` 下每一件按 `detect` 选校验器，与真源 `_FORM_CHECK`
   同款调用比对（`combo-cert` 属 `pack_combo` 面，本轮排除并记明）。
② **合成用例**：`_check_json` 的重复键/非 RFC 常量/语法坏等分支（真语料全良构，踩不到）。

用法：python engine/rust/tools/gen_output_forms_checks.py
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import output_forms as of  # noqa: E402

files = sorted(p.relative_to(ROOT).as_posix()
               for p in ROOT.glob('community/*/outputs/**/*') if p.is_file())
rows = []
skipped = []
for rel in files:
    form, _tier = of.detect(str(ROOT), rel)
    # `combo-cert` 的校验器（`_check_combo_cert`）已移植并接入 `form_check` ⇒ 不再排除
    checker = of._FORM_CHECK.get(form)
    issues = checker(str(ROOT), rel) if checker else []
    rows.append((rel, form, issues))
print('# 逐件校验：%d 件（报 issue 的 %d 件）；跳过 %d 件'
      % (len(rows), sum(1 for r in rows if r[2]), len(skipped)))

# ---- 合成用例（真语料踩不到的 JSON 分支）
FIX = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'output-forms-json'
if FIX.exists():
    shutil.rmtree(FIX)
FIX.mkdir(parents=True)
CASES = {
    'dup.json': '{"a": 1, "a": 2}\n',
    'dup_nested.json': '{"o": {"k": 1, "k": 2}, "arr": [{"z": 1, "z": 2}]}\n',
    'nan.json': '{"v": NaN, "w": Infinity, "x": -Infinity}\n',
    'ok.json': '{"a": [1, 2.5, "s", true, null], "b": {"c": "d"}}\n',
    'bad.json': '{"a": \n',
    'extra.json': '{} {}\n',
    'ctrl.json': '{"a": "x\u0001y"}\n',
    'unicode.json': '{"\\u4e2d": "\\ud83d\\ude00"}\n',
    'empty.json': '',
    'scalar.json': '42\n',
}
for name, body in CASES.items():
    (FIX / name).write_text(body, encoding='utf-8', newline='')
syn = []
for name in sorted(CASES):
    issues = of._check_json(str(FIX), name)
    syn.append((name, issues))
    print('# 合成 %-16s issues=%d %s' % (name, len(issues), (issues[0][:70] if issues else '')))


def arr(v):
    return "&[%s]" % ", ".join(rr(str(x)) for x in v)


entries = "\n".join('        (%s, %s, %s),' % (rr(rel), rr(form), arr(issues))
                    for rel, form, issues in rows)
syn_entries = "\n".join('        (%s, %s),' % (rr(n), arr(i)) for n, i in syn)
fix_entries = "\n".join('        (%s, %s),' % (rr(k), rr(v)) for k, v in sorted(CASES.items()))

TEMPLATE = r'''
    // >>> GENERATED by tools/gen_output_forms_checks.py（勿手改；重跑生成器覆盖本段）
    /// ===== ① 真语料逐件（按 `detect` 选校验器，与真源 `_FORM_CHECK` 同款调用）=====
    ///
    /// 覆盖 outputs 下 %d 件（报 issue 的 %d 件）。**含 `combo-cert`**（%d 件）——
    /// 它对应的 `_check_combo_cert` 属 `pack_combo` 面，本轮未移植，`form_check` 对它返回
    /// `None`（**不静默当通过**）。
    #[test]
    fn output_forms_checkers_match_truth_source_over_corpus() {
        let root = crate::testutil::repo_root();
        let cases: &[(&str, &str, &[&str])] = &[
@@CASES@@
        ];
        for (rel, form, want) in cases {
            let got = form_check(form, &root, rel)
                .unwrap_or_else(|| panic!("{} 的形态 {} 无校验器", rel, form));
            assert_eq!(got, want.to_vec(), "{} ({}) 的校验结论", rel, form);
        }
    }

    /// ===== ② 合成用例：真语料踩不到的 JSON 分支（重复键 / 非 RFC 常量 / 语法坏）=====
    const OF_JSON_FILES: [(&str, &str); @@NF@@] = [
@@FILES@@
    ];

    #[test]
    fn output_forms_json_branches_match_truth_source() {
        let root = crate::testutil::fixture("output-forms-json-src");
        for (rel, body) in OF_JSON_FILES {
            std::fs::write(root.join(rel), body).unwrap();
        }
        let cases: &[(&str, &[&str])] = &[
@@SYN@@
        ];
        // ⚠️ **解析失败的文本不可比**（CPython `json` vs 本线 `jsonmini`）⇒ 归一到前缀后比较。
        // 归一**不削弱判据**：某例在一侧报错、另一侧不报，归一后仍会不同（那才是真结论差）。
        let norm = |v: &[String]| -> Vec<String> {
            v.iter()
                .map(|x| match x.find("JSON 不可解析：") {
                    Some(k) => format!("{}<TEXT>", &x[..k + "JSON 不可解析：".len()]),
                    None => x.clone(),
                })
                .collect()
        };
        for (rel, want) in cases {
            assert_eq!(
                norm(&check_json(&root, rel)),
                norm(&want.iter().map(|s| s.to_string()).collect::<Vec<_>>()),
                "{} 的 JSON 结论",
                rel
            );
        }
    }
    // <<< GENERATED
'''
text = (TEMPLATE % (len(rows), sum(1 for r in rows if r[2]), len(skipped)))
text = (text.replace('@@CASES@@', entries)
        .replace('@@NF@@', str(len(CASES)))
        .replace('@@FILES@@', fix_entries)
        .replace('@@SYN@@', syn_entries))
BEGIN = '    // >>> GENERATED by tools/gen_output_forms_checks.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'output_forms_checks.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入校验器判据（真语料 %d 件 / 合成 %d 例）' % (len(rows), len(syn)))
