"""为 `library.verify`（`library-verify` 契约）生成分支级判据。

真语料上该契约**全绿**（馆藏 frontmatter 真源零 FAIL）⇒ 对账核不到错误分支。

⚠️ **刻意避开依赖"当天日期"的分支**（如 `doc_hygiene` 的「超过 N 个月未更新」）——
那类夹具会随日历变红。本面的日期判据只做**格式**校验（`非 YYYY-MM-DD`），与当天无关。

用法：python engine/rust/tools/gen_library_verify_branches.py
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
from _rustlit import rs  # noqa: E402  —— Rust 普通字符串字面量（键等）
from core import library as lb  # noqa: E402

FIX = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'library-verify-branches'
if FIX.exists():
    shutil.rmtree(FIX)
LIB = FIX / 'library'
LIB.mkdir(parents=True)


def doc(eid, fields, body="正文\n"):
    fm = "\n".join("%s: %s" % (k, v) for k, v in fields.items())
    return "---\n%s\n---\n%s" % (fm, body)


FILES = {
    # ① 缺 frontmatter（没有 `---` 头）
    'NF-1.md': "没有 frontmatter 的正文\n",
    # ② 缺必填键（type/title 都没给）
    'NF-2.md': doc('NF-2', {'id': 'NF-2'}),
    # ③ id 与文件名不一致
    'NF-3.md': doc('NF-3', {'id': 'NF-其他', 'type': 't', 'title': 'X'}),
    # ④ license 不在词表
    'NF-4.md': doc('NF-4', {'id': 'NF-4', 'type': 't', 'title': 'X', 'license': 'Frobnicate'}),
    # ⑤ status 不在词表
    'NF-5.md': doc('NF-5', {'id': 'NF-5', 'type': 't', 'title': 'X', 'status': 'bogus'}),
    # ⑥ superseded 但缺 superseded_by
    'NF-6.md': doc('NF-6', {'id': 'NF-6', 'type': 't', 'title': 'X', 'status': 'superseded'}),
    # ⑦ superseded_by 指向不存在
    'NF-7.md': doc('NF-7', {'id': 'NF-7', 'type': 't', 'title': 'X', 'status': 'superseded',
                            'superseded_by': 'NF-999'}),
    # ⑧ superseded_by 指向自身（成环）
    'NF-8.md': doc('NF-8', {'id': 'NF-8', 'type': 't', 'title': 'X', 'status': 'superseded',
                            'superseded_by': 'NF-8'}),
    # ⑨ 日期格式非法（三个键各踩一次）
    'NF-9.md': doc('NF-9', {'id': 'NF-9', 'type': 't', 'title': 'X',
                            'generated': '2026/01/01', 'verified': '2026-1-1',
                            'stale_after': 'x'}),
    # ⑩ attestation 非 64 位十六进制
    'NF-10.md': doc('NF-10', {'id': 'NF-10', 'type': 't', 'title': 'X', 'attestation': 'zz'}),
    # ⑪ 全绿（含 sources ⇒ 无 warn）
    'NF-11.md': doc('NF-11', {'id': 'NF-11', 'type': 't', 'title': 'X',
                              'license': 'MIT', 'status': 'active', 'sources': '[a]'}),
}

for name, body in FILES.items():
    (LIB / name).write_text(body, encoding='utf-8', newline='')

issues, warns, stats = lb.verify(str(FIX))
print('# 真源：issues=%d warns=%d' % (len(issues), len(warns)))
for x in issues:
    print('#   ! %s' % x)
for x in warns:
    print('#   ~ %s' % x)
print('# stats = %s' % json.dumps(stats, ensure_ascii=False, sort_keys=True))


def rj(s):
    assert '"#' not in s
    return 'r#"%s"#' % s


def arr(v):
    return "&[%s]" % ", ".join(json.dumps(x, ensure_ascii=False) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_library_verify_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_library_verify_branches.py` 从真源生成）=====
    ///
    /// 契约在真语料上**全绿** ⇒ 对账核不到错误分支。本夹具逐支踩：缺 frontmatter / 缺必填键 /
    /// id 与文件名不一致 / license 不在词表 / status 不在词表 / superseded 缺 superseded_by /
    /// superseded_by 指向不存在 / 指向自身（成环）/ 三个日期键格式非法 / attestation 非 64 位十六进制 /
    /// 缺 sources(WARN) / 全绿。
    ///
    /// ⚠️ **刻意避开依赖"当天日期"的分支**——那类夹具会随日历变红。本面的日期判据只做**格式**校验。
    const LB_FILES: [(&str, &str); @@NF@@] = [
@@FILES@@
    ];

    fn build_lb_fixture() -> std::path::PathBuf {
        let root = crate::testutil::fixture("library-verify-branches");
        std::fs::create_dir_all(root.join("library")).unwrap();
        for (name, body) in LB_FILES {
            std::fs::write(root.join("library").join(name), body).unwrap();
        }
        root
    }

    #[test]
    fn verify_matches_truth_source_branch_by_branch() {
        let root = build_lb_fixture();
        let got = verify(&root);
        assert_eq!(got.issues, @@ISSUES@@ as &[&str], "issues 须逐字且同序");
        assert_eq!(got.warns, @@WARNS@@ as &[&str], "warns 须逐字且同序");
    }
    // <<< GENERATED
'''

text = (TEMPLATE
        .replace('@@NF@@', str(len(FILES)))
        .replace('@@FILES@@', "\n".join('        (%s, %s),' % (rs(k), rj(v))
                                       for k, v in sorted(FILES.items())))
        .replace('@@ISSUES@@', arr(issues))
        .replace('@@WARNS@@', arr(warns)))

BEGIN = '    // >>> GENERATED by tools/gen_library_verify_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]
path = ROOT / 'engine' / 'rust' / 'src' / 'library.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    path.write_text(t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n'
                    + block + '}\n', encoding='utf-8', newline='')
    print('# 已追加标记区间')
