import json
import pathlib
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import quality_depth_scan as qd  # noqa: E402

# ---------------------------------------------------------------- ① depth-scan 的常驻 oracle
issues, stats = qd.scan(str(ROOT))
want = json.dumps(stats, ensure_ascii=False, sort_keys=True)
print('# depth-scan: issues=%d / stats %d 字符 / %d 项'
      % (len(issues), len(want), len(stats)))

TEMPLATE = r'''
    // >>> GENERATED by tools/gen_depth_scan_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== `depth-scan` 面的**对账 oracle**：与真源 `quality_depth_scan.scan` 逐字节比对 =====
    ///
    /// 面登记见 `desktop/tests/test_rust_fastlane.py` 的 `COVERED_FACES["depth-scan"]`
    /// ——「不许有无人核的面」那条规矩要求本面有 oracle，这就是它。
    ///
    /// 覆盖面：13 个子扫描器 + `tool_face`/`world_model`/`world_slots`/`payload_consumer`
    /// 共 14 项统计；比对取**最严**口径（规范 JSON 字符串相等，含键序）。
    #[test]
    fn depth_scan_matches_truth_source() {
        let root = crate::testutil::repo_root();
        let (issues, stats) = scan(&root);
        assert_eq!(issues, @@ISSUES@@ as &[&str], "issues 须逐字且同序");
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@WANT@@).unwrap(),
        )
        .unwrap();
        assert!(
            crate::jsonread::json_eq(&stats, &want),
            "聚合 stats 不一致\n  实得 {}\n  期望 {}",
            stats.dumps_default(),
            want.dumps_default()
        );
        assert_eq!(stats.dumps_default(), @@CANON@@, "规范 JSON 须逐字节相同");
    }

    /// 输入面清单**不许空转**：`QD_INPUTS` 必须非空且覆盖各子扫描器的已知面。
    ///
    /// 真源把它用作内容键缓存的面；本线不移植缓存，但把它作为**面的事实记录**留着，
    /// 并在这里核一遍——否则它就是个没人看的常量（`never used` 告警）。
    #[test]
    fn qd_inputs_records_the_composite_face() {
        assert!(QD_INPUTS.len() >= 25, "并集面不许塌缩：{}", QD_INPUTS.len());
        for must in ["community/**/*", "docs/**/*", "04_模块库/**/*", "05_资产库/**/*",
                     "protocol/**/*", "desktop/src/**/*.py"] {
            assert!(QD_INPUTS.contains(&must), "并集面缺 {}：{:?}", must, QD_INPUTS);
        }
        // 子扫描器真读的那三条（真源注释记的"陈旧洞"）必须在面内
        for must in [".rivet/private_archive/ai_packs/specs/*.json",
                     "desktop/src/core/registry.json", "agent_组装指令包_v0.2.md"] {
            assert!(QD_INPUTS.contains(&must), "并集面缺补齐项 {}：{:?}", must, QD_INPUTS);
        }
    }
    // <<< GENERATED
'''
text = (TEMPLATE.replace('@@ISSUES@@', "&[%s]" % ", ".join(rr(str(x)) for x in issues))
        .replace('@@WANT@@', rr(want))
        .replace('@@CANON@@', rr(want)))
BEGIN = '    // >>> GENERATED by tools/gen_depth_scan_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'quality_depth_scan.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入 depth-scan 的常驻 oracle')

# ---------------------------------------------------------------- ② 登记面
f = ROOT / 'desktop' / 'tests' / 'test_rust_fastlane.py'
ft = f.read_text(encoding='utf-8')
if '"depth-scan":' not in ft:
    anchor = '''    "code-metrics": "差分对账入口；oracle = engine/rust/check_parity.ps1 面 15 "'''
    assert anchor in ft, '登记表锚点未命中'
    add = ('''    "depth-scan": "差分对账入口；oracle = engine/rust/src/quality_depth_scan.rs 的 "
                  "tests::depth_scan_matches_truth_source（13 子扫描器 + 4 后置项，"
                  "规范 JSON 逐字节相同）",\n''')
    ft = ft.replace(anchor, add + anchor, 1)
    f.write_text(ft, encoding='utf-8', newline='')
    print('② 已登记 depth-scan 面')
else:
    print('② 已登记')

# ---------------------------------------------------------------- ③ HELPER 也过 _r()（与报告口径一致）
g = ROOT / 'engine' / 'rust' / 'tools' / 'gen_quant_metrics_cases.py'
gt = g.read_text(encoding='utf-8')
old = """HELPER = {
    'rank': [qm._rank(x) for x in (FACTOR, TIED, [5.0], [])],
    'pearson': [qm._pearson(FACTOR, FWD), qm._pearson(TIED, FACTOR),
                qm._pearson([1.0], [2.0]), qm._pearson([1.0, 1.0], [2.0, 3.0])],
    'ic_spearman': [qm.information_coefficient(FACTOR, FWD),
                    qm.information_coefficient(TIED, FWD)],
    'ic_pearson': [qm.information_coefficient(FACTOR, FWD, method='pearson')],
    'turnover_single': [qm.turnover(W1), qm.turnover([]), qm.turnover([[1.0]])],
    'turnover_double': [qm.turnover(W1, single_side=False)],
}"""
new = """def _rr(x):
    \"\"\"标量 → `_r()`（6 位）；列表逐项。判据侧同样过 `r6()`，两侧口径一致。\"\"\"
    if isinstance(x, list):
        return [_rr(v) for v in x]
    return qm._r(x) if isinstance(x, (int, float)) else x


HELPER = {
    'rank': [_rr(qm._rank(x)) for x in (FACTOR, TIED, [5.0], [])],
    'pearson': [_rr(x) for x in (qm._pearson(FACTOR, FWD), qm._pearson(TIED, FACTOR),
                                 qm._pearson([1.0], [2.0]), qm._pearson([1.0, 1.0], [2.0, 3.0]))],
    'ic_spearman': [_rr(qm.information_coefficient(FACTOR, FWD)),
                    _rr(qm.information_coefficient(TIED, FWD))],
    'ic_pearson': [_rr(qm.information_coefficient(FACTOR, FWD, method='pearson'))],
    'turnover_single': [_rr(qm.turnover(W1)), _rr(qm.turnover([])), _rr(qm.turnover([[1.0]]))],
    'turnover_double': [_rr(qm.turnover(W1, single_side=False))],
}"""
assert old in gt, 'HELPER 锚点未命中'
gt = gt.replace(old, new, 1)
g.write_text(gt, encoding='utf-8', newline='')
print('③ 已把 HELPER 期望值过 _r()（与判据侧的 r6() 同口径）')
