"""生成 `src/py_stdlib.rs`：`sys.stdlib_module_names` 的常量表。

真源 `purity_scan._is_local` 用 `mod in sys.stdlib_module_names` 判"是否标准库"
（标准库 import 不计入 R5）。那是**解释器自带的集合**，与 `root` 无关，故本线转录成表。
**该集合随 Python 版本变**——换解释器/升级版本后须重跑本脚本（判据会红，见 `tools/README.md`）。

用法：python engine/rust/tools/gen_py_stdlib.py
"""
import pathlib
import sys

sys.path.insert(0, 'engine/rust/tools')
from _rustlit import rs  # noqa: E402

ROOT = pathlib.Path('.').resolve()
names = sorted(sys.stdlib_module_names)

out = ['//! `sys.stdlib_module_names` 的转录表 —— 供 `purity_scan` 的 R5 判「是否标准库」。',
       '//!',
       '//! 真源用的是**解释器自带集合**（与 `root` 无关）。本表由',
       '//! `tools/gen_py_stdlib.py` 从当前解释器生成，**勿手改**。',
       '//!',
       '//! ⚠️ 该集合**随 Python 版本变**。换解释器或升级版本后若本表过期，',
       '//! `purity-scan` 的对账会红（这正是要的：宁可红，也不要静默用旧集合判"标准库"）。',
       '',
       '// >>> GENERATED by tools/gen_py_stdlib.py（勿手改；重跑生成器覆盖本段）',
       '#[rustfmt::skip]',
       'pub const STDLIB: [&str; %d] = [' % len(names)]
out += ['    %s,' % rs(n) for n in names]
out += ['];', '// <<< GENERATED']
src = '\n'.join(out) + '\n'

p = ROOT / 'engine/rust/src/py_stdlib.rs'
BEGIN = '// >>> GENERATED by tools/gen_py_stdlib.py'
END = '// <<< GENERATED'
if p.is_file():
    t = p.read_text(encoding='utf-8')
    if BEGIN in t:
        a = t.index(BEGIN)
        b = t.index(END, a) + len(END)
        t = t[:a] + src[t.index(BEGIN):] if False else t[:a] + '\n'.join(out[out.index(BEGIN):]) + t[b:]
        p.write_text(t, encoding='utf-8', newline='')
        print('已刷新 py_stdlib.rs（%d 条）' % len(names))
    else:
        p.write_text(t.rstrip() + '\n\n' + src, encoding='utf-8', newline='')
        print('已追加（%d 条）' % len(names))
else:
    p.write_text(src, encoding='utf-8', newline='')
    print('已生成 py_stdlib.rs（%d 条）' % len(names))
