"""为 `cognition`（术语表 + 执行分档）生成分支级判据。

真语料上该契约全绿（术语 11 · 使用面 16 · 执行档 2 · 合格实例 2）⇒ 对账核不到错误分支。
本夹具逐支踩 15 个分支。

用法：python engine/rust/tools/gen_cognition_branches.py
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
from core import cognition as cg  # noqa: E402
from core import conformance_report as cr  # noqa: E402

FIX = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'cognition-branches'
if FIX.exists():
    shutil.rmtree(FIX)
(FIX / 'protocol').mkdir(parents=True)
(FIX / 'docs').mkdir(parents=True)

GLOSSARY = {
    "schema": "wrong/1",                     # ① schema 不匹配
    "rules": [],                             # ② rules 为空
    "terms": [
        {"definition": "无 term"},           # ③ 无 term 的条目
        {"term": "甲", "definition": "定义甲", "source": "docs/s.md"},      # 全绿 + 计入 uses
        {"term": "甲", "definition": "定义甲2", "source": "docs/s.md"},     # ④ 术语重复
        {"term": "乙"},                       # ⑤ 缺 definition（且 source 为空 ⇒ 也报 source 不存在）
        {"term": "丙", "definition": "定义丙", "source": "no/such.md"},     # ⑥ source 不存在
        {"term": "丁", "definition": "定义丁", "source": "docs/s.md"},      # ⑦ 未在 source 中逐字出现
        {"term": "戊", "definition": "定义戊", "used_in": ["no/such.md"]},  # ⑧ used_in 不存在
        {"term": "己", "definition": "定义己", "used_in": ["docs/u.md"]},   # ⑨ used_in 未逐字出现
    ],
}
MODES = {
    "schema": "wrong/1",                     # ⑩ schema 不匹配
    "modes": [
        {"id": "m1", "required_blocks": ["## 块"], "instances": ["docs/inst-ok.md"]},   # 全绿
        {"id": "m1", "required_blocks": [], "instances": []},                          # ⑪ id 重复 ⑫ 缺 blocks ⑬ 无实例
        {"id": "m2", "required_blocks": ["## 块"], "instances": ["no/such.md"]},        # ⑭ 实例不存在
        {"id": "m3", "required_blocks": ["## 块"], "instances": ["docs/inst-bad.md"]},  # ⑮ 缺结构块
    ],
}

(FIX / 'protocol' / 'glossary.json').write_text(
    json.dumps(GLOSSARY, ensure_ascii=False), encoding='utf-8', newline='')
(FIX / 'protocol' / 'execution_modes.json').write_text(
    json.dumps(MODES, ensure_ascii=False), encoding='utf-8', newline='')

DOCS = {
    'docs/s.md': "# 源\n甲 在这里逐字出现\n",
    'docs/u.md': "# 使用面\n（不含那个术语）\n",
    'docs/inst-ok.md': "# 实例\n## 块\n内容\n",
    'docs/inst-bad.md': "# 实例\n没有那个结构块\n",
}
for rel, body in DOCS.items():
    (FIX / rel).write_text(body, encoding='utf-8', newline='')

issues, warns, stats = cg.scan(str(FIX))
ok, detail = cr._c_cognition(str(FIX))
print('# 真源：issues=%d warns=%d ok=%s' % (len(issues), len(warns), ok))
for x in issues:
    print('#   ! %s' % x)
print('# detail = %r' % detail)
print('# stats = %s' % json.dumps(stats, ensure_ascii=False, sort_keys=True))


from _rustlit import raw as rj  # noqa: E402  —— 分隔符自动升级，避免内容里的 \"#\ 提前终止
from _rustlit import rs  # noqa: E402  —— Rust 普通字符串字面量（键等）


def arr(v):
    return "&[%s]" % ", ".join(json.dumps(x, ensure_ascii=False) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_cognition_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_cognition_branches.py` 从真源生成）=====
    ///
    /// 真语料上该契约全绿 ⇒ 对账核不到错误分支。本夹具逐支踩：
    /// 术语表（schema / rules 空 / 无 term 条目 / 术语重复 / 缺 definition / source 不存在 /
    /// 未在 source 中逐字出现 / used_in 不存在 / used_in 未逐字出现 / 全绿计入 uses）
    /// + 执行分档（schema / id 重复 / 缺 required_blocks / 无实例 / 实例不存在 / 缺结构块）。
    const CG_GLOSSARY: &str = @@GLOSSARY@@;
    const CG_MODES: &str = @@MODES@@;
    const CG_DOCS: [(&str, &str); @@ND@@] = [
@@DOCS@@
    ];

    fn build_cognition_fixture() -> std::path::PathBuf {
        let root = crate::testutil::fixture("cognition-branches");
        std::fs::create_dir_all(root.join("protocol")).unwrap();
        std::fs::create_dir_all(root.join("docs")).unwrap();
        std::fs::write(root.join("protocol/glossary.json"), CG_GLOSSARY).unwrap();
        std::fs::write(root.join("protocol/execution_modes.json"), CG_MODES).unwrap();
        for (rel, body) in CG_DOCS {
            std::fs::write(root.join(rel), body).unwrap();
        }
        root
    }

    #[test]
    fn cognition_matches_truth_source_branch_by_branch() {
        let root = build_cognition_fixture();
        let (issues, _g, _m) = cognition_scan(&root);
        assert_eq!(issues, @@ISSUES@@ as &[&str], "issues 须逐字且同序");
        // 契约层：ok + detail（detail 里嵌了 terms/uses/modes/instances_ok 四项计数）
        let (ok, detail) = cognition(&root);
        assert_eq!(ok, @@OK@@);
        assert_eq!(detail, @@DETAIL@@);
    }
    // <<< GENERATED
'''

text = (TEMPLATE
        .replace('@@GLOSSARY@@', rj(json.dumps(GLOSSARY, ensure_ascii=False)))
        .replace('@@MODES@@', rj(json.dumps(MODES, ensure_ascii=False)))
        .replace('@@ND@@', str(len(DOCS)))
        .replace('@@DOCS@@', "\n".join('        (%s, %s),' % (rs(k), rj(v))
                                       for k, v in sorted(DOCS.items())))
        .replace('@@ISSUES@@', arr(issues))
        .replace('@@OK@@', 'true' if ok else 'false')
        .replace('@@DETAIL@@', json.dumps(detail, ensure_ascii=False)))

BEGIN = '    // >>> GENERATED by tools/gen_cognition_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'contracts.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    # 插到现有 tests 模块收尾之前
    idx = t.rstrip().rfind('\n}')
    path.write_text(t[:idx] + '\n' + block + t[idx:], encoding='utf-8', newline='')
    print('# 已插入标记区间')
