"""生成 `src/output_tables.rs`：`output_forms` 依赖的两张小表。

- `quant_metrics` 的**模块级名字**：真源 `_check_quant_metrics` 用 `hasattr(qm, fn)` 判
  「宣称的引擎是否真实存在」（宣称≠实现）；
- `domain_metrics.FAMILIES`：真源 `_check_domain_report` 用它判「度量族是否在本仓登记」。

两者都是**真源的模块内事实**（随源码变），故转录成表并标注重跑入口。

用法：python engine/rust/tools/gen_output_tables.py
"""
import ast
import inspect
import pathlib
import sys

sys.path.insert(0, 'engine/rust/tools')
sys.path.insert(0, 'desktop/src')
from _rustlit import rs  # noqa: E402

import core.domain_metrics as dm  # noqa: E402
import core.quant_metrics as qm  # noqa: E402

ROOT = pathlib.Path('.').resolve()

# quant_metrics 的模块级名字（函数 + 类 + 模块级常量）——对应 Python 的 hasattr 命中面
src = pathlib.Path(inspect.getsourcefile(qm)).read_text(encoding='utf-8')
tree = ast.parse(src)
names = set()
for node in tree.body:
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
        names.add(node.name)
    elif isinstance(node, ast.Assign):
        for t in node.targets:
            if isinstance(t, ast.Name):
                names.add(t.id)
    elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
        names.add(node.target.id)
names = sorted(names)

families = sorted(str(x) for x in dm.FAMILIES)

out = [
    '//! `output_forms` 依赖的两张转录表 —— 由 `tools/gen_output_tables.py` 生成，**勿手改**。',
    '//!',
    '//! - `QUANT_METRICS_NAMES`：真源 `_check_quant_metrics` 用 `hasattr(qm, fn)` 判',
    '//!   「宣称的引擎是否真实存在」（宣称≠实现）；',
    '//! - `DOMAIN_FAMILIES`：真源 `_check_domain_report` 用它判「度量族是否在本仓登记」。',
    '//!',
    '//! ⚠️ 两者都随真源源码变。改了 `quant_metrics.py` / `domain_metrics.py` 后须重跑生成器，',
    '//! 否则对账会红（这正是要的：宁可红，也不要静默用旧表判"实现存在"）。',
    '',
    '// >>> GENERATED by tools/gen_output_tables.py（勿手改；重跑生成器覆盖本段）',
    '#[rustfmt::skip]',
    'pub const QUANT_METRICS_NAMES: [&str; %d] = [' % len(names),
]
out += ['    %s,' % rs(n) for n in names]
out += ['];', '', '#[rustfmt::skip]', 'pub const DOMAIN_FAMILIES: [&str; %d] = [' % len(families)]
out += ['    %s,' % rs(n) for n in families]
out += ['];', '// <<< GENERATED', '']

p = ROOT / 'engine/rust/src/output_tables.rs'
p.write_text('\n'.join(out), encoding='utf-8', newline='')
print('已生成 output_tables.rs：quant_metrics %d 名 / domain_metrics %d 族'
      % (len(names), len(families)))
