"""为 `payload_harvest.verify_backlog` 生成分支级判据（真源 4 个分支）。

用法：python engine/rust/tools/gen_type_backlog_branches.py
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
from core import payload_harvest as ph  # noqa: E402

BASE = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'type-backlog-branches'
if BASE.exists():
    shutil.rmtree(BASE)


def reg(fields):
    return {"schema": "community-event-registry/1",
            "events": {"ev_" + k: {"fields": {k: v}} for k, v in fields.items()}}


# ① 无声增长（无 note）+ 台账 count 不符
REG_KITCHEN = {"schema": "x", "events": {
    "e1": {"fields": {"a": {"type": "untyped"},                      # 无 note → 无声增长
                      "b": {"type": "untyped", "note": "有据"}}},
    "e2": {"fields": {"c": {"type": "string"}}},                     # 非 untyped 不计
}}
# ② 有 note 但台账缺件
REG_NOLEDGER = {"schema": "x", "events": {"e1": {"fields": {"a": {"type": "untyped", "note": "n"}}}}}
# ③ 台账坏 JSON
# ④ 全绿

SCENARIOS = {}
for name, r, ledger in (
    ('kitchen', REG_KITCHEN, json.dumps({"count": 99}, ensure_ascii=False)),
    ('noledger', REG_NOLEDGER, None),
    ('badjson', REG_NOLEDGER, "{ 这不是 JSON"),
    ('green', REG_NOLEDGER, json.dumps({"count": 1}, ensure_ascii=False)),
):
    fix = BASE / name
    (fix / 'protocol').mkdir(parents=True)
    (fix / 'protocol' / 'event_registry.json').write_text(
        json.dumps(r, ensure_ascii=False), encoding='utf-8', newline='')
    if ledger is not None:
        (fix / 'protocol' / 'type_backlog.json').write_text(ledger, encoding='utf-8', newline='')
    issues, stats = ph.verify_backlog(str(fix))
    SCENARIOS[name] = (issues, stats)
    print('# 场景 %s：issues=%d' % (name, len(issues)))
    for x in issues:
        print('#   ! %s' % x)
    print('# stats = %s' % json.dumps(stats, ensure_ascii=False, sort_keys=True))


def rj(s):
    assert '"#' not in s
    return 'r#"%s"#' % s


def arr(v):
    return "&[%s]" % ", ".join(json.dumps(x, ensure_ascii=False) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_type_backlog_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_type_backlog_branches.py` 从真源生成）=====
    ///
    /// 四场景：无声增长 + count 不符 / 有 note 但台账缺件 / 台账坏 JSON / 全绿。
    /// 分支：无 note 的 untyped（无声增长）/ 缺台账 / 台账不可解析 / 台账过期（count 不符）/ 全绿。
    const TB_REG_KITCHEN: &str = @@R1@@;
    const TB_REG_NOLEDGER: &str = @@R2@@;

    fn build_tb_fixture(scenario: &str, reg: &str, ledger: Option<&str>) -> std::path::PathBuf {
        let root = crate::testutil::fixture(&format!("type-backlog-branches-{}", scenario));
        std::fs::create_dir_all(root.join("protocol")).unwrap();
        std::fs::write(root.join("protocol/event_registry.json"), reg).unwrap();
        if let Some(l) = ledger {
            std::fs::write(root.join("protocol/type_backlog.json"), l).unwrap();
        }
        root
    }

    #[test]
    fn verify_backlog_matches_truth_source_in_all_four_scenarios() {
        for (scenario, reg, ledger, want_issues, want_untyped) in [
            ("kitchen", TB_REG_KITCHEN, Some(r#"{"count": 99}"#), @@I1@@ as &[&str], @@U1@@),
            ("noledger", TB_REG_NOLEDGER, None, @@I2@@ as &[&str], @@U2@@),
            ("badjson", TB_REG_NOLEDGER, Some("{ 这不是 JSON"), @@I3@@ as &[&str], @@U3@@),
            ("green", TB_REG_NOLEDGER, Some(r#"{"count": 1}"#), @@I4@@ as &[&str], @@U4@@),
        ] {
            let root = build_tb_fixture(scenario, reg, ledger);
            let (issues, stats) = verify_backlog(&root);
            assert_eq!(issues, want_issues, "场景 {} 的 issues", scenario);
            assert!(crate::jsonread::json_eq(
                &stats,
                &crate::jsonread::convert(&serde_json::json!({"untyped": want_untyped})).unwrap()
            ));
        }
    }
    // <<< GENERATED
'''

sc = SCENARIOS
text = (TEMPLATE
        .replace('@@R1@@', rj(json.dumps(REG_KITCHEN, ensure_ascii=False)))
        .replace('@@R2@@', rj(json.dumps(REG_NOLEDGER, ensure_ascii=False)))
        .replace('@@I1@@', arr(sc['kitchen'][0])).replace('@@U1@@', str(sc['kitchen'][1]['untyped']))
        .replace('@@I2@@', arr(sc['noledger'][0])).replace('@@U2@@', str(sc['noledger'][1]['untyped']))
        .replace('@@I3@@', arr(sc['badjson'][0])).replace('@@U3@@', str(sc['badjson'][1]['untyped']))
        .replace('@@I4@@', arr(sc['green'][0])).replace('@@U4@@', str(sc['green'][1]['untyped'])))

BEGIN = '    // >>> GENERATED by tools/gen_type_backlog_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]
path = ROOT / 'engine' / 'rust' / 'src' / 'payload_harvest.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    path.write_text(t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n'
                    + block + '}\n', encoding='utf-8', newline='')
    print('# 已追加标记区间')
