"""为三个小深度子扫描器生成差分判据：`payload_consumer` / `tool_face` / `world_slots`。

期望值从真源取（真语料整棵面）。

用法：python engine/rust/tools/gen_depth_small_cases.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import payload_consumer as pc  # noqa: E402
from core import tool_face as tf  # noqa: E402
from core import world_slots as ws  # noqa: E402


def arr(v):
    return "&[%s]" % ", ".join(rr(x) for x in v)


rows = []
for name, fn in (("payload_consumer_scan", pc.scan), ("tool_face_scan", tf.scan),
                 ("world_slots_scan", ws.scan)):
    issues, stats = fn(str(ROOT))
    rows.append((name, issues, stats))
    print('# %-22s issues=%d stats=%s' % (name, len(issues),
                                       json.dumps(stats, ensure_ascii=False, sort_keys=True)[:120]))

entries = []
for name, issues, stats in rows:
    entries.append('        (\n            %s,\n            %s,\n            %s\n        ),'
                   % (rr(name), arr(issues),
                      rr(json.dumps(stats, ensure_ascii=False, sort_keys=True))))

TEMPLATE = r'''
    // >>> GENERATED by tools/gen_depth_small_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== 三个小深度子扫描器（真实语料，期望值由生成器从真源取）=====
    #[test]
    fn depth_small_matches_truth_source() {
        let root = crate::testutil::repo_root();
        let cases: &[(&str, &[&str], &str)] = &[
@@CASES@@
        ];
        for (name, want_issues, want_stats) in cases {
            let (issues, stats) = match *name {
                "payload_consumer_scan" => payload_consumer_scan(&root),
                "tool_face_scan" => tool_face_scan(&root),
                "world_slots_scan" => world_slots_scan(&root),
                other => panic!("未知用例 {}", other),
            };
            assert_eq!(issues, want_issues.to_vec(), "{} 的 issues 不一致", name);
            let want: Json = crate::jsonread::convert(
                &serde_json::from_str::<serde_json::Value>(want_stats).unwrap(),
            )
            .unwrap();
            assert!(
                crate::jsonread::json_eq(&stats, &want),
                "{} 的 stats 不一致\n  实得 {}\n  期望 {}",
                name,
                stats.dumps(),
                want.dumps()
            );
        }
    }
    // <<< GENERATED
'''
text = TEMPLATE.replace('@@CASES@@', "\n".join(entries))
BEGIN = '    // >>> GENERATED by tools/gen_depth_small_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'depth_small.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')

# testutil 加 repo_root（判据要用真仓库根）
tu = ROOT / 'engine' / 'rust' / 'src' / 'testutil.rs'
tt = tu.read_text(encoding='utf-8')
if 'pub fn repo_root' not in tt:
    tt = tt.replace('/// 建一个**唯一**夹具目录并返回其路径（已建好、已清空）。',
                    '''/// 真仓库根（crate 在 `engine/rust/` 下，故上溯两级）。
///
/// 有些判据（如 `asset_contract` / 深度子扫描器）要的是**真语料**而不是合成夹具。
pub fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// 建一个**唯一**夹具目录并返回其路径（已建好、已清空）。''', 1)
    tu.write_text(tt, encoding='utf-8', newline='')
    print('# testutil 已加 repo_root')
print('# 已写入 %d 条小扫描器判据' % len(rows))
