"""为 `paths` / `output_forms._declared_out_rel` 生成差分判据。

① **真语料**：全部包 `outputs/INDEX.json` 里声明的每一条产出路经，比对 `_declared_out_rel`
   的结果（成功给相对路径 / 失败给 `ValueError` 文本）。
② **合成越界写法**：`../` 段、盘符写法 `C:foo`、备用数据流 `x.md:hidden`、控制字符、
   保留设备名 `CON`、`~` 开头、绝对路径、指向别的包。

用法：python engine/rust/tools/gen_paths_cases.py
"""
import glob
import json
import pathlib
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import output_forms as of  # noqa: E402


def outcome(pkg, rel):
    try:
        return ('ok', of._declared_out_rel(str(ROOT), pkg, rel))
    except ValueError as exc:
        return ('err', str(exc))


rows = []
for f in sorted(glob.glob('community/*/outputs/INDEX.json')):
    pkg = pathlib.Path(f).parts[1]
    try:
        idx = json.load(open(f, encoding='utf-8'))
    except Exception:
        continue
    for e in idx.get('outputs') or []:
        p = e.get('path')
        if p is None:
            continue
        rows.append((pkg, p, outcome(pkg, p)))
print('# 真语料声明路径 %d 条（成功 %d / 报错 %d）'
      % (len(rows), sum(1 for r in rows if r[2][0] == 'ok'), sum(1 for r in rows if r[2][0] == 'err')))

PKG = 'AI系统域包'
SYNTH = [
    ('plain', 'outputs/x.json'),
    ('sub dir', 'outputs/a/b.json'),
    ('already community', 'community/%s/outputs/x.json' % PKG),
    ('other pkg', 'community/别的包/outputs/x.json'),
    ('traversal', '../x.json'),
    ('traversal mid', 'outputs/../../x.json'),
    ('drive rel', 'C:foo.json'),
    ('abs backslash', '\\x.json'),
    ('abs slash', '/x.json'),
    ('tilde', '~/x.json'),
    ('ads', 'x.md:hidden'),
    ('control', 'ok\x00bad'),
    ('reserved', 'outputs/NUL'),
    ('reserved ext', 'outputs/CON.json'),
    ('empty', ''),
    ('blank', '   '),
]
syn = [(name, p, outcome(PKG, p)) for name, p in SYNTH]
for name, p, (kind, val) in syn:
    print('# 合成 %-18s %s → %s' % (name, kind, val[:88]))


def arr(v):
    return "&[%s]" % ", ".join(rr(str(x)) for x in v)


real_entries = "\n".join('        (%s, %s, %s, %s),' % (rr(p), rr(pk), rr(k), rr(v))
                         for pk, p, (k, v) in rows)
syn_entries = "\n".join('        (%s, %s, %s, %s),' % (rr(n), rr(p), rr(k), rr(v))
                        for n, p, (k, v) in syn)

TEMPLATE = r'''
    // >>> GENERATED by tools/gen_paths_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== ① 真语料：每条声明产出路径的 `_declared_out_rel`（成功/失败 + 文本）=====
    #[test]
    fn declared_out_rel_matches_truth_source_over_corpus() {
        let root = crate::testutil::repo_root();
        let cases: &[(&str, &str, &str, &str)] = &[
@@REAL@@
        ];
        for (path, pkg, want_kind, want_val) in cases {
            let got = declared_out_rel(&root, pkg, &Json::Str(path.to_string()));
            match (want_kind, got) {
                (&"ok", Ok(v)) => assert_eq!(&v, want_val, "{} 的产出路径", path),
                (&"ok", Err(e)) => panic!("{} 真源成功、本线报错：{}", path, e),
                (&"err", Ok(v)) => panic!("{} 真源报错、本线成功：{}", path, v),
                (&"err", Err(e)) => assert_eq!(&e, want_val, "{} 的报错文本", path),
                _ => panic!("未知期望 {}", want_kind),
            }
        }
    }

    /// ===== ② 合成越界写法（真语料全是合规路径，踩不到这些分支）=====
    #[test]
    fn declared_out_rel_rejects_escape_forms() {
        let root = crate::testutil::repo_root();
        let cases: &[(&str, &str, &str, &str)] = &[
@@SYN@@
        ];
        for (name, path, want_kind, want_val) in cases {
            let got = declared_out_rel(&root, "AI系统域包", &Json::Str(path.to_string()));
            match (want_kind, got) {
                (&"ok", Ok(v)) => assert_eq!(&v, want_val, "{}", name),
                (&"err", Err(e)) => assert_eq!(&e, want_val, "{} 的报错文本", name),
                (k, other) => panic!("{} 期望 {} 实得 {:?}", name, k, other.map(|v| v)),
            }
        }
    }
    // <<< GENERATED
'''
text = TEMPLATE.replace('@@REAL@@', real_entries).replace('@@SYN@@', syn_entries)
BEGIN = '    // >>> GENERATED by tools/gen_paths_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'output_forms.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入判据（真语料 %d 条 / 合成 %d 条）' % (len(rows), len(syn)))
