"""为 `pack_combo.scan` 生成差分判据（在盘证书复算 + 广度证明）。

用法：python engine/rust/tools/gen_pack_combo_cases.py
"""
import json
import pathlib
import sys
import time

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import pack_combo as pc  # noqa: E402

t0 = time.time()
issues, stats = pc.scan(str(ROOT))
print('# pack_combo.scan: issues=%d 用时 %.1fs' % (len(issues), time.time() - t0))
print('# breadth 摘要: %s'
      % json.dumps({k: v for k, v in stats['breadth'].items() if k != 'failures'},
                   ensure_ascii=False, sort_keys=True))
print('# declared_certificates =', stats['declared_certificates'])
for x in issues[:6]:
    print('#   ! %s' % x[:118])


def arr(v):
    return "&[%s]" % ", ".join(rr(str(x)) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_pack_combo_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== 真语料差分（期望值由生成器从真源取）=====
    ///
    /// 覆盖：**在盘组合证书复算**（schema + 逐字段比对）+ **广度证明**（6,105 组两两 + 780 组抽样）。
    /// 抽样器由 `pyrandom` 的判据单独钉住；本条钉的是「同一批组合 → 同一批判决 → 同一份 stats」。
    #[test]
    fn pack_combo_matches_truth_source() {
        let root = crate::testutil::repo_root();
        let (issues, stats) = scan(&root);
        assert_eq!(issues, @@ISSUES@@ as &[&str], "issues 须逐字且同序");
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@WANT@@).unwrap(),
        )
        .unwrap();
        assert!(crate::jsonread::json_eq(&stats, &want),
                "stats 不一致\n  实得 {}\n  期望 {}", stats.dumps(), want.dumps());
    }
    // <<< GENERATED
'''
text = (TEMPLATE.replace('@@ISSUES@@', arr(issues))
        .replace('@@WANT@@', rr(json.dumps(stats, ensure_ascii=False, sort_keys=True))))
BEGIN = '    // >>> GENERATED by tools/gen_pack_combo_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'pack_combo_core.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入 pack_combo 判据（issues %d 条）' % len(issues))
