"""为 `io_types.scan` 生成分支级判据（真源 issues 与 warns 两侧都要核）。

契约 `_c_io_types` 只看 issues + coverage，**warns 无人消费**——而 warns 里恰含实质判据
（`io_types.outputs`/`inputs` 与 `machine_contract` 的键集对齐、未标、L0）。故本判据两侧都比。

用法：python engine/rust/tools/gen_io_types_branches.py
"""
import json
from _rustlit import rs  # noqa: E402
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
from core import io_types as iot  # noqa: E402

BASE = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'io-types-branches'
if BASE.exists():
    shutil.rmtree(BASE)


def mc(body):
    return "```yaml\nmachine_contract:\n" + body + "```\n"


MODS = {
    # L0：无机读契约
    'M90-l0.md': "# 无契约\n正文\n",
    # 有 id 但没标 io_types → warn「未标」
    'M91-unmarked.md': mc("  id: M91\n  outputs: [a]\n"),
    # 越词表 + 键集两边都不一致（outputs 缺 a 多 b；inputs 缺 x 多 y）+ typed/untyped 计数
    'M92-badkind.md': mc(
        "  id: M92\n"
        "  outputs: [a]\n"
        "  inputs: [x]\n"
        "  io_types:\n"
        "    outputs:\n"
        "      b: 不存在的类型\n"
        "      c: untyped\n"
        "    inputs:\n"
        "      y: untyped\n"
    ),
    # 提供方：outputs foo → number
    'M93-provider.md': mc(
        "  id: M93\n"
        "  outputs: [foo]\n"
        "  io_types:\n"
        "    outputs:\n"
        "      foo: number\n"
    ),
    # 消费方：期望 string（提供方只声明 number）→ 类型不匹配；state/untyped 应被跳过
    'M94-consumer.md': mc(
        "  id: M94\n"
        "  inputs: [M93, M95, M96]\n"
        "  io_types:\n"
        "    outputs: {}\n"
        "    inputs:\n"
        "      M93: string\n"
        "      M95: state\n"
        "      M96: untyped\n"
    ),
    # 跨包依赖键含冒号（旧模式读不出来的那类）+ 显式空段
    'M95-colonkey.md': mc(
        "  id: M95\n"
        "  outputs: []\n"
        "  io_types:\n"
        "    outputs: {}\n"
        "    inputs:\n"
        "      'AI保险:M01': untyped\n"
    ),
    # 全绿：键集一致、类型在册
    'M96-green.md': mc(
        "  id: M96\n"
        "  outputs: [g]\n"
        "  outputs: [g]\n"
        "  io_types:\n"
        "    outputs:\n"
        "      g: event\n"
        "    inputs: {}\n"
    ),
}
(FIX := BASE / 'kitchen').mkdir(parents=True)
(FIX / '04_模块库' / '通用类').mkdir(parents=True)
for name, body in MODS.items():
    (FIX / '04_模块库' / '通用类' / name).write_text(body, encoding='utf-8', newline='')

issues, warns, stats = iot.scan(str(FIX))
cov = iot.coverage(str(FIX))

print('# 真源：issues=%d warns=%d' % (len(issues), len(warns)))
for x in issues:
    print('#   ! %s' % x)
for x in warns:
    print('#   ~ %s' % x)
print('# stats = %s' % json.dumps(stats, ensure_ascii=False, sort_keys=True))
print('# coverage = %s' % cov['coverage'])


def rj(s):
    assert '"#' not in s
    return 'r#"%s"#' % s


def arr(v):
    return "&[%s]" % ", ".join(json.dumps(x, ensure_ascii=False) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_io_types_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_io_types_branches.py` 从真源生成）=====
    ///
    /// 契约只看 issues + coverage，**warns 无消费者**——而 warns 里含实质判据（键集对齐、未标、L0），
    /// 故本判据**两侧都比**（warns 正是靠这里才不是"没人核的代码"）。
    /// 分支：L0 件 / 未标 io_types / 类型越词表 / 输出键集不一致 / 输入键集不一致 /
    /// 类型不匹配（提供方有声明但无一匹配）/ `state` 与 `untyped` 跳过 / 含冒号的跨包键 /
    /// 显式空段 `outputs: {}` / 全绿。
    const IOT_MODS: [(&str, &str); @@NM@@] = [
@@MODS@@
    ];

    fn build_io_types_fixture() -> std::path::PathBuf {
        let root = crate::testutil::fixture("io-types-branches");
        let dir = root.join("04_模块库/通用类");
        std::fs::create_dir_all(&dir).unwrap();
        for (name, body) in IOT_MODS {
            std::fs::write(dir.join(name), body).unwrap();
        }
        root
    }

    #[test]
    fn scan_matches_truth_source_on_both_sides() {
        let root = build_io_types_fixture();
        let got = scan(&root);
        assert_eq!(got.issues, @@ISSUES@@ as &[&str], "issues 须逐字且同序");
        assert_eq!(got.warns, @@WARNS@@ as &[&str], "warns 须逐字且同序");
        assert!(crate::jsonread::json_eq(
            &got.stats,
            &crate::jsonread::convert(&serde_json::json!({
                "modules_with_contract": @@MW@@, "l0_modules": @@L0@@,
                "typed_fields": @@TF@@, "untyped_fields": @@UF@@
            }))
            .unwrap()
        ));
    }

    #[test]
    fn coverage_matches_the_truth_source() {
        let root = build_io_types_fixture();
        let (_s, cov) = coverage(&root);
        assert_eq!(cov, @@COV@@, "覆盖率（一位小数、正确舍入）");
    }
    // <<< GENERATED
'''

sc = (issues, warns, stats, cov['coverage'])
text = (TEMPLATE
        .replace('@@NM@@', str(len(MODS)))
        .replace('@@MODS@@', "\n".join('        (%s, %s),' % (rs(k), rj(v))
                                       for k, v in sorted(MODS.items())))
        .replace('@@ISSUES@@', arr(issues))
        .replace('@@WARNS@@', arr(warns))
        .replace('@@MW@@', str(stats['modules_with_contract']))
        .replace('@@L0@@', str(stats['l0_modules']))
        .replace('@@TF@@', str(stats['typed_fields']))
        .replace('@@UF@@', str(stats['untyped_fields']))
        .replace('@@COV@@', repr(float(cov['coverage']))))

BEGIN = '    // >>> GENERATED by tools/gen_io_types_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]
path = ROOT / 'engine' / 'rust' / 'src' / 'io_types.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    path.write_text(t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n'
                    + block + '}\n', encoding='utf-8', newline='')
    print('# 已追加标记区间')
