"""为 `endpoint.scan` 生成分支级判据（真源 20+ 个 issue 分支）。

用法：python engine/rust/tools/gen_endpoint_branches.py
"""
import json
from _rustlit import rs  # noqa: E402
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
from core import endpoint as ep  # noqa: E402

BASE = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'endpoint-branches'
if BASE.exists():
    shutil.rmtree(BASE)

# CLI 注册表：真源用 `sub.add_parser("名")` 抽子命令
NF_PY = (
    "import argparse\n"
    "sub = argparse.ArgumentParser().add_subparsers()\n"
    'sub.add_parser("library")\n'
    'sub.add_parser("stats")\n'
)

KITCHEN = {
    "schema": "wrong/1",                      # schema 不匹配
    "status": "越词表",                        # status 越词表
    # conventions 缺 streaming / deprecation / idempotency（三处都踩）
    "endpoints": [
        {"id": "e1", "method": "FETCH", "path": "/a", "maps_to": "nf nope"},          # method 越词表 + CLI 无法解析
        {"id": "e1", "method": "GET", "path": "/a", "streaming": True,
         "maps_to": "no_such_tool（MCP 工具）"},                                        # id 重复 + streaming 无约定 + MCP 不存在
        {"id": "e3", "method": "GET", "path": "/a", "maps_to": "nf stats"},           # method+path 重复
        {"id": "e4", "method": "POST", "path": "/b", "maps_to": "nf library",
         "deprecated": "yes", "sunset": "2026/01/01"},                                # deprecated 非布尔 + sunset 不合法 + 缺 replacement
        {"id": "e5", "method": "POST", "path": "/c", "maps_to": "nf library",
         "sunset": "2026-01-01"},                                                      # 未 deprecated 却带 sunset
    ],
    "idempotency_exceptions": [
        {"id": "nope", "mode": "idempotent", "why": "w"},                              # 指向不存在端点
        {"id": "e3", "mode": "bogus", "why": "w"},                                     # mode 越词表
        {"id": "e3", "mode": "idempotent", "why": "w"},                                # 重复登记
        {"id": "e4", "mode": "non-idempotent", "key": "bogus", "why": ""},             # key 越词表 + 缺 why
        {"id": "e5", "mode": "non-idempotent", "key": "required", "why": "w"},         # required 但 conventions 未定义幂等
    ],
}
GREEN = {
    "schema": "nf-endpoint/1",
    "status": "implemented",
    "conventions": {"idempotency": "默认幂等", "deprecation": "见 RFC 8594",
                    "streaming": "SSE"},
    "endpoints": [
        {"id": "g1", "method": "GET", "path": "/g", "maps_to": "nf stats"},
        {"id": "g2", "method": "POST", "path": "/h", "maps_to": "library_read（MCP 工具）",
         "streaming": True},
    ],
    "idempotency_exceptions": [
        {"id": "g2", "mode": "non-idempotent", "key": "required", "why": "重放会重复借阅"},
    ],
}

SCENARIOS = {}
for name, contract in (('kitchen', KITCHEN), ('green', GREEN), ('nodecl', None)):
    fix = BASE / name
    (fix / 'protocol').mkdir(parents=True)
    (fix / 'scripts').mkdir(parents=True)
    if contract is not None:
        (fix / 'protocol' / 'endpoint_contract.json').write_text(
            json.dumps(contract, ensure_ascii=False), encoding='utf-8', newline='')
    (fix / 'scripts' / 'nf.py').write_text(NF_PY, encoding='utf-8', newline='')
    issues, warns, stats = ep.scan(str(fix))
    SCENARIOS[name] = (issues, warns, stats)
    print('# 场景 %s：issues=%d warns=%d' % (name, len(issues), len(warns)))
    for x in issues:
        print('#   ! %s' % x)
    print('# stats = %s' % json.dumps(stats, ensure_ascii=False, sort_keys=True))


def rj(s):
    assert '"#' not in s
    return 'r#"%s"#' % s


def arr(v):
    return "&[%s]" % ", ".join(json.dumps(x, ensure_ascii=False) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_endpoint_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_endpoint_branches.py` 从真源生成）=====
    ///
    /// 三场景：kitchen（逐分支）/ 全绿 / 缺契约。分支：schema / status 越词表 /
    /// endpoint id 重复 / method 越词表 / method+path 重复 / streaming 无 SSE 约定 /
    /// maps_to 的 MCP 工具不存在 / maps_to 无法解析为现存 CLI 子命令 /
    /// deprecated 非布尔 / deprecated 但 status≠implemented / 无弃用约定 / sunset 不合规 /
    /// 缺 replacement / replacement 指向不存在端点 / 未 deprecated 却带 sunset /
    /// conventions 未声明幂等 / 幂等例外指向不存在端点 / 重复登记 / mode 越词表 /
    /// key 越词表 / required 但无幂等语义 / 缺 why。
    ///
    /// **移植面**：真源 `scan` 还返回 warns（`status == proposed` 的提示），但契约只看 issues，
    /// 故本线结构体未纳入；`want_warns` 仅作记录。
    const EP_KITCHEN: &str = @@KITCHEN@@;
    const EP_GREEN: &str = @@GREEN@@;
    const EP_NF_PY: &str = @@NFPY@@;

    fn build_endpoint_fixture(scenario: &str, contract: Option<&str>) -> std::path::PathBuf {
        let root = crate::testutil::fixture(&format!("endpoint-branches-{}", scenario));
        std::fs::create_dir_all(root.join("protocol")).unwrap();
        std::fs::create_dir_all(root.join("scripts")).unwrap();
        if let Some(c) = contract {
            std::fs::write(root.join("protocol/endpoint_contract.json"), c).unwrap();
        }
        std::fs::write(root.join("scripts/nf.py"), EP_NF_PY).unwrap();
        root
    }

    #[test]
    fn scan_matches_truth_source_in_all_three_scenarios() {
        // 真源 `scan` 还返回 warns（`status == proposed` 的提示），但契约只看 issues，
        // 故本线结构体未纳入移植面——`want_warns` 仅作记录，不参与断言。
        for (scenario, contract, want_issues, want_warns, want_stats) in [
            (
                "kitchen",
                Some(EP_KITCHEN),
                @@I1@@ as &[&str],
                @@W1@@ as &[&str],
                @@S1@@,
            ),
            ("green", Some(EP_GREEN), @@I2@@ as &[&str], @@W2@@ as &[&str], @@S2@@),
            ("nodecl", None, @@I3@@ as &[&str], @@W3@@ as &[&str], @@S3@@),
        ] {
            let root = build_endpoint_fixture(scenario, contract);
            let got = scan(&root);
            assert_eq!(got.issues, want_issues, "场景 {} 的 issues", scenario);
            let _ = want_warns;
            // 比 JSON 语义（对象键序无关）——本线用真源字典的**插入序**，而生成器把期望值排了序，
            // 直接 `assert_eq!` 会得到**假失败**（值本就相同）。
            assert!(
                crate::jsonread::json_eq(&got.stats, &want_stats),
                "场景 {} 的 stats：实得 {:?}",
                scenario,
                got.stats
            );
        }
    }
    // <<< GENERATED
'''


def stats_rust(s):
    """把真源 stats 转成 Rust 的 `Json` 构造（计数与字符串各归其位）。"""
    parts = []
    for k in sorted(s):
        v = s[k]
        if isinstance(v, str):
            parts.append('("{}".to_string(), crate::pyjson::Json::Str({}.to_string()))'
                         .format(k, json.dumps(v, ensure_ascii=False)))
        else:
            parts.append('("{}".to_string(), crate::pyjson::Json::Int({}))'.format(k, v))
    return 'crate::pyjson::Json::Object(vec![%s])' % ', '.join(parts)


sc = SCENARIOS
text = (TEMPLATE
        .replace('@@KITCHEN@@', rj(json.dumps(KITCHEN, ensure_ascii=False)))
        .replace('@@GREEN@@', rj(json.dumps(GREEN, ensure_ascii=False)))
        .replace('@@NFPY@@', rj(NF_PY))
        .replace('@@I1@@', arr(sc['kitchen'][0])).replace('@@W1@@', arr(sc['kitchen'][1]))
        .replace('@@I2@@', arr(sc['green'][0])).replace('@@W2@@', arr(sc['green'][1]))
        .replace('@@I3@@', arr(sc['nodecl'][0])).replace('@@W3@@', arr(sc['nodecl'][1]))
        .replace('@@S1@@', stats_rust(sc['kitchen'][2]))
        .replace('@@S2@@', stats_rust(sc['green'][2]))
        .replace('@@S3@@', stats_rust(sc['nodecl'][2])))

BEGIN = '    // >>> GENERATED by tools/gen_endpoint_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]
path = ROOT / 'engine' / 'rust' / 'src' / 'endpoint.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    path.write_text(t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n'
                    + block + '}\n', encoding='utf-8', newline='')
    print('# 已追加标记区间')
