"""为 `pipelinerun.sweep` / `_c_pipeline_dryrun` 生成分支级判据。

真语料上该契约**全绿**（0 issues / 114 管线 / 1142 advisory）⇒ 对账核不到任何错误分支，
故必须用合成夹具逐分支核。

## 一支刻意不覆盖（死代码，已实证）

真源 `graph` 的 **hard** 分支「依赖序违约」（`dep_layer > idx`）在 `sweep` 路径上**不可达**：
`layer_of` 只在处理**当前层**时写入（`layer_of[mid] = idx`），而层是按升序处理的，
故 `layer_of` 里任何值都 ≤ 当前 idx，`>` 永不成立。**不编造夹具去"覆盖"它**。

用法：python engine/rust/tools/gen_pipeline_dryrun_branches.py
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
from core import conformance_report as cr  # noqa: E402
from core import pipelinerun as pr  # noqa: E402

BASE = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'pipeline-branches'
if BASE.exists():
    shutil.rmtree(BASE)

KITCHEN = {
    'desktop/src/core/registry.json': json.dumps(
        {"modules": [{"id": "M00"}, {"id": "M99"}]}, ensure_ascii=False),
    '04_模块库/通用类/M00_基座.md': (
        "```yaml\nmachine_contract:\n  id: M00\n  outputs: [tok0]\n"
        "  events:\n    publish: [ev_base]\n```\n"),
    '04_模块库/通用类/README.md': "# 说明，必须被跳过\n",
    '04_模块库/通用类/M10_a.md': (
        "```yaml\nmachine_contract:\n  id: M10\n  inputs: [M99, M11, Ghostx]\n"
        "  outputs: [tokc]\n  events:\n    subscribe: [ev_orphan]\n"
        "  io_types:\n    outputs:\n      tokc: number\n"
        "    inputs:\n      M11: object\n```\n"),
    '04_模块库/通用类/M11_b.md': (
        "```yaml\nmachine_contract:\n  id: M11\n  outputs: [tokd]\n"
        "  io_types:\n    outputs:\n      tokc: string\n      tokd: number\n```\n"),
    # mc.id 用长名（情感类:M22）；管线里用短名（情感:M22）⇒ 走 fid_key 归一
    '04_模块库/情感类/M22_c.md': (
        "```yaml\nmachine_contract:\n  id: 情感类:M22\n  outputs: [toke]\n```\n"),
    '03_管线库/P01_测试.md': (
        "```yaml\nPipeline:\n  id: P01\n  name: 测试\n  structure:\n    type: linear\n"
        "  layers:\n"
        "    - id: L1\n      default_modules: [M00]\n"
        "    - id: L2\n      default_modules: [M10, M11, GhostMod]\n"
        "    - id: L3\n      default_modules: [情感:M22]\n```\n"),
}

# 解析失败：没有 yaml 围栏 ⇒ graph 抛 ValueError ⇒ sweep 整体 Err
BAD = dict(KITCHEN)
BAD.pop('03_管线库/P01_测试.md')
BAD['03_管线库/P02_坏件.md'] = "没有围栏的正文\n"

# 零管线
NONE = {k: v for k, v in KITCHEN.items() if not k.startswith('03_管线库/')}

SCENARIOS = {}
for name, files in (('kitchen', KITCHEN), ('parsefail', BAD), ('nopipelines', NONE)):
    fix = BASE / name
    for rel, body in files.items():
        p = fix / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body, encoding='utf-8', newline='')

    err = None
    try:
        issues, tot = pr.sweep(str(fix))
        pipelines, notes = tot['pipelines'], tot['notes']
    except Exception as exc:                      # noqa: BLE001
        err = str(exc)
        issues, pipelines, notes = [], 0, 0
    try:
        ok, detail = cr._c_pipeline_dryrun(str(fix))
    except Exception as exc:      # noqa: BLE001 —— 对齐真源 `_run_impl` 的兜底
        ok, detail = False, "契约执行异常：%s" % exc
    # 夹具根归一成 <ROOT>：Rust 侧用 `testutil::fixture`（带进程号 + 序号隔离），
    # 两侧目录名必然不同；消息里的绝对路径只差这一段，归一后才可比。
    fix_posix = str(fix).replace('\\', '/')
    err = err.replace(fix_posix, '<ROOT>') if err else err
    detail = detail.replace(fix_posix, '<ROOT>')
    SCENARIOS[name] = {
        'issues': issues, 'pipelines': pipelines, 'notes': notes,
        'err': err, 'ok': ok, 'detail': detail,
    }
    print('# 场景 %s：err=%r pipelines=%d notes=%d ok=%s' % (name, err, pipelines, notes, ok))
    for x in issues:
        print('#   ! %s' % x)
    print('#   detail = %s' % detail)


def rj(s):
    assert '"#' not in s
    return 'r#"%s"#' % s


def arr(v):
    return "&[%s]" % ", ".join(json.dumps(x, ensure_ascii=False) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_pipeline_dryrun_branches.py（勿手改；重跑生成器覆盖本段）
    /// ===== 分支级差分判据（期望值由 `tools/gen_pipeline_dryrun_branches.py` 从真源生成）=====
    ///
    /// 真语料上该契约**全绿**（0 issues / 114 管线 / 1142 advisory）⇒ 对账核不到错误分支。
    /// 三场景：kitchen（逐分支）/ 管线解析失败 / 零管线。
    ///
    /// 覆盖：模块未在仓库找到（hard）/ 同层依赖序（advisory）/ 跨包外部依赖（advisory）/
    /// 跨包外部事件（advisory）/ 类型冲突 / 类型不匹配 / 基座模块进池 / `fid_key` 长短名归一 /
    /// `README.md` 跳过 / 解析失败 ⇒ 契约记「契约执行异常：…」。
    ///
    /// ⚠️ **一支刻意不覆盖**：真源 `graph` 的 hard 分支「依赖序违约」（`dep_layer > idx`）在
    /// `sweep` 路径上**不可达**——`layer_of` 只在处理当前层时写入，层按升序处理 ⇒ 任何值都
    /// ≤ 当前 idx，`>` 永不成立。**不编造夹具去"覆盖"死代码**。
    const PB_KITCHEN: [(&str, &str); @@N1@@] = [
@@F1@@
    ];
    const PB_BAD: [(&str, &str); @@N2@@] = [
@@F2@@
    ];
    const PB_NONE: [(&str, &str); @@N3@@] = [
@@F3@@
    ];

    fn build_pb_fixture(scenario: &str, files: &[(&str, &str)]) -> std::path::PathBuf {
        let root = crate::testutil::fixture(&format!("pipeline-branches-{}", scenario));
        for (rel, body) in files {
            let p = root.join(rel);
            std::fs::create_dir_all(p.parent().unwrap()).unwrap();
            std::fs::write(p, body).unwrap();
        }
        root
    }

    #[test]
    fn sweep_matches_truth_source_branch_by_branch() {
        for (scenario, files, want_issues, want_pipelines, want_notes, want_err, want_detail) in [
            ("kitchen", &PB_KITCHEN[..], @@I1@@ as &[&str], @@P1@@, @@NO1@@, None, @@D1@@),
            ("parsefail", &PB_BAD[..], @@I2@@ as &[&str], @@P2@@, @@NO2@@, Some(@@E2@@), @@D2@@),
            ("nopipelines", &PB_NONE[..], @@I3@@ as &[&str], @@P3@@, @@NO3@@, None, @@D3@@),
        ] {
            let root = build_pb_fixture(scenario, files);
            match (sweep(&root), want_err) {
                (Ok(s), None) => {
                    assert_eq!(s.issues, want_issues, "场景 {} 的 issues", scenario);
                    assert_eq!(s.pipelines, want_pipelines, "场景 {} 的管线条数", scenario);
                    assert_eq!(s.notes, want_notes, "场景 {} 的 advisory 数", scenario);
                    let detail = if s.issues.is_empty() {
                        format!("管线 {} 条零 hard 缺陷（advisory {}）", s.pipelines, s.notes)
                    } else {
                        s.issues.iter().take(2).cloned().collect::<Vec<_>>().join("; ")
                    };
                    assert_eq!(detail, want_detail, "场景 {} 的契约 detail", scenario);
                }
                (Err(msg), Some(want)) => {
                    // 夹具根归一：两侧目录名不同（Rust 侧带进程号隔离），消息里的绝对路径只差这一段
                    let root_posix = root.to_string_lossy().replace('\\', "/");
                    let norm = |s: &str| s.replace(&root_posix, "<ROOT>");
                    assert_eq!(norm(&msg), want, "场景 {} 的异常消息", scenario);
                    assert_eq!(
                        norm(&format!("契约执行异常：{}", msg)),
                        want_detail,
                        "场景 {} 的契约 detail", scenario
                    );
                }
                (got, _) => panic!("场景 {} 的成败不符：{:?}", scenario, got.is_ok()),
            }
        }
    }
    // <<< GENERATED
'''


def files_rust(files):
    return "\n".join('        (%s, %s),' % (json.dumps(k, ensure_ascii=False), rj(v))
                     for k, v in sorted(files.items()))


sc = SCENARIOS
text = (TEMPLATE
        .replace('@@N1@@', str(len(KITCHEN))).replace('@@F1@@', files_rust(KITCHEN))
        .replace('@@N2@@', str(len(BAD))).replace('@@F2@@', files_rust(BAD))
        .replace('@@N3@@', str(len(NONE))).replace('@@F3@@', files_rust(NONE))
        .replace('@@I1@@', arr(sc['kitchen']['issues']))
        .replace('@@I2@@', arr(sc['parsefail']['issues']))
        .replace('@@I3@@', arr(sc['nopipelines']['issues']))
        .replace('@@P1@@', str(sc['kitchen']['pipelines']))
        .replace('@@P2@@', str(sc['parsefail']['pipelines']))
        .replace('@@P3@@', str(sc['nopipelines']['pipelines']))
        .replace('@@NO1@@', str(sc['kitchen']['notes']))
        .replace('@@NO2@@', str(sc['parsefail']['notes']))
        .replace('@@NO3@@', str(sc['nopipelines']['notes']))
        .replace('@@E2@@', rj(sc['parsefail']['err'] or ''))
        .replace('@@D1@@', json.dumps(sc['kitchen']['detail'], ensure_ascii=False))
        .replace('@@D2@@', json.dumps(sc['parsefail']['detail'], ensure_ascii=False))
        .replace('@@D3@@', json.dumps(sc['nopipelines']['detail'], ensure_ascii=False)))

BEGIN = '    // >>> GENERATED by tools/gen_pipeline_dryrun_branches.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]
path = ROOT / 'engine' / 'rust' / 'src' / 'pipelinerun.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    path.write_text(t[:a] + block + t[b:], encoding='utf-8', newline='')
    print('# 已刷新标记区间')
else:
    path.write_text(t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n'
                    + block + '}\n', encoding='utf-8', newline='')
    print('# 已追加标记区间')
