"""为 `domain_pack.scan` 生成差分判据（真语料 + 缺名录的中性通过支）。

用法：python engine/rust/tools/gen_domain_pack_cases.py
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path('.').resolve()
sys.path.insert(0, str(ROOT / 'desktop' / 'src'))
sys.path.insert(0, str(ROOT / 'engine' / 'rust' / 'tools'))
from _rustlit import raw as rr  # noqa: E402
from core import domain_pack as dp  # noqa: E402

issues, stats = dp.manifest_verify(str(ROOT))
print('# manifest_verify: issues=%d stats=%s'
      % (len(issues), json.dumps(stats, ensure_ascii=False, sort_keys=True)[:160]))
for x in issues[:6]:
    print('#   ! %s' % x[:118])

# 缺名录 ⇒ 中性通过支
FIX = ROOT / 'engine' / 'rust' / 'target' / 'test-fixtures' / 'domain-pack-empty'
if FIX.exists():
    shutil.rmtree(FIX)
FIX.mkdir(parents=True)
i2, s2 = dp.manifest_verify(str(FIX))
print('# 缺名录: issues=%d stats=%s' % (len(i2), json.dumps(s2, ensure_ascii=False, sort_keys=True)))


def arr(v):
    return "&[%s]" % ", ".join(rr(str(x)) for x in v)


TEMPLATE = r'''
    // >>> GENERATED by tools/gen_domain_pack_cases.py（勿手改；重跑生成器覆盖本段）
    /// ===== 真语料差分（期望值由生成器从真源取）=====
    #[test]
    fn domain_pack_matches_truth_source() {
        let root = crate::testutil::repo_root();
        let (issues, stats) = scan(&root);
        assert_eq!(issues, @@ISSUES@@ as &[&str], "issues 须逐字且同序");
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@WANT@@).unwrap(),
        )
        .unwrap();
        assert!(crate::jsonread::json_eq(&stats, &want),
                "stats 不一致\n  实得 {}\n  期望 {}", stats.dumps(), want.dumps());
    }

    /// 缺名录时的**中性通过**支（真语料有名录，踩不到）。
    #[test]
    fn domain_pack_without_manifest_is_neutral() {
        let root = crate::testutil::fixture("domain-pack-empty");
        let (issues, stats) = scan(&root);
        assert_eq!(issues, @@I2@@ as &[&str]);
        let want: Json = crate::jsonread::convert(
            &serde_json::from_str::<serde_json::Value>(@@S2@@).unwrap(),
        )
        .unwrap();
        assert!(crate::jsonread::json_eq(&stats, &want), "缺名录 stats 不一致");
    }
    // <<< GENERATED
'''
text = (TEMPLATE.replace('@@ISSUES@@', arr(issues))
        .replace('@@WANT@@', rr(json.dumps(stats, ensure_ascii=False, sort_keys=True)))
        .replace('@@I2@@', arr(i2))
        .replace('@@S2@@', rr(json.dumps(s2, ensure_ascii=False, sort_keys=True))))
BEGIN = '    // >>> GENERATED by tools/gen_domain_pack_cases.py（勿手改；重跑生成器覆盖本段）\n'
END = '    // <<< GENERATED\n'
block = BEGIN + text.split(BEGIN, 1)[1]

path = ROOT / 'engine' / 'rust' / 'src' / 'domain_pack.rs'
t = path.read_text(encoding='utf-8')
if BEGIN in t:
    a = t.index(BEGIN)
    b = t.index(END, a) + len(END)
    t = t[:a] + block + t[b:]
else:
    t = t.rstrip() + '\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n}\n'
    t = t.rstrip()[:-1].rstrip() + '\n' + block + '}\n'
path.write_text(t, encoding='utf-8', newline='')
print('# 已写入 domain_pack 判据（真语料 %d 条 issue）' % len(issues))
